import {existsSync,statSync} from "node:fs";import path from "node:path";import {describe,expect,it} from "vitest";
import {getElaPtFlow} from "@/lib/assessment-flow";import {getManualRubric} from "@/lib/manual-rubrics";import {getQuestions,type Question} from "@/lib/questions";import {scoreResponse} from "@/lib/scoring";import {evaluateGrade4Test5} from "@/lib/validation/grade4-test5";
const section=(s:"math"|"ela",t:"cat"|"pt")=>getQuestions(4,s,t,5,{includeUnavailable:true});const mc=()=>section("math","cat"),mp=()=>section("math","pt"),ec=()=>section("ela","cat"),ep=()=>section("ela","pt");const all=()=>[...mc(),...mp(),...ec(),...ep()];const wc=(v:string)=>v.trim().split(/\s+/).filter(Boolean).length;
describe("Grade 4 Test 5 locked Hard bank",()=>{
it("passes its independent full-form fixture",()=>expect(evaluateGrade4Test5()).toMatchObject({passed:true,errors:[],warnings:[],reviewedItems:69}));
it("matches the 69-item, 81-point scaffold and claim distributions",()=>{expect([mc().length,mp().length,ec().length,ep().length]).toEqual([31,5,30,3]);expect([mc(),mp(),ec(),ep()].map(q=>q.reduce((n,x)=>n+x.points,0))).toEqual([32,6,30,13]);expect(new Set(all().map(q=>q.id)).size).toBe(69);expect(mc().reduce((n,q)=>(n[q.claim-1]++,n),[0,0,0,0])).toEqual([17,3,8,3]);expect(ec().reduce((n,q)=>(n[q.claim-1]++,n),[0,0,0,0])).toEqual([15,6,6,3])});
it("locks the intended Hard DOK profile",()=>{expect(mc().reduce((n,q)=>(n[q.dok]=(n[q.dok]||0)+1,n),{} as Record<number,number>)).toEqual({2:13,3:16,4:2});expect(ec().reduce((n,q)=>(n[q.dok]=(n[q.dok]||0)+1,n),{} as Record<number,number>)).toEqual({2:11,3:19})});
it("registers Part 1 and the separate full write",()=>expect(getElaPtFlow(4,5)).toMatchObject({part1ItemIds:[49101,49102],part2ItemIds:[49103]}));
it("rejects content and provenance changes",()=>{const changed=structuredClone(ec());changed[0].questionText+=" changed";changed[1].provenance!.sourceId="";const r=evaluateGrade4Test5({"ela-cat":changed});expect(r.passed).toBe(false);expect(r.errors.some(e=>e.field==="canonicalSha256")).toBe(true);expect(r.errors.some(e=>e.field==="provenance.sourceId")).toBe(true)});
});
describe("Grade 4 Test 5 scoring contracts",()=>{
it("scores all keys and marks only rubric tasks manual",()=>{for(const q of all())expect(scoreResponse(q,q.correctAnswer).status,`item ${q.id}`).toBe(q.scoringRule?.kind==="manual-rubric"?"manual":"correct")});
it("enforces independent partial credit",()=>{const q=mc().find(x=>x.id===48020)!;expect(scoreResponse(q,["560","3108"])).toMatchObject({earnedPoints:2,status:"correct"});expect(scoreResponse(q,["560","3000"])).toMatchObject({earnedPoints:1,status:"partial"});expect(scoreResponse(q,["320","3000"]).status).toBe("incorrect")});
it("tests crate cost/capacity/parity boundaries",()=>{const q=mc().find(x=>x.id===48030)!;for(const a of [["4","4"],["6","2"]])expect(scoreResponse(q,a).status).toBe("correct");for(const a of [["2","4"],["4","3"],["4.5","4"],["8","4"]])expect(scoreResponse(q,a).status).toBe("incorrect")});
it("tests two-trip load, container, total, and integer boundaries",()=>{const q=mp().find(x=>x.id===48105)!;for(const a of [["2","3","1","5"],["2","4","2","3"]])expect(scoreResponse(q,a).status).toBe("correct");for(const a of [["2","3","1","4"],["2","2","1","5"],["2.5","3","1","5"],["5","2","1","5"]])expect(scoreResponse(q,a).status).toBe("incorrect")});
it("enforces PT 1/2/1 source cardinality",()=>{const q=ep().find(x=>x.id===49102)!;expect(q.gridSelection?.rowSelections).toEqual([{min:1,max:1},{min:2,max:2},{min:1,max:1}]);expect(scoreResponse(q,["0:0","1:1","1:2","2:2"]).status).toBe("correct");expect(scoreResponse(q,["0:0","1:1","2:2"]).status).toBe("incorrect")});
it("registers all manual rubrics",()=>{for(const id of [48104,49101,49103]){const q=all().find(x=>x.id===id)!;expect(getManualRubric(4,5,id)?.maxPoints).toBe(q.points)}});
});
describe("Grade 4 Test 5 source and originality review",()=>{
it("keeps sources within approved bands",()=>{const m=new Map<string,string>();for(const q of ec())if(q.passage&&q.passageTitle)m.set(q.passageTitle,q.passage);expect(wc(m.get("Signals Across the Cove")!)).toBeGreaterThanOrEqual(950);expect(wc(m.get("Signals Across the Cove")!)).toBeLessThanOrEqual(1100);expect(wc(m.get("Room for Roots Beneath a City Street")!)).toBeGreaterThanOrEqual(1000);expect(wc(m.get("Room for Roots Beneath a City Street")!)).toBeLessThanOrEqual(1150);for(const title of ["Testing a Model Building Against Shaking","How Sand Dunes Move"]){expect(wc(m.get(title)!)).toBeGreaterThanOrEqual(470);expect(wc(m.get(title)!)).toBeLessThanOrEqual(540)}expect(wc(ep()[0].passage!)).toBeGreaterThanOrEqual(1200);expect(wc(ep()[0].passage!)).toBeLessThanOrEqual(1400)});
it("has complete transcript/audio associations",()=>{for(const q of ec().filter(x=>x.claim===3)){expect(q.audio?.transcript).toBe(q.passage);const f=path.join(process.cwd(),"public",q.audio!.src.replace(/^\//,""));expect(existsSync(f)).toBe(true);expect(statSync(f).size).toBeGreaterThan(100_000)}});
it("does not exactly reuse prior prompts or passages",()=>{const prior:Question[]=[];for(let n=1;n<=18;n++)for(const s of ["math","ela"] as const)for(const t of ["cat","pt"] as const)prior.push(...getQuestions(3,s,t,n));for(let n=1;n<=4;n++)for(const s of ["math","ela"] as const)for(const t of ["cat","pt"] as const)prior.push(...getQuestions(4,s,t,n));const prompts=new Set(prior.map(q=>q.questionText));for(const q of all())expect(prompts.has(q.questionText),`item ${q.id}`).toBe(false);const passages=new Set(prior.map(q=>q.passage).filter(Boolean));for(const p of new Set(all().map(q=>q.passage).filter(Boolean)))expect(passages.has(p)).toBe(false)});
});
