import {expect,test,type Page} from "@playwright/test";
async function start(page:Page,label:string){await page.goto("/");await page.locator("#grade").selectOption("4");await expect(page.locator("#practiceTest option")).toHaveText(["Test 1 (Official Baseline)","Test 2 (Original · Easy)","Test 3 (Original · Easy)","Test 4 (Original · Medium)","Test 5 (Original · Hard)","Test 6 (Original · Easy)","Test 7 (Original · Easy)","Test 8 (Original · Medium)","Test 9 (Original · Hard)","Test 10 (Original · Hard)"]);await page.locator("#practiceTest").selectOption("5");await page.getByRole("button").filter({hasText:label}).click();await expect(page).toHaveURL(/test=5/);await expect(page.locator(".tds-q-badge")).toHaveText("1")}
async function review(page:Page,count:number){const dots=page.locator(".tds-progress-dots .tds-dot");await expect(dots).toHaveCount(count);for(let i=0;i<count;i++){await dots.nth(i).click({force:true});await expect(page.locator(".tds-q-badge")).toHaveText(String(i+1));await expect(page.locator(".tds-question-text")).not.toBeEmpty()}}
test.describe("Grade 4 Test 5 original Hard form",()=>{
test("renders all Math CAT items and high-risk Hard interactions",async({page})=>{await start(page,"Mathematics — Computer Adaptive Test");await review(page,31);const d=page.locator(".tds-progress-dots .tds-dot");await d.nth(24).click({force:true});await page.getByRole("button",{name:"Vertical line"}).click();await page.getByRole("button",{name:"Horizontal line"}).click();await expect(page.getByRole("button",{name:"Vertical line"})).toHaveAttribute("aria-pressed","true");await d.nth(28).click({force:true});await expect(page.locator(".line-plot-cell")).toHaveCount(12);await d.nth(29).click({force:true});await expect(page.locator(".multi-input-field input")).toHaveCount(2)});
test("renders and persists the two-trip water plan",async({page})=>{await start(page,"Mathematics — Performance Task");await review(page,5);await expect(page.locator(".tds-passage-body")).toContainText("Trip 1 runs 9:10–9:35");await expect(page.locator(".stimulus-table-table")).toBeVisible();await page.locator(".tds-progress-dots .tds-dot").nth(4).click({force:true});const f=page.locator(".multi-input-field input");await expect(f).toHaveCount(4);for(const[i,v]of["2","3","1","5"].entries())await f.nth(i).fill(v);await page.reload();await expect(page.locator(".multi-input-field input").nth(3)).toHaveValue("5")});
test("renders every ELA CAT item and both playable Hard narrations",async({page})=>{const failures:string[]=[];page.on("response",r=>{if(r.status()>=400&&/grade-4\/test-5/.test(r.url()))failures.push(r.url())});await start(page,"ELA — Computer Adaptive Test");await review(page,30);const d=page.locator(".tds-progress-dots .tds-dot");await d.nth(21).click({force:true});await expect(page.getByRole("heading",{name:"Testing a Model Building Against Shaking"})).toBeVisible();const audio=page.locator("audio");await audio.evaluate((n:HTMLAudioElement)=>n.load());await expect.poll(()=>audio.evaluate((n:HTMLAudioElement)=>n.readyState)).toBeGreaterThan(0);await d.nth(24).click({force:true});await expect(page.getByRole("heading",{name:"How Sand Dunes Move"})).toBeVisible();await expect(page.locator("audio source")).toHaveAttribute("src",/test-5-how-sand-dunes-move\.m4a/);expect(failures).toEqual([])});
test("completes streetlight Part 1, transition, full write, and submission",async({page})=>{await start(page,"ELA — Performance Task Segment");await expect(page.locator(".tds-progress-dots .tds-dot")).toHaveCount(2);await expect(page.locator(".tds-passage-body")).toContainText("What Shielded LED Streetlights Change");await page.locator(".short-answer-input").fill("Source 1 explains design choices; Source 3 reports a limited pilot.");await page.locator(".tds-progress-dots .tds-dot").nth(1).click({force:true});await expect(page.getByRole("note")).toContainText("row 1: exactly 1 (selected 0); row 2: exactly 2 (selected 0); row 3: exactly 1 (selected 0)");for(const i of [0,4,5,8])await page.locator(".grid-match-checkbox").nth(i).check();await page.getByTitle("Review Part 1").click();await expect(page.getByTestId("ela-pt-part1-review")).toBeVisible();await page.getByRole("button",{name:"CONTINUE TO PART 2"}).click();await expect(page.getByTestId("ela-pt-part2-transition")).toBeVisible();await page.getByRole("button",{name:"BEGIN PART 2"}).click();await expect(page.getByTitle("Back")).toBeDisabled();await page.locator(".rich-editor-body").fill("The town should expand in phases. The pilot shows energy savings, but the wetland and glare results require location-specific settings and monitoring.");await page.getByRole("button",{name:"SUBMIT TEST"}).click();await expect(page).toHaveURL(/\/results\?attempt=/)});
test("starts a clean Hard attempt after detecting a stale saved bank",async({page})=>{await page.addInitScript(()=>localStorage.setItem("caaspp-attempt:stale-test5",JSON.stringify({attemptId:"stale-test5",grade:4,subject:"ela",testType:"pt",practiceTest:5,bankVersion:"old-bank",bankHash:"old-hash",responseSchemaVersion:"1",answers:{},flagged:[],currentIndex:0,startedAt:"2026-07-01T00:00:00.000Z",updatedAt:"2026-07-01T00:00:00.000Z"})));await page.goto("/test?grade=4&subject=ela&type=pt&test=5&attempt=stale-test5");await expect(page.getByRole("heading",{name:"This saved attempt uses a different test version"})).toBeVisible();await page.getByRole("button",{name:"START NEW ATTEMPT"}).click();await expect(page).toHaveURL(/attempt=(?!stale-test5)/);await expect(page.locator(".tds-q-badge")).toHaveText("1")});
test("keeps the Hard water PT usable at 390 by 844",async({page})=>{await page.setViewportSize({width:390,height:844});await start(page,"Mathematics — Performance Task");await expect(page.locator(".tds-question-text")).toBeVisible();await expect(page.locator(".stimulus-table-table")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(1)});
});
