import { expect, test, type Page } from "@playwright/test";

async function startTest4(page:Page,label:string){
  await page.goto("/");
  await page.locator("#grade").selectOption("4");
  await expect(page.locator("#practiceTest option")).toHaveText(["Test 1 (Official Baseline)","Test 2 (Original · Easy)","Test 3 (Original · Easy)","Test 4 (Original · Medium)"]);
  await page.locator("#practiceTest").selectOption("4");
  await page.getByRole("button").filter({hasText:label}).click();
  await expect(page).toHaveURL(/grade=4/);await expect(page).toHaveURL(/test=4/);await expect(page.locator(".tds-q-badge")).toHaveText("1");
}
async function reviewEveryItem(page:Page,count:number){const dots=page.locator(".tds-progress-dots .tds-dot");await expect(dots).toHaveCount(count);for(let i=0;i<count;i++){await dots.nth(i).click({force:true});await expect(page.locator(".tds-q-badge")).toHaveText(String(i+1));await expect(page.locator(".tds-question-text")).not.toBeEmpty()}}

test.describe("Grade 4 Test 4 original Medium form",()=>{
  test("renders every Math CAT item and its high-risk interactions",async({page})=>{await startTest4(page,"Mathematics — Computer Adaptive Test");await reviewEveryItem(page,31);const dots=page.locator(".tds-progress-dots .tds-dot");await dots.nth(23).click({force:true});await expect(page.locator(".grid-match-checkbox")).toHaveCount(15);await dots.nth(24).click({force:true});await page.getByRole("button",{name:"Vertical line"}).click();await page.getByRole("button",{name:"Horizontal line"}).click();await expect(page.getByRole("button",{name:"Vertical line"})).toHaveAttribute("aria-pressed","true");await dots.nth(28).click({force:true});await expect(page.locator(".line-plot-cell")).toHaveCount(12);await dots.nth(30).click({force:true});await expect(page.locator(".multi-input-field input")).toHaveCount(2)});
  test("renders the complete pantry PT and persists a constraint response",async({page})=>{await startTest4(page,"Mathematics — Performance Task");await reviewEveryItem(page,5);await expect(page.locator(".tds-passage-body")).toContainText("Required reserve");await expect(page.locator(".stimulus-table-table")).toBeVisible();await page.locator(".tds-progress-dots .tds-dot").nth(4).click({force:true});const fields=page.locator(".multi-input-field input");for(const [i,value] of ["12","2","2"].entries())await fields.nth(i).fill(value);await page.reload();await expect(page.locator(".multi-input-field input").nth(0)).toHaveValue("12")});
  test("renders all ELA CAT items with playable transcript-linked audio",async({page})=>{const failures:string[]=[];page.on("response",r=>{if(r.status()>=400&&/grade-4\/test-4/.test(r.url()))failures.push(r.url())});await startTest4(page,"ELA — Computer Adaptive Test");await reviewEveryItem(page,30);const dots=page.locator(".tds-progress-dots .tds-dot");await dots.nth(21).click({force:true});await expect(page.getByRole("heading",{name:"From Clay to a Fired Bowl"})).toBeVisible();const audio=page.locator("audio");await expect(audio.locator("source")).toHaveAttribute("src",/test-4-from-clay-to-a-fired-bowl\.m4a/);await audio.evaluate((node:HTMLAudioElement)=>node.load());await expect.poll(()=>audio.evaluate((node:HTMLAudioElement)=>node.readyState)).toBeGreaterThan(0);await dots.nth(24).click({force:true});await expect(page.getByRole("heading",{name:"Reading a Weather Map"})).toBeVisible();await expect(page.locator("audio source")).toHaveAttribute("src",/test-4-reading-a-weather-map\.m4a/);expect(failures).toEqual([])});
  test("completes ELA PT review, 1/2/1 guidance, forward transition, and submission",async({page})=>{await startTest4(page,"ELA — Performance Task Segment");await expect(page.locator(".tds-progress-dots .tds-dot")).toHaveCount(2);await expect(page.locator(".tds-passage-body")).toContainText("Why Lunch Lines Slow Down");await page.locator(".short-answer-input").fill("Source 1 offers changes; Source 2 lists requirements.");await page.locator(".tds-progress-dots .tds-dot").nth(1).click({force:true});await expect(page.getByRole("note")).toContainText("row 1: exactly 1 (selected 0); row 2: exactly 2 (selected 0); row 3: exactly 1 (selected 0)");for(const i of [0,3,4,8])await page.locator(".grid-match-checkbox").nth(i).check();await page.getByTitle("Review Part 1").click();await expect(page.getByTestId("ela-pt-part1-review")).toBeVisible();await page.getByRole("button",{name:"CONTINUE TO PART 2"}).click();await expect(page.getByTestId("ela-pt-part2-transition")).toBeVisible();await page.getByRole("button",{name:"BEGIN PART 2"}).click();await expect(page.getByTitle("Back")).toBeDisabled();await page.locator(".rich-editor-body").fill("The school should keep the menu signs and test one additional change. The sources show shorter waits but also access and cost limits.");await page.getByRole("button",{name:"SUBMIT TEST"}).click();await expect(page).toHaveURL(/\/results\?attempt=/)});
  test("keeps the Medium PT usable at 390 by 844",async({page})=>{await page.setViewportSize({width:390,height:844});await startTest4(page,"Mathematics — Performance Task");await expect(page.locator(".tds-question-text")).toBeVisible();await expect(page.locator(".stimulus-table-table")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(1)});
});
