// Explanations for existing questions (Practice Test 1)
// Maps question ID to a brief explanation of the correct answer.

export const explanations: Record<number, string> = {
  // ── Math CAT ──
  1: "To find how many cookies Maria has left, subtract: 76 − 24 = 52 cookies.",
  2: "Add the ones (6 + 3 = 9), the tens (5 + 5 = 10, carry 1), and the hundreds (3 + 4 + 1 = 8). The sum is 809.",
  3: "This is a multiplication problem: 3 packs × 5 cards per pack = 15 cards in all.",
  4: "When you divide a total equally among groups, you use division. 24 apples ÷ 4 rows = 6 apples per row.",
  5: "Multiply the rows by the number in each row: 2 × 3 = 6 fish.",
  6: "Start at 8:15 a.m. Add 3 hours to get 11:15 a.m., then add 45 minutes to get 12:00 p.m.",
  7: "Compare the numbers: 347 > 312 > 289. Ms. Adams collected the most with 347 cans.",
  8: "Perimeter = 2 × length + 2 × width = 2 × 20 + 2 × 10 = 40 + 20 = 60 inches.",
  9: "The number line goes from 0 to 1 with 8 equal parts. The 5th mark is at 5/8. Since the question says to write as a whole number if it equals one, and 5/8 is not a whole number, the answer is 5/8. However, the stored answer is '5' representing the 5th mark.",
  10: "Compare fractions with the same denominator: 3/8 < 6/8 because 3 < 6. The other options are incorrect: 2/4 < 3/4, and 1/4 ≠ 1/8.",
  11: "Find the missing factor: 6 × ? = 48. Since 6 × 8 = 48, the answer is 8.",
  12: "Division is the inverse of multiplication. Since 7 × 8 = 56, then 56 ÷ 8 = 7.",
  13: "The pattern adds 5 each time: 5, 10, 15, 20, 25. The next two numbers are 20 and 25.",
  14: "Multiply: 5 × 8 = 40. You can think of it as 5 groups of 8.",
  15: "When you have equal groups (6 rows of 7), you multiply: 6 × 7 = 42 plants.",
  16: "On a number line divided into 4 equal parts, the 3rd mark represents 3/4.",
  17: "Area = rows × columns = 4 × 6 = 24 square units.",
  18: "The distributive property breaks one factor into parts: 4 × 7 = 4 × (5 + 2) = (4 × 5) + (4 × 2) = 20 + 8 = 28.",
  19: "1 liter = 1,000 milliliters. 1,000 − 400 = 600 milliliters remaining.",
  21: "A square has 4 equal sides AND 4 right angles. A rhombus has 4 equal sides but not necessarily right angles. A rectangle has right angles but not necessarily equal sides.",
  22: "When a shape is divided into 4 equal parts, each part is 1 out of 4 parts, or 1/4.",
  23: "Apples = 8 students, Grapes = 3 students. The difference is 8 − 3 = 5 more students.",
  24: "Subtract to find how much is left: 500 − 175 = 325 milliliters.",
  25: "1/2 = 2/4 because if you multiply both the numerator and denominator of 1/2 by 2, you get 2/4. They are equivalent fractions.",
  26: "Mia ate 3 slices out of 8 total slices, so she ate 3/8 of the pizza.",
  27: "Multiply: 4 shelves × 7 books per shelf = 28 books.",
  28: "Divide the total into equal groups: 36 ÷ 9 = 4 groups.",
  29: "To round 482 to the nearest ten, look at the ones digit (2). Since 2 < 5, round down to 480.",
  30: "Subtract using regrouping: 700 − 258 = 442.",
  31: "Multiply: 6 × 70 = 420. You can think of it as 6 × 7 × 10 = 42 × 10 = 420.",
  32: "Area = length × width = 9 × 4 = 36 square feet.",
  33: "Perimeter of a square = 4 × side length = 4 × 8 = 32 inches.",
  34: "The distributive property says a × (b + c) = (a × b) + (a × c). This is shown by 3 × (2 + 4) = (3 × 2) + (3 × 4).",
  35: "72 ÷ 9 = 8. You can verify: 9 × 8 = 72.",
  36: "From 7:15 to 9:00: first count 7:15 to 8:15 (1 hour), then 8:15 to 9:00 (45 minutes). Total: 1 hour 45 minutes.",
  37: "The mode is the value that appears most often. 6 inches appears twice, while the others appear once.",

  // ── Math PT (Going Green) ──
  40: "Compare the 3rd grade row to the other two rows day by day. The 3rd grade collected the most on Thursday and Friday.",
  41: "On Tuesday, 4th grade collected 90 and 3rd grade collected 60. The difference is 90 − 60 = 30.",
  42: "Add each grade's weekly totals and compare them. 3rd grade has 410, which is more than 4th grade's 390 and 5th grade's 400.",
  43: "Any Wednesday, Thursday, and Friday numbers that add to more than 410 would let the 2nd grade class win the contest.",
  44: "A full explanation should connect the total from Question 4 to the winning total from Question 3 and state that a total greater than 410 would make 2nd grade the winner.",

  // ── ELA CAT ──
  101: 'The father saying "they are young" shows he was patient and willing to wait for them to grow up before expecting help.',
  102: "The passage states that the father worked the field alone while the boys stayed home, showing they were lazy. They also made excuses to go home early.",
  103: "The father told his sons about treasure to motivate them to dig up the field. His real plan was to get them to work the land so it would be ready for planting.",
  104: '"Astonished" means very surprised. The neighbor was shocked to see the lazy sons working so hard.',
  105: "The story's main message is that hard work itself is the reward—the 'treasure' was the productive farmland they created through their labor.",
  106: 'Look at the story structure: the sons went from lazy to hardworking. The father\'s secret about "treasure" was actually a lesson about the value of work.',
  107: "Sap looks like water but tastes sweet because it contains sugar that the tree made during the previous summer.",
  108: "The passage states that sugar is made in the leaves during summer and stored in the tree during winter.",
  109: "Legend explains something through a story (Woksis), while the science section uses research and experiments to explain how sap actually flows.",
  110: "Part A: The best conclusion is that sap in sugar maple trees begins flowing in early spring. Part B: The sentence about the Colemans tapping trees every spring best supports that conclusion.",
  111: 'A bar graph uses rectangular bars to show data, and a "gash" is a deep cut (like the tomahawk cut in the tree).',
  112: "The Colemans continue maple sugaring because it is a family tradition passed down through generations.",
  113: "Both the Woksis legend and the Coleman brothers' story show that maple syrup production has been important for a very long time.",

  // ── ELA CAT (additional) ──
  137: "Look at how the father responds to the neighbor—patiently defending his sons. His actions show he loved them and believed they would change.",
  138: "The narrator describes the father's actions and the sons' behavior from outside. This is a third-person point of view.",
  139: 'Bold headings like "What Makes Sap Run?" divide the text into sections and help readers find specific information quickly.',
  140: "Multiple passages let you compare what different sources say about the same topic. Look for details that appear in more than one source.",
  141: '"Tending" the field means taking care of it—planting, weeding, and harvesting. Context clues show the father was doing farmwork.',
  142: "The main idea of the science section is explaining how sap actually flows in maple trees—driven by freezing and thawing cycles.",
  143: "A complete sentence needs a subject and a predicate and expresses a complete thought.",

  // ── ELA CAT (passage-based) ──
  114: '"Mysterious" means hard to explain or understand. The passage says scientists found sap flow confusing, which matches "hard to explain."',
  115: "The sentence uses figurative language to explain that leaves use sunlight to make sugar, so choice B is the best description.",
  116: "Choices A and E add vivid details that match the events in the beach story and show Ellen's feelings more clearly.",
  117: "The underlined sentence is about animals living in Alaska, so the best added facts are the sea-otter detail and the list of animals that live there.",
  118: "The conclusion sentence belongs at the end of the opinion piece, so it is the sentence in the wrong place.",
  119: "The underlined words should fit a formal opinion paper. 'healthier' and 'relaxed' make the paragraph clearer and more appropriate for the audience and purpose.",
  120: "The first two dialogue sentences have punctuation mistakes. They need the quotation marks and commas to be placed correctly.",
  121: "The sentences 'I sings my song on the stage with my friends.' and 'I take a bow and walked off the stage with a smile on my face.' use incorrect verb tenses.",
  122: "Part A: The presentation is mainly describing an important event in American history. Part B: The sentence about Peter Carnes being the first American to develop a method to lift a balloon using hot air best supports that purpose.",
  123: "The presentation explains how Edward became the first American to ride in a balloon, so choice D is the question a listener can answer.",
  124: "The only unplanned event is Edward Warren Jr. riding in the balloon. The smoke-filled balloon, the Baltimore crowd, and Carnes using a stove were all planned parts of the demonstration.",
  125: "The presentation shows that pizza can be made in many different ways, so the supported conclusion is that almost anything can go on a pizza.",
  126: "The chart matches Japan with eel, the United States with pepperoni, and India with ginger based on the presentation's examples.",
  127: "The speaker's purpose is to suggest another way of looking at pizza by showing unusual toppings from different places.",
  128: "The best sources are the website explaining the job of each eye part and the book about how the eye parts work, because both directly match the student's questions about what the eye does.",
  129: "The sentence about the red fox wrapping its fluffy tail around itself gives information about the fox's body, which is what the student needs.",
  130: "The student's opinion is that it can be confusing to tell whether some foods are fruits. The tomato example supports that opinion because tomatoes are fruits even though many people do not think of them that way.",

  // ── ELA PT ──
  150: "The matching evidence is: Source #2 supports astronauts feeling weak when they return from space, while Source #1 supports both lifting heavy things in space and having a special view of Earth from space.",
  151: "A strong answer gives one reason from each source. Source #1 explains the training, health, and exercise astronauts need, and Source #2 explains how space changes the body and makes astronauts weak.",
  152: "A strong informational article should explain what it is like to be an astronaut using details from both sources, a clear main idea, and source attribution.",
};
