// Explanations for existing questions (Practice Test 1)
// Maps question ID to a brief explanation of the correct answer.

export const explanations: Record<number, string> = {
  // ── Math CAT ──
  1: "To find how many cookies Maria has left, subtract: 76 − 24 = 52 cookies.",
  2: "Add the ones (6 + 3 = 9), the tens (5 + 5 = 10, carry 1), and the hundreds (3 + 4 + 1 = 8). The sum is 809.",
  3: "This is a multiplication problem: 3 packs × 5 cards per pack = 15 cards in all.",
  4: "When you divide a total equally among groups, you use division. 24 apples ÷ 4 rows = 6 apples per row.",
  5: "Multiply the rows by the number in each row: 2 × 3 = 6 fish.",
  6: "Start at 8:15 a.m. Add 3 hours to get 11:15 a.m., then add 45 minutes to get 12:00 p.m.",
  7: "Compare the numbers: 347 > 312 > 289. Ms. Adams collected the most with 347 cans.",
  8: "Perimeter = 2 × length + 2 × width = 2 × 20 + 2 × 10 = 40 + 20 = 60 inches.",
  9: "The number line goes from 0 to 1 with 8 equal parts. The 5th mark is at 5/8. Since the question says to write as a whole number if it equals one, and 5/8 is not a whole number, the answer is 5/8. However, the stored answer is '5' representing the 5th mark.",
  10: "Compare fractions with the same denominator: 3/8 < 6/8 because 3 < 6. The other options are incorrect: 2/4 < 3/4, and 1/4 ≠ 1/8.",
  11: "Find the missing factor: 6 × ? = 48. Since 6 × 8 = 48, the answer is 8.",
  12: "Division is the inverse of multiplication. Since 7 × 8 = 56, then 56 ÷ 8 = 7.",
  13: "The pattern adds 5 each time: 5, 10, 15, 20, 25. The next two numbers are 20 and 25.",
  14: "Multiply: 5 × 8 = 40. You can think of it as 5 groups of 8.",
  15: "When you have equal groups (6 rows of 7), you multiply: 6 × 7 = 42 plants.",
  16: "On a number line divided into 4 equal parts, the 3rd mark represents 3/4.",
  17: "Area = rows × columns = 4 × 6 = 24 square units.",
  18: "The distributive property breaks one factor into parts: 4 × 7 = 4 × (5 + 2) = (4 × 5) + (4 × 2) = 20 + 8 = 28.",
  19: "1 liter = 1,000 milliliters. 1,000 − 400 = 600 milliliters remaining.",
  21: "A square has 4 equal sides AND 4 right angles. A rhombus has 4 equal sides but not necessarily right angles. A rectangle has right angles but not necessarily equal sides.",
  22: "When a shape is divided into 4 equal parts, each part is 1 out of 4 parts, or 1/4.",
  23: "Apples = 8 students, Grapes = 3 students. The difference is 8 − 3 = 5 more students.",
  24: "Subtract to find how much is left: 500 − 175 = 325 milliliters.",
  25: "1/2 = 2/4 because if you multiply both the numerator and denominator of 1/2 by 2, you get 2/4. They are equivalent fractions.",
  26: "Mia ate 3 slices out of 8 total slices, so she ate 3/8 of the pizza.",
  27: "Multiply: 4 shelves × 7 books per shelf = 28 books.",
  28: "Divide the total into equal groups: 36 ÷ 9 = 4 groups.",
  29: "To round 482 to the nearest ten, look at the ones digit (2). Since 2 < 5, round down to 480.",
  30: "Subtract using regrouping: 700 − 258 = 442.",
  31: "Multiply: 6 × 70 = 420. You can think of it as 6 × 7 × 10 = 42 × 10 = 420.",
  32: "Area = length × width = 9 × 4 = 36 square feet.",
  33: "Perimeter of a square = 4 × side length = 4 × 8 = 32 inches.",
  34: "The distributive property says a × (b + c) = (a × b) + (a × c). This is shown by 3 × (2 + 4) = (3 × 2) + (3 × 4).",
  35: "72 ÷ 9 = 8. You can verify: 9 × 8 = 72.",
  36: "From 7:15 to 9:00: first count 7:15 to 8:15 (1 hour), then 8:15 to 9:00 (45 minutes). Total: 1 hour 45 minutes.",
  37: "The mode is the value that appears most often. 6 inches appears twice, while the others appear once.",

  // ── Math PT (School Fun Fair) ──
  40: "Divide the total students into equal teams: 72 ÷ 8 = 9 teams.",
  41: "Area = length × width = 6 × 4 = 24 square feet.",
  42: "First add the money raised: $156 + $98 = $254. Then subtract supplies: $254 − $75 = $179.",
  43: "First find total bags: 5 bags × 6 booths = 30 bags. Then find total cost: 30 × $3 = $90. The expression is (5 × 6) × 3.",
  44: "Perimeter = 2 × length + 2 × width = 2 × 5 + 2 × 3 = 10 + 6 = 16 feet of ribbon.",
  45: "Step 1: Cost of stuffed animals = 15 × $6 = $90. Step 2: Money left = $150 − $90 = $60. Step 3: Bouncy balls = $60 ÷ $2 = 30 bouncy balls.",
  46: "Check each option: 5 × 9 = 45 (not 48), 6 × 8 = 48 (correct!), 7 × 7 = 49 (not 48), 4 × 10 = 40 (not 48).",

  // ── ELA CAT ──
  101: 'The father saying "they are young" shows he was patient and willing to wait for them to grow up before expecting help.',
  102: "The passage states that the father worked the field alone while the boys stayed home, showing they were lazy. They also made excuses to go home early.",
  103: "The father told his sons about treasure to motivate them to dig up the field. His real plan was to get them to work the land so it would be ready for planting.",
  104: '"Astonished" means very surprised. The neighbor was shocked to see the lazy sons working so hard.',
  105: "The story's main message is that hard work itself is the reward—the 'treasure' was the productive farmland they created through their labor.",
  106: 'Look at the story structure: the sons went from lazy to hardworking. The father\'s secret about "treasure" was actually a lesson about the value of work.',
  107: "Sap looks like water but tastes sweet because it contains sugar that the tree made during the previous summer.",
  108: "The passage states that sugar is made in the leaves during summer and stored in the tree during winter.",
  109: "Legend explains something through a story (Woksis), while the science section uses research and experiments to explain how sap actually flows.",
  110: "The passage explains that scientists discovered sap flows downward, not upward as people once thought.",
  111: 'A bar graph uses rectangular bars to show data, and a "gash" is a deep cut (like the tomahawk cut in the tree).',
  112: "The Colemans continue maple sugaring because it is a family tradition passed down through generations.",
  113: "Both the Woksis legend and the Coleman brothers' story show that maple syrup production has been important for a very long time.",

  // ── ELA CAT (additional) ──
  137: "Look at how the father responds to the neighbor—patiently defending his sons. His actions show he loved them and believed they would change.",
  138: "The narrator describes the father's actions and the sons' behavior from outside. This is a third-person point of view.",
  139: 'Bold headings like "What Makes Sap Run?" divide the text into sections and help readers find specific information quickly.',
  140: "Multiple passages let you compare what different sources say about the same topic. Look for details that appear in more than one source.",
  141: '"Tending" the field means taking care of it—planting, weeding, and harvesting. Context clues show the father was doing farmwork.',
  142: "The main idea of the science section is explaining how sap actually flows in maple trees—driven by freezing and thawing cycles.",
  143: "A complete sentence needs a subject and a predicate and expresses a complete thought.",

  // ── ELA PT ──
  150: "The directions tell you to read the sources first, then answer questions and write an essay. Following directions carefully helps you do your best work.",
  151: "Both sources discuss how sap is collected and processed, but they present the information differently—one as legend, one as science.",
  152: "Good evidence comes directly from the text and supports your main point. Pick quotes or facts that clearly relate to what you're trying to prove.",
  153: "Both the legend and the science passage explain where maple syrup comes from, but one uses storytelling and the other uses scientific research.",
};
