import type { Question } from "./questions";

const BANK_VERSION = "2026-07-20.1";
type Item = Omit<Question, "grade" | "subject" | "practiceTest">;
const item = (question: Item): Question => ({ ...question, grade: 4, subject: "ela", practiceTest: 1 });
const exact = (itemNumber: number, sourcePage: number, sourceId: "g4-ela-cat" | "g4-ela-pt") => ({ itemNumber, sourcePage, sourceId, bankVersion: BANK_VERSION, fidelity: "exact" as const });

const rainyDay = `I heard the honking of the horn as my dad's truck pulled into the driveway. Immediately, I knew it was time to stop playing catch with my dog. My grandmother called, “Matthew! Your dad is home. Please come help him!”

I was disappointed. It was a cloudy Saturday, and I thought we would be able to skip the Farmer's Market. I had hoped to do what I wanted today, but no such luck.

“Matthew!” Grandmother called again.

“I'll be right there!” I yelled.

“Please get the big umbrellas from the basement,” Grandmother said. “It looks like it's going to rain.”

I still had to put on some shoes. I decided to wear my cowboy boots, but I couldn't find them. I looked in the front closet, upstairs, and by the back door. I could've worn my sneakers, but I really wanted to wear my boots. I knew that if I didn't hurry, everyone was going to be upset with me. Reluctantly, I put on my sneakers and went outside.

By then there were only a few crates of produce that needed to be loaded onto the truck.

“I could have used your help, son,” said Dad. “Kayla helped me load all of this produce into the truck.”

I knew he wasn't happy with me, and I felt bad that my sister Kayla had helped instead of me. I started to explain how I wanted to wear my boots, but couldn't find them. Then I realized how selfish I sounded.

Grandmother came outside, and I helped her carry a box of fresh baked goods. Once we were all in the truck, Dad drove toward town.

The Farmer's Market was located in a parking lot behind the town square.

Dad stopped the truck at the main entrance to check in. “Good morning, Bill,” Dad said to the attendant. “What's the weather prediction?”

“It's not looking good,” said Bill. He directed us to where we should park our truck.

Dad drove the truck toward our parking space, and then carefully backed in. We set up our table with fruits and vegetables on one side and baked goods on the other. Grandmother's homemade pies and cookies made my mouth water.

“We'd better put up the umbrellas in case it rains,” said Dad.

I gulped. I realized I had forgotten the umbrellas. Dad, Grandma, and Kayla looked at me expectantly.

“I'll be right back!” I yelled, and took off running before anyone had a chance to say anything.

I knew that my friend Jose and his family were supposed to be at the market, so I searched for them, keeping my fingers crossed that it didn't start to rain. I ran past tables of flowers, fruits, vegetables, and even homemade soaps and hand-knitted sweaters, but I could not find Jose.

Exhausted, I continued searching through the rows of tables. I reached the last row with growing concern. If it rained, our truck would get soaked, and so would my family.

Finally I saw Jose. I ran over and almost collapsed.

“Is everything all right, Matthew?” asked Jose's mom.

I gasped for air as I explained how I forgot our umbrellas. I asked if they had any extras we could borrow.

“Of course! Jose, please help Matthew,” said Jose's mom.

Then it happened: a drop of rain hit my face!

Jose and I quickly pulled out two large umbrellas from the family's truck. Jose helped me carry the big umbrellas back to our space. We had to go slowly, being careful not to bump into anyone. The market had opened for business, and it was already crowded.

We arrived just in time. As we opened the umbrellas, the few drops of rain began to turn into a steady drizzle. Dad smiled and nodded, seemingly pleased that I had solved the problem on my own. After we set up the umbrellas, Jose hurried back to his family. Luckily the rain didn't stop the crowds. But the rain sure taught me a lesson that day.`;

const dancesWithAnimals = `A honey bee returns to the hive. Sticky pollen clings to her body. Nectar fills her honey sac. She's found apple blossoms in a distant orchard. How does she tell other worker bees about this new food source? She dances!

Unlike humans, animals don't have words to help them communicate. They can't say “Hey! Look what I found,” or “Keep away! This is my spot,” or “Want to go steady?” Yet, animals communicate all the time. They send out signals—messages others receive and understand using their senses of smell, taste, touch, hearing, and sight.

Animals with good vision “talk” to each other with their bodies. They use patterns of movements to share information, to defend themselves or their territories, and to attract mates. Nature designs their steps, and they dance as if their lives depended on it. Often, they do.

## Language of Bees

Most communication takes place among members of the same species. In dark beehives, honeycombed walls become waxy dance floors. Like a rock star swarmed by adoring fans, a bee returning from the apple orchard begins her dance. Other workers follow her as she moves forward in a straight line. She vibrates her wings and wags her body side to side very quickly—13 to 15 times a second. Then she turns to one side, circles back, and begins the waggle run again. When she finishes, she circles around—this time in the opposite direction—and repeats her steps. The dance may go on for hours.

As she traces a figure 8 on the dance floor, the follower bees touch her with their antennae. They sense the odors of apple blossom nectar and pollen clinging to her body. These workers also detect the scent she used to mark the distant flowers. A flight plan is coded in her movements. The length of the waggle run tells workers how far the flowers are from the hive. Its angle tells them how to get there. Because bees steer by the sun, the dancer links her directions to its position in the sky.

However, the position of the sun in the sky keeps changing. If the waggle dance lasts for hours, how do bees leaving the hive long after the dance has begun find their targets? Amazingly, they do. The waggling bee adjusts her dance to account for the sun's movement.

## Keep Away!

“This is my spot!” Not all animals cooperate the way honey bees do. Most compete for food, territory, and mates. Fights take time and energy. Rivals risk injury and death, weakening the group as a whole. So some animals dance instead, using movements to make themselves look larger, stronger, and quicker than their competition. “Don't mess with me,” they say.

## Red Fish, Blue Fish

Most fish settle conflicts over territory without fighting. But Siamese fighting fish, also known as bettas, are little fish with a big mean streak. Brightly colored bettas in pet stores have been specially bred for their beautiful veil-like fins. In the wild, they live in rice paddies in Southeast Asia.

If threatened, male Siamese fighting fish switch back and forth between face-to-face and side-to-side positions. Facing each other, they flare out flaps of skin on their necks and extend their fins. This makes them seem twice their size. Side-to-side, they flicker their fins and beat the water with their tails. Tail beating gets faster and faster until one male backs down. The loser lowers his fins and puts his tail down. His bright red, blue, or purple body color fades to a dull hue. Defeated, he swims away.

Whether it is to communicate where to find something or to tell someone to “steer clear,” animal dances can tell us a lot!

“Dances with Animals” by Ellen R. Braaf, from *Ask* magazine. Copyright © 2009 by Carus Publishing. Reprinted by permission of the publisher.`;

const telephoneTranscript = `In the following presentation you will hear a speaker discuss the birth of the telephone.

On March 10, 1876, Alexander Graham Bell toiled in his lab in Boston, Massachusetts. The lab was actually a few small bedrooms in a boardinghouse. Hanging on one of the walls was a portrait of an owl. It was given to the inventor as a joke because he often worked late into the night. A pale, tall man with sideburns and a bushy mustache, Bell stared at his unusual contraption. He had been working on it for several years. Along the way, his invention had become an instrument of metal, rods, and wires. Bell had experimented with many other machines, but those trials had ended in failure. Sometimes he got discouraged, but he never gave up. Now history was about to be made.

To see if the device would work, Bell called into the mouthpiece: “Mr. Watson—Come here—I want to see you.” Seconds later, his assistant burst through the door. He had heard Bell's voice, even though he was in another room with a hallway in between. The two men switched places. Thomas Watson read from a book. A few of his words came through clearly. Then he said: “Mr. Bell, do you understand what I say?” Alexander Graham Bell heard every word. After years of research, the telephone was finally born.`;

const balloonTranscript = `In the following presentation, you will hear about balloon wranglers. Listen to the presentation and then answer the questions that follow.

Every Thanksgiving, a giant parade winds through the streets of New York City. The parade has singers, dancers, and bands. It has funny clowns and colorful floats. Most people, however, want to see the balloons. The balloons in this parade are huge! Many look like famous cartoon characters. Most are as tall as five- or six-story buildings and are just as long. Because the balloons are so large, many people must help guide them. These people are called balloon wranglers. Each balloon needs between fifty and seventy wranglers. The wranglers hold ropes, called “bones.” The bones attach to different parts of the balloon. Sometimes wranglers use the bones to make parts of the balloon move. For example, they might make the balloon wave its hand or wag its tail. Balloon wranglers bring the balloon to life for the crowd.

Being a balloon wrangler is not easy, though. Balloon wranglers receive special training before the parade. They must walk the whole length of the parade, which is about 2.5 miles. They also must walk in all kinds of weather, including rain, snow, and wind. Even so, many balloon wranglers return year after year because they have so much fun.`;

const rain = { passage: rainyDay, passageTitle: "A Rainy Day at the Farmer's Market" };
const dance = { passage: dancesWithAnimals, passageTitle: "Dances with Animals", passageAuthor: "Ellen R. Braaf" };
const phone = { passage: telephoneTranscript, passageTitle: "The Telephone Is Born", studentDirections: "Listen to the presentation. Then answer questions 22–24.\n\nExcerpt from *Alexander Graham Bell: Inventor of the Telephone* by Editors of Time for Kids with John Micklos, Jr. Copyright © 2006 by Time Inc. Reused with permission of Time Inc.", audio: { src: "/audio/presentations/grade-4/test-1-the-telephone-is-born.m4a", title: "The Telephone Is Born presentation", transcript: telephoneTranscript } };
const balloon = { passage: balloonTranscript, passageTitle: "Balloon Wranglers", studentDirections: "Listen to the presentation. Then answer questions 25–27.", audio: { src: "/audio/presentations/grade-4/test-1-balloon-wranglers.m4a", title: "Balloon Wranglers presentation", transcript: balloonTranscript } };

export const grade4ElaCat: Question[] = [
  item({...rain,id:41001,testType:"cat",claim:1,target:"1",dok:2,standard:"RL.1",type:"multi-select",questionText:"Matthew and his family go to the farmer's market regularly. Pick the two details from the passage that best support this inference.",options:[{label:"A",text:"Kayla helps load the crates onto the truck."},{label:"B",text:"Matthew knows his friend Jose will be there."},{label:"C",text:"Grandmother bakes pies to sell at the market."},{label:"D",text:"Dad knows the name of the parking attendant."},{label:"E",text:"Matthew thinks the rain will allow them to stay home."}],correctAnswer:["B","D"],rubric:"(1 point) The student selects the correct two options.",points:1,official:exact(1,6,"g4-ela-cat")}),
  item({...rain,id:41002,testType:"cat",claim:1,target:"7",dok:2,standard:"L.5b",type:"multi-select",questionText:"Read the sentences from the passage.\n\nI knew that my friend Jose and his family were supposed to be at the market, so I searched for them, keeping my fingers crossed that it didn't start to rain.\n\nWhy does the author use the phrase “keeping my fingers crossed”? Pick three choices.",options:[{label:"A",text:"to show Matthew feels unlucky"},{label:"B",text:"to show Matthew can move his hands easily"},{label:"C",text:"to show Matthew thinks the rain will not come after all"},{label:"D",text:"to show Matthew believes he can change the weather"},{label:"E",text:"to show Matthew is hopeful that the weather will not turn bad"},{label:"F",text:"to show Matthew wishes he could have some control over his problem"}],correctAnswer:["A","E","F"],rubric:"(1 point) The student selects the correct options.",points:1,official:exact(2,7,"g4-ela-cat")}),
  item({...rain,id:41003,testType:"cat",claim:1,target:"3",dok:2,standard:"RL.4",type:"multiple-choice",questionText:"The author uses the word *disappointed* in the passage. Click on the group of words in the sentence that best shows that idea.\n\nIt was a cloudy Saturday, and I thought we would be able to skip the Farmer's Market. I had hoped to do what I wanted today, but no such luck.",options:[{label:"A",text:"It was a cloudy Saturday"},{label:"B",text:"we would be able to skip the Farmer's Market"},{label:"C",text:"I had hoped to do what I wanted today"},{label:"D",text:"no such luck"}],correctAnswer:"D",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(3,8,"g4-ela-cat")}),
  item({...rain,id:41004,testType:"cat",claim:1,target:"3",dok:2,standard:"RL.4",type:"multiple-choice",questionText:"Read the sentences from the passage.\n\nFinally I saw Jose. I ran over and almost collapsed.\n\nWhat does the use of the word *collapsed* suggest?",options:[{label:"A",text:"Matthew is noisy."},{label:"B",text:"Matthew is very helpful."},{label:"C",text:"Matthew feels cheerful."},{label:"D",text:"Matthew feels very tired."}],correctAnswer:"D",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(4,9,"g4-ela-cat")}),
  item({...rain,id:41005,testType:"cat",claim:1,target:"4",dok:3,standard:"RL.3",type:"two-part",questionText:"The following question has two parts. First, answer part A. Then, answer part B.",partAPrompt:"Which of these inferences about Matthew is supported by the passage?",partAOptions:[{label:"A",text:"Matthew does not get enough exercise."},{label:"B",text:"Matthew wants to go to the farmer's market."},{label:"C",text:"Matthew does not care if his family gets wet."},{label:"D",text:"Matthew enjoys eating his grandmother's baked goods."}],partBPrompt:"Which sentence from the passage best supports your answer in part A?",partBOptions:[{label:"A",text:"I had hoped to do what I wanted today."},{label:"B",text:"Grandmother's homemade pies and cookies made my mouth water."},{label:"C",text:"I realized I had forgotten the umbrellas."},{label:"D",text:"I ran over and almost collapsed."}],correctAnswer:["D","B"],rubric:"(1 point) The student selects the correct option for Part A and the correct option for Part B.",points:1,official:exact(5,10,"g4-ela-cat")}),
  item({...rain,id:41006,testType:"cat",claim:1,target:"2",dok:2,standard:"RL.2",type:"multiple-choice",questionText:"What happens after Matthew and Jose open the umbrellas?",options:[{label:"A",text:"The rain begins to fall."},{label:"B",text:"The crowds begin to thin out."},{label:"C",text:"Matthew visits Jose and his mother at their stand."},{label:"D",text:"Matthew sets up the table with the fruits and vegetables."}],correctAnswer:"A",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(6,11,"g4-ela-cat")}),
  item({...rain,id:41007,testType:"cat",claim:1,target:"5",dok:3,standard:"RL.3",type:"multiple-choice",questionText:"How does the author develop the idea that Matthew takes responsibility for his actions?",options:[{label:"A",text:"Matthew stops explaining to his dad about the boots and begins helping."},{label:"B",text:"Matthew comes outside in time to load the last crates of produce onto the truck."},{label:"C",text:"Matthew is disappointed that he still must go to the market, even though it is raining."},{label:"D",text:"Matthew asks his friend to help him carry the umbrellas carefully through the crowd."}],correctAnswer:"A",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(7,12,"g4-ela-cat")}),
  item({...rain,id:41008,testType:"cat",claim:1,target:"6",dok:3,standard:"RL.5",type:"multi-select",questionText:"Read the sentence from the passage.\n\nI ran past tables of flowers, fruits, vegetables, and even homemade soaps and hand-knitted sweaters, but I could not find Jose.\n\nChoose two statements that best explain why the author chose to include this sentence.",options:[{label:"A",text:"to show that Matthew is good at running"},{label:"B",text:"to prove that Matthew's problem is very serious"},{label:"C",text:"to help the reader imagine the farmer's market"},{label:"D",text:"to show that it was difficult for Matthew to find Jose"},{label:"E",text:"to prove that there were many other sellers at the market besides Matthew's family"},{label:"F",text:"to help the reader understand the different kinds of items that were being sold at the market"}],correctAnswer:["C","D"],rubric:"(1 point) The student selects the correct two options.",points:1,official:exact(8,13,"g4-ela-cat")}),
  item({...rain,id:41009,testType:"cat",claim:1,target:"6",dok:3,standard:"RL.5",type:"multiple-choice",questionText:"How does the paragraph about Matthew looking for his cowboy boots add to the plot?",options:[{label:"A",text:"Matthew takes his time finding them, which adds to the calm feeling of the story."},{label:"B",text:"Matthew spends a lot of time looking for them, which adds a feeling of mystery to the story."},{label:"C",text:"Matthew gets too busy looking for them, causing him to forget the umbrellas, which sets up the problem in the story."},{label:"D",text:"Matthew is unable to find them, causing him to wear his sneakers, which builds on the character description in the story."}],correctAnswer:"C",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(9,14,"g4-ela-cat")}),
  item({...dance,id:41010,testType:"cat",claim:1,target:"8",dok:2,standard:"RI.1",type:"multi-select",questionText:"Click on the two sentences that best support the idea that dancing may be a better way for animals to communicate than fighting.",options:[{label:"A",text:"Not all animals cooperate the way honey bees do."},{label:"B",text:"Most compete for food, territory, and mates."},{label:"C",text:"Fights take time and energy."},{label:"D",text:"Rivals risk injury and death, weakening the group as a whole."},{label:"E",text:"So some animals dance instead, using movements to make themselves look larger, stronger, and quicker than their competition."},{label:"F",text:"“Don't mess with me,” they say."}],correctAnswer:["C","D"],rubric:"(1 point) The student selects the correct two options.",points:1,official:exact(10,17,"g4-ela-cat")}),
  item({...dance,id:41011,testType:"cat",claim:1,target:"9",dok:2,standard:"RI.2",type:"multiple-choice",questionText:"Read the summary of the “Red Fish, Blue Fish” section of the passage and the directions that follow.\n\nThe male betta fish would rather dance than fight. First, they turn toward each other and stretch out their skin and fins to look bigger. Then, they move side to side and quickly beat the water with their tails until one backs down. The loser lowers his fins and tail and swims away.\n\nAn important detail is missing from the summary. Click on the sentence from the passage that includes the missing detail.",options:[{label:"A",text:"If threatened, male Siamese fighting fish switch back and forth between face-to-face and side-to-side positions."},{label:"B",text:"Facing each other, they flare out flaps of skin on their necks and extend their fins."},{label:"C",text:"Side-to-side, they flicker their fins and beat the water with their tails."},{label:"D",text:"His bright red, blue, or purple body color fades to a dull hue."}],correctAnswer:"D",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(11,18,"g4-ela-cat")}),
  item({...dance,id:41012,testType:"cat",claim:1,target:"10",dok:2,standard:"RI.4",type:"multiple-choice",questionText:"Read the sentence from the passage.\n\nBecause bees steer by the sun, the dancer links her directions to its position in the sky.\n\nPick the word that best defines *position* as it is used in the sentence.",options:[{label:"A",text:"job"},{label:"B",text:"opinion"},{label:"C",text:"order"},{label:"D",text:"place"}],correctAnswer:"D",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(12,19,"g4-ela-cat")}),
  item({...dance,id:41013,testType:"cat",claim:1,target:"13",dok:2,standard:"L.5b",type:"multi-select",questionText:"What is the most likely reason the author uses dialogue in the passage? Pick three choices.",options:[{label:"A",text:"to inform readers that animals communicate through movement"},{label:"B",text:"to inform readers that animals can talk to each other the same way humans can"},{label:"C",text:"to inform readers that different dance movements have different meanings to animals"},{label:"D",text:"to inform readers that animals have a spoken language that some humans can understand"},{label:"E",text:"to inform readers that an animal’s specific movements gives other animals important information"},{label:"F",text:"to inform readers that animals have secret codes that only the smartest animals in the species can understand"}],correctAnswer:["A","C","E"],rubric:"(1 point) The student selects the correct options.",points:1,official:exact(13,20,"g4-ela-cat")}),
  item({...dance,id:41014,testType:"cat",claim:1,target:"9",dok:2,standard:"RI.2",type:"multi-select",questionText:"Pick the two sentences that should be included in a summary of the passage.",options:[{label:"A",text:"A bee traces a figure 8 while other bees touch her antennae."},{label:"B",text:"Bees are able to communicate with dance when the sun is in the sky."},{label:"C",text:"It takes several hours for a bee to communicate with other worker bees."},{label:"D",text:"Bees use patterns of movement to tell other worker bees how to find food."},{label:"E",text:"Bees dance to show other worker bees the direction of food but not how far away it is."},{label:"F",text:"Bees communicate by vibrating their wings, moving side to side, and turning in circles."}],correctAnswer:["D","F"],rubric:"(1 point) The student selects the correct two options.",points:1,official:exact(14,21,"g4-ela-cat")}),
  item({...dance,id:41015,testType:"cat",claim:1,target:"12",dok:3,standard:"RI.1",type:"multiple-choice",questionText:"What does the information in the section “Keep Away!” show about the author’s point of view?",options:[{label:"A",text:"It shows that the author thinks that bees are the best animal."},{label:"B",text:"It shows that the author thinks that all animal dances are frightening."},{label:"C",text:"It shows that the author thinks that animal dances weaken animal groups."},{label:"D",text:"It shows that the author thinks that animal dances are better than animal fights."}],correctAnswer:"D",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(15,22,"g4-ela-cat")}),
  item({id:41016,testType:"cat",claim:2,target:"1bE",dok:2,standard:"W.3b",type:"multiple-choice",questionText:"Parker is writing a story for her class about a dog that helps people who are blind. Parker wants to revise her story to add better detail about the main character. Read the draft paragraphs of her story and complete the task that follows.\n\nAbout a year ago, a young Black Labrador puppy was adopted by a loving and helpful family. The family named the pup Bailey, and they taught her how to assist people who are blind.\n\nEach day, Bailey learned a new skill for being a good guide dog. She learned how to listen very carefully to commands, and she also learned how to warn people when there was danger. Bailey seemed to beam with pride and happiness every time she was praised for her good work. She knew she was destined for great things in life. Bailey wanted nothing more than to help people. Bailey wagged her tail in delight when she heard, “Good girl! What a helpful dog you are!”\n\nFinally, the day arrived for Bailey to go to her new home. A lovely lady who had lost her eyesight only a month earlier adopted the helpful dog. Bailey quickly became her faithful friend and assistant. Bailey always made sure the woman was safe both at home and in the neighborhood. In return, the woman made sure Bailey felt loved and treasured.\n\nChoose the best sentence to add detail to show or explain who the main character is.",options:[{label:"A",text:"The family lived in a beautiful, small home in the woods."},{label:"B",text:"Bailey was more helpful, loving, and intelligent than any dog the family had known."},{label:"C",text:"The lovely lady had three daughters and one son who all lived far away in different states."},{label:"D",text:"Parker met Bailey in fourth grade when a lovely lady brought her to the school for a lesson."}],correctAnswer:"B",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(16,23,"g4-ela-cat")}),
  item({id:41017,testType:"cat",claim:2,target:"3bO",dok:2,standard:"W.2c",type:"multi-select",questionText:"A student is writing a report for his teacher about raising frogs. Read the draft of the report and complete the task that follows.\n\nWhen Robert brought the frog eggs to school, they looked like tiny jelly balls. They were attached like a bunch of grapes to a rock under the water of the aquarium tank. For several days, nothing seemed to be happening. We worried that something had gone wrong. Frog eggs will not hatch if the water is not clean enough or if the temperature is too cool. Then, one morning Kate noticed that the eggs had hatched. Tadpoles were swimming around the tank like a swarm of tiny bees. It was disappointing that we were not able to see the hatching itself. Later on, raising frogs has been very interesting so far.\n\nChoose the best two phrases to connect “It was disappointing that we were not able to see the hatching itself” and “raising frogs has been very interesting so far.”",options:[{label:"A",text:"Even so"},{label:"B",text:"Later on"},{label:"C",text:"Let alone"},{label:"D",text:"Despite this"},{label:"E",text:"For example"},{label:"F",text:"In other words"}],correctAnswer:["A","D"],rubric:"(1 point) The student selects the correct two options.",points:1,official:exact(17,24,"g4-ela-cat")}),
  item({id:41018,testType:"cat",claim:2,target:"6b",dok:2,standard:"W.1b",type:"multiple-choice",questionText:"A student is writing an opinion article for the teacher about too much homework. The student wants to revise the draft to improve the development of ideas. Read the draft of the article and complete the task that follows.\n\nStudents these days have too much homework. At my school, students get more than an hour and a half of homework every night, and that doesn’t include our daily reading.\n\nFirst of all, our homes should not feel like another form of school. We listen and work all day at school. Home should be for spending time with our families and friends. However, the amount of homework the average fourth-grade student receives is taking away important family time and time to play. Kids also need to get enough sleep to do well in school. Sometimes we have so much homework in so many different subjects that we are up way past our bedtimes trying to get it done.\n\nHowever, other people believe homework gets students ready for high school and makes them more responsible. They also say homework makes parents get more involved in their child’s learning. I disagree. I believe it’s more important to spend fun times with your family instead of arguing over homework.\n\nAfter you’ve worked on schoolwork all day long, it’s not fun to go home and do homework. I hope teachers, principals, students, and parents can find an answer and end the problem of too much homework!\n\nChoose the sentence that best supports the reason that homework takes away important family time and time to play.",options:[{label:"A",text:"My family loves to spend time playing board games in the evenings."},{label:"B",text:"Many of my friends would use the free time at home to play on their computers."},{label:"C",text:"My teachers say that all students should have one to two hours of homework each night."},{label:"D",text:"Studies have shown that students who are active with friends and family are healthier and happier."}],correctAnswer:"D",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(18,25,"g4-ela-cat")}),
  item({id:41019,testType:"cat",claim:2,target:"8",dok:1,standard:"W.3d, L.3a",type:"multi-select",questionText:"A student is writing a story for language arts about learning to ski. Read the draft of the story and complete the task that follows.\n\nThe student wants to make sure that he has used the right words to make his meaning clear. Click on two of the underlined words that he should change.\n\nThis weekend, I went skiing with my friend Jack and his family. I had never been there before, so I was really excited. The mountains looked so beautiful with their peaks covered in snow.\n\nFirst, Jack's father gave me a ski lesson and I practiced for a while. Then, we rode to the ski slope on the thing that takes people to the mountain top. It was fun to slide on the skis, but I forgot how to stop and crashed into Jack. We both fell down, but we weren't hurt. Jack's dad was laughing. He helped us up and taught me how to stop again.",options:[{label:"A",text:"there"},{label:"B",text:"peaks"},{label:"C",text:"thing"},{label:"D",text:"crashed"}],correctAnswer:["A","C"],rubric:"(1 point) The student selects the correct two options.",points:1,official:exact(19,26,"g4-ela-cat")}),
  item({id:41020,testType:"cat",claim:2,target:"9",dok:1,standard:"L.2b, L.2c",type:"multiple-choice",questionText:"Read the story and the question that follows.\n\nToday, our class went to The Fishery, a local fish store, because we are learning about fish: where they live and how they are different from people. Inside the store was very dark, except for the bright lights on top of each tank.\n\nThe girl, working in the store told me that the lights are neon, and they are used to show off the bright, colors of each fish.\n\nThe different fish were beautiful under the lights. They were bright blue, purple, yellow, and green.\n\nI wanted to take all of the fish home.\n\nWhat is the best way to correct the punctuation error in the underlined sentence?",options:[{label:"A",text:"The girl working in the store told me the lights are neon, and they are used to show off the bright colors of each fish."},{label:"B",text:"The girl working in the store told me, the lights, are neon and they are used to show off the bright color of each fish."},{label:"C",text:"The girl, working in the store told me, “The lights are neon” and they are used to show off the bright colors of each fish."},{label:"D",text:"The girl working in the store told me, the lights are “neon,” and they are used to show off the “bright colors” of each fish."}],correctAnswer:"A",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(20,27,"g4-ela-cat")}),
  item({id:41021,testType:"cat",claim:2,target:"9",dok:1,standard:"L.2a",type:"multiple-choice",questionText:"Read the paragraph and complete the task that follows.\n\nWe went to visit my uncle in Massachusetts. He lives just outside of Boston, so we went sightseeing in the City. We went to see where Paul Revere lived. He was a famous hero in the American Revolution. After that we walked through Boston Commons, a large park. Then we went to a baseball game.\n\nChoose the underlined word that is incorrectly capitalized.",options:[{label:"A",text:"uncle"},{label:"B",text:"City"},{label:"C",text:"Revolution"},{label:"D",text:"park"}],correctAnswer:"B",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(21,28,"g4-ela-cat")}),
  item({...phone,id:41022,testType:"cat",claim:3,target:"4",dok:3,standard:"SL.3",type:"two-part",questionText:"The following question has two parts. First, answer part A. Then, answer part B.",partAPrompt:"What is the main idea of the presentation?",partAOptions:[{label:"A",text:"Alexander Graham Bell lived long ago."},{label:"B",text:"Alexander Graham Bell was an inventor."},{label:"C",text:"Alexander Graham Bell worked in a small lab."},{label:"D",text:"Alexander Graham Bell invented the telephone."}],partBPrompt:"Which sentence from the presentation best supports the main idea?",partBOptions:[{label:"A",text:"“On March 10, 1876, Alexander Graham toiled in his lab in Boston, Massachusetts.”"},{label:"B",text:"“The lab was actually a few small bedrooms in a boardinghouse.”"},{label:"C",text:"“Bell had experimented with many other machines, but those trials had ended in failure.”"},{label:"D",text:"“After years of research, the telephone was finally born.”"}],correctAnswer:["D","D"],rubric:"(1 point) The student selects the correct option for Part A and the correct option in Part B.",points:1,official:exact(22,30,"g4-ela-cat")}),
  item({...phone,id:41023,testType:"cat",claim:3,target:"4",dok:1,standard:"SL.3",type:"multiple-choice",questionText:"Which detail from the presentation best supports the conclusion that Alexander Graham Bell was a dedicated scientist?",options:[{label:"A",text:"Bell worked late at night."},{label:"B",text:"Bell worked in a boardinghouse lab."},{label:"C",text:"Bell had many failures with other machines."},{label:"D",text:"Bell got discouraged, but kept trying anyway."}],correctAnswer:"D",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(23,31,"g4-ela-cat")}),
  item({...phone,id:41024,testType:"cat",claim:3,target:"4",dok:2,standard:"SL.3",type:"multi-select",questionText:"Choose two details from the presentation that support the idea that the telephone took a long time to invent.",options:[{label:"A",text:"Bell worked hard in his small lab."},{label:"B",text:"Bell had an assistant that helped him."},{label:"C",text:"Bell worked with metal, rods, and wires."},{label:"D",text:"Bell worked on his contraption for several years."},{label:"E",text:"Bell experimented with many different machines."}],correctAnswer:["D","E"],rubric:"(1 point) The student selects the two correct options.",points:1,official:exact(24,32,"g4-ela-cat")}),
  item({...balloon,id:41025,testType:"cat",claim:3,target:"4",dok:3,standard:"SL.3",type:"two-part",questionText:"The following question has two parts. First, answer part A. Then, answer part B.",partAPrompt:"Which conclusion is supported by the presentation?",partAOptions:[{label:"A",text:"The New York parade is the largest of its kind."},{label:"B",text:"The huge balloons in a parade are difficult to control."},{label:"C",text:"Balloon wranglers have a harder job than others in the parade."},{label:"D",text:"The main reason people like the balloons is because of who they look like."}],partBPrompt:"Which sentence from the presentation best supports your answer in part A?",partBOptions:[{label:"A",text:"Many balloons look like well-known cartoons."},{label:"B",text:"They have to walk the whole 2.5 miles of the parade."},{label:"C",text:"The giant parade moves through the streets of New York City."},{label:"D",text:"There are between fifty and seventy wranglers for every balloon."}],correctAnswer:["B","D"],rubric:"(1 point) The student selects the correct option for Part A and the correct option for Part B.",points:1,official:exact(25,34,"g4-ela-cat")}),
  item({...balloon,id:41026,testType:"cat",claim:3,target:"4",dok:2,standard:"SL.3",type:"multiple-choice",questionText:"“One job of the balloon wranglers is to amuse the people in the crowd.”\n\nWhich detail from the presentation best supports this idea?",options:[{label:"A",text:"Balloon wranglers receive special training."},{label:"B",text:"Balloon wranglers have fun handling the balloons."},{label:"C",text:"Balloon wranglers make parts of the balloons move."},{label:"D",text:"Balloon wranglers will work no matter how bad the weather is."}],correctAnswer:"C",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(26,35,"g4-ela-cat")}),
  item({...balloon,id:41027,testType:"cat",claim:3,target:"4",dok:1,standard:"SL.2",type:"grid-match",questionText:"The presentation gives information about the balloons used in the Thanksgiving parade in New York City as well as information about other parts of the parade. Complete the chart by clicking in the boxes next to the information column that match whether the information describes balloons or other parts of the parade.",gridRows:["Famous Characters","Funny Clowns","Long and Tall","Colorful Floats"],gridColumns:["Balloons","Parade"],correctAnswer:["0:0","1:1","2:0","3:1"],rubric:"(1 point) The student selects the correct four options.",points:1,official:exact(27,36,"g4-ela-cat")}),
  item({id:41028,testType:"cat",claim:4,target:"3",dok:2,standard:"W.8",type:"multi-select",questionText:"A student is writing a research report about the sky. Read the sentences from her report and the directions that follow.\n\nIt is a clear day in the summer. The sun shines brightly on your face. You lie down on the soft carpet of green grass and look up at the bright blue sky. Suddenly you ask yourself, “If air has no color, then what makes the sky blue?”\n\nChoose two of the sources that would most likely give the student more information about the ideas she has written.",options:[{label:"A",text:"“Sky High,” a story about a boy who grows wings and flies high into the clouds to explore"},{label:"B",text:"Art from Above, a book which gives directions on how to paint a picture of the Earth and sky"},{label:"C",text:"Pictures in the Sky, a book which tells all about the different kinds of clouds and how they form"},{label:"D",text:"Science Far Above, a book that gives information about how light rays change the way the sky looks"},{label:"E",text:"Summer Days, Summer Ways, a book of fun things to do in the summer when you have nothing to do"},{label:"F",text:"www.how_I_wonder.com, a website that explains kids' questions about how things happen in nature"}],correctAnswer:["D","F"],rubric:"(1 point) The student selects the two correct options.",points:1,official:exact(28,37,"g4-ela-cat")}),
  item({id:41029,testType:"cat",claim:4,target:"2",dok:2,standard:"W.8",type:"multiple-choice",questionText:"A student is writing a report about chipmunks. Read the sentences from a source and the directions that follow.\n\nThere are 25 kinds of chipmunks, 24 of which live in North America. Chipmunks can also be found in Northern Asia. Female chipmunks have at least one litter per year with four or five babies who stay in the nest for up to six weeks. They look like squirrels, their bushy-tailed cousins, but they are smaller. Chipmunks live in dens with two rooms. One room is a nest lined with leaves, and the second room is where they store their food of nuts, seeds, and grains. Chipmunks hibernate in cold weather, which means they spend most of the winter sleeping in their dens.\n\nThe parts of the student's report are shown below. In which part of the report would the facts from the source best fit?",options:[{label:"A",text:"Part A: The Family of a Chipmunk"},{label:"B",text:"Part B: The Food a Chipmunk Eats"},{label:"C",text:"Part C: The Appearance of a Chipmunk"},{label:"D",text:"Part D: The Places Where a Chipmunk Lives"}],correctAnswer:"D",rubric:"(1 point) The student selects the correct option.",points:1,official:exact(29,38,"g4-ela-cat")}),
  item({id:41030,testType:"cat",claim:4,target:"4",dok:2,standard:"W.9",type:"multi-select",questionText:"A student is writing a research report about panda bears. He wrote an opinion in the report. Read the sentences from the report and the directions that follow.\n\nA panda bear has black hair around its eyes, ears, nose and all across its tummy. The rest of its fur is white. A panda has a short, stubby tail. It has five claws and an extra finger, kind of like a thumb, that starts at its wrist bone. It uses this extra finger to grip and eat bamboo. Panda bears love to eat lots and lots of bamboo.\n\nThe student found another source about pandas. Choose two of the sentences from the source that support the student's opinion.",options:[{label:"A",text:"A panda bear can climb trees."},{label:"B",text:"Panda bears live in the forest."},{label:"C",text:"Panda bears enjoy being alone."},{label:"D",text:"The panda mainly eats bamboo shoots."},{label:"E",text:"The panda has a thumb and five fingers."},{label:"F",text:"Panda bears can eat at least 20 pounds of bamboo a day."}],correctAnswer:["D","F"],rubric:"(1 point) The student selects the two correct options.",points:1,official:exact(30,39,"g4-ela-cat")}),
];

const animalsPtDirections = `# Animals and Their Surroundings Informational Performance Task

## Task

Your school's science fair is taking place soon. Your class has decided to focus on doing science projects about animals. You become interested in learning more about where animals live. You have found three sources about this topic in the school library.

After you have looked at these sources, you will answer some questions about them. Briefly scan the sources and the three questions that follow. Then, go back and read the sources carefully so you will have the information you will need to answer the questions and complete your research. You may click on the Global Notes button to take notes on the information you find in the sources as you read. You may also use scratch paper to take notes.

In Part 2, you will write an informational article using information you have read.

## Directions for Beginning

You will now look at several sources. You can look at any of the sources as often as you like.

## Research Questions

After reviewing the research sources, use the rest of the time in Part 1 to answer three questions about them. Your answers to these questions will be scored. Also, your answers will help you think about the information you have read, which should help you write your informational article.

You may click on the Global Notes button or refer back to your scratch paper to review your notes when you think it would be helpful. Answer the questions in the spaces below the items.

Both the Global Notes on the computer and your written notes on scratch paper will be available to you in Part 1 and Part 2 of the performance task.`;

const animalsSource1 = `## Source #1

You have found an article that describes how animals survive in different environments, the places where plants and animals live.

# It's a Cold (Hot, Dry, Dark) Cruel World!

by Dawn Baertlein

Living creatures survive in all types of environments. Each environment creates different challenges for animals that live there. Some living creatures survive at the bottom of the sea where it is dark as night and very cold. Other plants and animals live in dry, hot environments. People can use tools like flashlights or fans to help them survive. Animals and plants, however, must rely on nature to help them survive.

Near the South Pole, in Antarctica, it is very cold. It is usually about minus 57 degrees Fahrenheit. Water freezes at 32 degrees Fahrenheit, so Antarctica is much colder than ice. Scientists live at the South Pole, but they live in buildings with thick walls and heating. What do animals do?

Some animals have bodies that help them live in the cold. The icefish lives in water so cold that even in summer, chunks of ice continue to float in the water. How do icefish keep from freezing? The only way icefish can survive in this extreme environment is because they have a special substance in their blood that keeps ice crystals from forming inside their bodies.

Penguins have thick layers of fat or blubber to help them stay warm, but sometimes even that is not enough! Often, penguins must rely on each other for survival. They cuddle up together as close as they can to share their body heat.

Another area that can be hard to live in is the dry, hot desert. People who live in the desert often wear special clothes to protect them from the heat. When they build homes they have air conditioners to keep them cool and to find water they dig wells that provide water from deep in the ground. How do animals survive in the hot, dry conditions?

Many desert animals come out only at night, when it's cool. Snakes, lizards, mice, and squirrels live in burrows. During the day, they stay under the ground and out of the sun.

In the hot Sonoran Desert of Arizona, an owl lives in a nest that sits on a tall cactus. The cactus stems store water. Rain doesn't fall often in the Sonoran Desert, but when it does, it falls quickly and heavily. Then the water quickly flows away. The cactus has roots that spread out only inches below the surface of the soil. The roots are like a big sponge, soaking up rainwater fast. Now the cactus can store water for months and the owl has a nice home high up in the cactus.

![An owl nests on a cactus in the desert](/images/grade-4/test-1/ela/source-1-owl-cactus.png)

The ocean has very different challenges from those of the desert. The deepest parts of the ocean are very dark and cold because the sun's rays are unable to shine through all of the layers of water. Some of the very deepest parts of the ocean have thermal vents on the ocean floor that are like little volcanoes under the sea. The water coming out of the vents is very hot. Crabs survive at the bottom of the sea by scurrying around the vents looking for food.

Arctic chill, desert sun, and cold, pitch-dark ocean—these are difficult conditions that would be hard for people to survive. But nature gives plants and animals the ability to live almost anywhere.

## Sources Used

Carey, B. (2006, June 19). Fish produces natural antifreeze to stay alive. Retrieved from http://www.nbcnews.com/id/13426864/ns/technology_and_sciencescience/t/fish-produces-natural-antifreeze-stay-alive/

Hill, K. (2007, September 15). What animal never drinks water in its entire life? Retrieved from http://www.bigsiteofamazingfacts.com/what-animal-never-drinks-water-in-its-entire-life

SeaWorld Parks and Entertainment (n.d.). Polar bears: behavior. Retrieved from http://www.seaworld.org/animal-info/info-books/polar-bear/behavior.htm

The Mariana Trench (n.d.). The mariana trench-biology. Retrieved from http://www.marianatrench.com/mariana_trench-biology_001.htm

Photo of owl on cactus (Image 1598R-10034017), copyright by SuperStock. Used by permission.`;

const animalsSource2 = `## Source #2

You have found an article from *Appleseeds* magazine that describes how some animals build their homes.

# Animal Architects

by Donna Henes

## Everybody Needs a Home

Homes protect us from weather and keep us safe and comfortable. Animals are no exception.

Humans live in a wide variety of structures. Around the world, people have designed and built their homes to suit their particular needs and ways of life. Animals do the same.

In addition to making living places, people and animals both build other structures: bridges, dams, traps, and storage areas. These structures help people and animals survive.

People and animals both use different materials and methods for their constructions. They build with wood, weave with fibers and vines, dig into the earth, and mold out of mud.

From sky-high nests to elaborate [or fancy] tunnels, the amazing works of animal architects [or building designers] rival those of the greatest human engineers. Let's take a look at some.

Beavers build lodges along the banks of lakes and ponds. Using branches they chewed apart themselves, beavers begin by building a cone-shaped frame. Then they fill in the gaps with mud and leaves. The entrance to the lodge is always at the bottom, underwater, so beavers can come and go without being seen by predators.

In addition to their lodges, beavers build dams. Water builds up behind the dams, creating flooded areas that are ideal places for beavers to find food. The flooded areas also provide pools for other wildlife.

Termites build 20-foot-high mounds out of dirt and their own saliva. These giant structures are like small apartment buildings. Besides living areas, these towers have food storage areas, nurseries for “baby” termites, a special chamber for the king and queen, and even gardens. (A chamber is like a room.)

![An inside view of a termite mound](/images/grade-4/test-1/ela/source-2-termite-mound.png)

Wombats dig huge underground burrows that can be 100 feet long. Wombat tunnels are elaborate, with many entrances, side tunnels, and resting chambers. Inside the burrow, sleeping nests are built on raised “platforms” to keep them dry in case of flooding. Often, several burrows are connected, creating structures so huge they can actually be seen from space!

![A wombat coming out of its burrow](/images/grade-4/test-1/ela/source-2-wombat.png)

Bald eagles build massive nests, 4 to 5 feet across and 3 to 6 feet deep, high in tall trees. They use their beaks and amazingly strong talons [or claws] to break branches and twigs for nest material. Like beavers, eagles begin by building a stick frame. Then they weave in smaller branches and twigs for added strength and protection. Finally, eagles line their nests with grasses and other soft material to make them comfy.

Take a look around you. [You may] find other examples of amazing animal architecture.

## Sources Used

Henes, D. (2009). Animal architects. *Appleseeds, 11*(7), 16–18.

Photograph of termite mound (Image 4268R-11707), copyright by SuperStock. Used by permission.

Photograph of wombat in burrow (Image 1889R-38764), copyright by SuperStock. Used by permission.`;

const animalsSource3 = `## Source #3

You have found an article that discusses plants and animals that live in the same place. The article describes how these plants and animals depend on each other to stay alive.

# Don't Step in that Ecosystem!

by Courtney Duke

The next time you go out, take a careful look around. Maybe you see a small pond. Plants might be growing in the pond, birds might take baths in it and, if you're lucky, the pond might even be a home to tadpoles.

Any place where plants and animals live and interact [work together] with nonliving things (like air, water, and soil) is called an ecosystem. The plants and animals in an ecosystem need each other to survive. It is important that there is a balance among all things in an ecosystem. A small change in any part of an ecosystem can have a big effect. For example, if the food that an animal eats can no longer be found, then that animal will either die or have to leave that ecosystem. When that animal is no longer a part of the ecosystem, then the rest of the living and nonliving parts of the ecosystem are affected because all parts of the ecosystem depend on each other.

All parts of an ecosystem are connected to each other. Think about an oak tree in the forest. It is a home to the bugs and birds that live in its bark and branches, and to the squirrels who make their nests in its trunk. The oak tree also provides food to other animals in the ecosystem. When its acorns are ripe, they fall to the forest floor. These rich nuts are good food for the mice and deer that eat them to fatten up for the winter. Mice save the acorns so that they have food in the winter months, and in the spring, hawks swoop down looking for a mouse meal. In a way, the oak tree helps the hawk find its food. This is an example of how the plants and animals in an ecosystem work together in order to survive.

Now think of the ocean. Imagine diving into the deep blue water. Near the surface, you see a rocky ridge of coral called a coral reef. The reef is home to many plants and animals. For example, sea plants move back and forth in the current, and fish come to feed or to hide from other living things that can harm them. Coral reefs, in fact, are homes to about one-quarter of all the fish in the sea. Reefs also attract birds, whales, turtles, and seals. The number and many different types of animals that depend upon coral reefs make them one of the most important ecosystems in the world.

There are many different kinds of ecosystems, and they can be very small like a pond or very big like a coral reef ecosystem. Ecosystems are everywhere.

*ecosystem: an area where plants, animals, and other nonliving things live and depend on each other for survival*

## Sources Used

Geography for kids. (n.d.). Ecosystems. Retrieved from: http://www.kidsgeo.com/geography-for-kids/0164-ecosystems.php

Salpietra, M. (2009, February 24). Population ecology. Retrieved from: http://www.pbs.org/wgbh/nova/nature/population-ecology.html

The Franklin Institute (n.d.). Ecosystems, biomes, and habitats. Retrieved from: http://www.fi.edu/tfi/units/life/habitat/habitat.html

Pala, C. (2008, September). Our imperiled oceans: victory at sea. Retrieved from: http://www.smithsonianmag.com/science-nature/our-imperiled-oceans-victory-at-sea-7468851/?no-ist`;

const animalsSources = `${animalsSource1}\n\n---\n\n${animalsSource2}\n\n---\n\n${animalsSource3}`;

const informationalRubric = `Organization/Purpose — 4 points: The response has a clear and effective organizational structure, creating a sense of unity and completeness. The organization is sustained between and within paragraphs. The response is consistently and purposefully focused: the controlling/main idea of a topic is clearly communicated, and the focus is strongly maintained for the purpose and audience; consistent use of a variety of transitional strategies clarifies the relationships between and among ideas; the introduction and conclusion are effective; and ideas progress logically from beginning to end, with strong connections between and among ideas and some syntactic variety.

Organization/Purpose — 3 points: The response has an evident organizational structure and a sense of completeness. Though there may be minor flaws, they do not interfere with overall coherence. The organization is adequately sustained between and within paragraphs. The response is generally focused: the controlling/main idea is clear, and the focus is mostly maintained for the purpose and audience; transitions are adequate and show some variety; the introduction and conclusion are adequate; and the progression and connections between and among ideas are adequate.

Organization/Purpose — 2 points: The response has an inconsistent organizational structure. Some flaws are evident, and some ideas may be loosely connected. The organization is somewhat sustained between and within paragraphs. The response may have a minor drift in focus: the controlling/main idea may be somewhat unclear, or the focus may be insufficiently sustained for the purpose and/or audience; transitions may be inconsistent or show little variety; the introduction or conclusion, if present, may be weak; and progression may be uneven or formulaic, with inconsistent or unclear connections between and among ideas.

Organization/Purpose — 1 point: The response has little or no discernible organizational structure. The response may be related to the topic but may provide little or no focus: the controlling/main idea may be confusing or ambiguous, the response may be too brief, or focus may drift from the purpose and/or audience; few or no transitions are evident; the introduction and/or conclusion may be missing; and frequent extraneous ideas, random ordering, or an unclear progression may be evident.

Evidence/Elaboration — 4 points: The response provides thorough elaboration of the support/evidence for the controlling/main idea that includes the effective use of source material. The response clearly and effectively develops ideas using precise language: comprehensive evidence (facts and details) from the source material is integrated, relevant, and specific; citations or attribution to source material are clear; a variety of elaborative techniques is used effectively; vocabulary is clearly appropriate for the audience and purpose; and an effective, appropriate style enhances content.

Evidence/Elaboration — 3 points: The response provides adequate elaboration of the support/evidence for the controlling/main idea that includes the use of source material. The response adequately develops ideas, employing a mix of precise and more general language: evidence is integrated and relevant, though it may be general; citations or attribution and some elaborative techniques are adequate; vocabulary is generally appropriate for the audience and purpose; and a generally appropriate style is evident.

Evidence/Elaboration — 2 points: The response provides uneven, cursory elaboration of the support/evidence for the controlling/main idea that includes uneven or limited use of source material. The response develops ideas unevenly using simplistic language: evidence may be weakly integrated, imprecise, repetitive, vague, and/or copied; citations or attribution are weak; elaborative techniques are weak or uneven and development may consist primarily of source summary; vocabulary use is uneven or somewhat ineffective for the audience and purpose; and the attempt to create an appropriate style is inconsistent or weak.

Evidence/Elaboration — 1 point: The response provides minimal elaboration of the support/evidence for the controlling/main idea that includes little or no use of source material. The response is vague, lacks clarity, or is confusing: evidence is minimal, irrelevant, absent, incorrectly used, or predominantly copied; citations or attribution are insufficient; elaborative techniques are minimal, if present; vocabulary is limited or ineffective for the audience and purpose; and there is little or no evidence of appropriate style.

Elaborative techniques may include the use of personal experiences that support the controlling/main idea.

Conventions — 2 points: The response demonstrates an adequate command of conventions, with adequate use of correct sentence formation, punctuation, capitalization, grammar usage, and spelling.

Conventions — 1 point: The response demonstrates a partial command of conventions, with limited use of correct sentence formation, punctuation, capitalization, grammar usage, and spelling.

Conventions — 0 points: The response demonstrates little or no command of conventions, with infrequent use of correct sentence formation, punctuation, capitalization, grammar usage, and spelling.

Conventions are scored holistically using Variety (the range of errors in sentence formation, punctuation, capitalization, grammar usage, and spelling), Severity (basic errors are more heavily weighted than higher-level errors), and Density (the proportion of errors to the amount of writing done well, including the ratio of errors to response length).

NS for every trait: Insufficient (includes copied text), in a language other than English, off-topic, or off-purpose.`;

export const grade4ElaPt: Question[] = [
  item({id:41101,testType:"pt",claim:4,target:"2",dok:3,standard:"W.9",type:"short-answer",passage:animalsSources,passageTitle:"Animals and Their Surroundings",studentDirections:animalsPtDirections,questionText:"Source #1 discusses what some animals do to survive in their environment. Explain how the information in Source #2 adds to the reader's understanding of what some animals do to survive in their environment. Give two details from Source #2 to support your explanation.",correctAnswer:"See the two-point evidence-based rubric and key elements from Source #2.",scoringRule:{kind:"manual-rubric"},rubric:"(2 points) Response is an evidence-based explanation that provides two pieces of evidence from the specified source that support this idea and that explain how each detail supports the idea.\n\n(1 point) Response is an evidence-based explanation that provides two pieces of evidence from the specified source that support this idea but doesn't explain how each detail supports the idea. OR Response provides only one piece of evidence that supports the idea and explains how that detail supports it.\n\n(0 points) Response is incorrect, irrelevant, insufficient, or blank.",points:2,official:exact(1,14,"g4-ela-pt")}),
  item({id:41102,testType:"pt",claim:4,target:"4",dok:3,standard:"W.8",type:"grid-match",passage:animalsSources,passageTitle:"Animals and Their Surroundings",studentDirections:animalsPtDirections,questionText:"Complete the chart by matching each idea with the source that supports it.",gridRows:["Some animals have developed special body features that help them survive in the place where they live.","Animals and plants living together is important for their survival.","Animals create environments where they are protected from the weather and kept safe and comfortable."],gridColumns:["Source #1","Source #2","Source #3"],correctAnswer:["0:0","1:2","2:1"],rubric:"(1 point) 3 cells completed correctly.\n\n(0 points) Fewer than 3 cells completed correctly or blank.",points:1,official:exact(2,16,"g4-ela-pt")}),
  item({id:41103,testType:"pt",claim:2,target:"4",dok:4,standard:"W.2b",type:"extended-writing",passage:animalsSources,passageTitle:"Animals and Their Surroundings",studentDirections:animalsPtDirections,questionText:"Your assignment is to use the research sources to write an informational article for your school's science fair. Your article will be read by students, teachers, and parents.\n\nUse information from more than one source to develop your main idea about animals and their surroundings. Write several paragraphs. Support your main idea with details from the sources. Use your own words except when quoting directly from a source. Give the source title or source number for the details and facts you use.",correctAnswer:"Responses will vary. See rubric.",scoringRule:{kind:"manual-rubric"},rubric:informationalRubric,points:10,official:exact(3,18,"g4-ela-pt")}),
];
