import type { Question } from "./questions";

const BANK_VERSION = "2026-07-20.1";

type Item = Omit<Question, "grade" | "subject" | "practiceTest">;

function cat(item: Item): Question {
  return { ...item, grade: 4, subject: "math", practiceTest: 1 };
}

function pt(item: Item): Question {
  return { ...item, grade: 4, subject: "math", practiceTest: 1 };
}

const exact = (itemNumber: number, sourcePage: number, sourceId: "g4-math-cat" | "g4-math-pt") => ({
  itemNumber,
  sourcePage,
  sourceId,
  bankVersion: BANK_VERSION,
  fidelity: "exact" as const,
});

export const grade4MathCat: Question[] = [
  cat({ id: 40001, testType: "cat", claim: 1, domain: "OA", target: "A", dok: 1, standard: "4.OA.A, 4.NBT.B.4", type: "text-input", questionText: "A baker has 159 cups of brown sugar and 264 cups of white sugar. How many total cups of sugar does the baker have?", correctAnswer: "423", rubric: "(1 point) The student enters the correct number of cups.", points: 1, official: exact(1, 3, "g4-math-cat") }),
  cat({ id: 40002, testType: "cat", claim: 3, domain: "NF", target: "E", dok: 2, standard: "4.NF.B.3", type: "multiple-choice", questionText: "Jarrod is adding 3 2/6 and 7 5/6.\n\nHe uses these steps to find the sum.\n\nStep 1: 3 + 7 = 10\nStep 2: 2/6 + 5/6 = 7/12\nStep 3: 10 + 7/12 = 10 7/12\n\nJarrod made a mistake. Select the statement that corrects his mistake.", options: [{label:"A",text:"In Step 1, he should have multiplied 3 and 7 by 6 before adding."},{label:"B",text:"In Step 2, he should not have added the denominators."},{label:"C",text:"In Step 2, he should have multiplied 2 and 5 instead of adding them."},{label:"D",text:"In Step 3, he should not have added the whole number and fraction."}], correctAnswer: "B", rubric: "(1 point) The student selects the correct statement.", points: 1, official: exact(2, 4, "g4-math-cat") }),
  cat({ id: 40003, testType: "cat", claim: 1, domain: "OA", target: "A", dok: 1, standard: "4.OA.A.2", type: "text-input", questionText: "Danielle’s full-grown dog weighs 10 times as much as her puppy. The puppy weighs 9 pounds.\n\nEnter the number of pounds the full-grown dog weighs.", correctAnswer: "90", rubric: "(1 point) The student enters the correct number of pounds.", points: 1, official: exact(3, 5, "g4-math-cat") }),
  cat({ id: 40004, testType: "cat", claim: 1, domain: "NF", target: "G", dok: 2, standard: "4.NF.B.3", type: "multiple-choice", questionText: "Choose the fraction model that represents the following equation: 3/7 + 2/7 + 1/7 = 6/7.", options: [{label:"A",text:"Model A"},{label:"B",text:"Model B"},{label:"C",text:"Model C"},{label:"D",text:"Model D"}], stimulusImages: [{src:"/images/grade-4/test-1/math/item-04-models.png",alt:"Four official number-line fraction models labeled A through D.",sha256:"42152acd4a3c6d3657720e60f01d1c15e0175dd614c0a74b944cc07c251b062e"}], correctAnswer: "C", rubric: "(1 point) The student identifies the fraction model that represents the equation.", points: 1, official: exact(4, 6, "g4-math-cat") }),
  cat({ id: 40005, testType: "cat", claim: 1, domain: "OA", target: "B", dok: 1, standard: "4.OA.B.4", type: "multiple-choice", questionText: "Select the list of numbers that are all multiples of 9.", options: [{label:"A",text:"9, 27, 35, 63"},{label:"B",text:"9, 48, 81, 90"},{label:"C",text:"18, 36, 45, 64"},{label:"D",text:"18, 54, 72, 99"}], correctAnswer: "D", rubric: "(1 point) The student selects the correct list of multiples.", points: 1, official: exact(5, 7, "g4-math-cat") }),
  cat({ id: 40006, testType: "cat", claim: 1, domain: "NF", target: "F", dok: 2, standard: "4.NF.A.2", type: "grid-match", questionText: "Select True if the comparison is true. Select False if the comparison is not true.", gridRows: ["89/100 > 9/10", "7/12 < 2/3", "3/5 > 4/10"], gridColumns: ["True", "False"], correctAnswer: ["0:1","1:0","2:0"], rubric: "(1 point) The student correctly identifies the true comparisons.", points: 1, official: exact(6, 8, "g4-math-cat") }),
  cat({ id: 40007, testType: "cat", claim: 4, domain: "OA", target: "E", dok: 3, standard: "4.OA.A.1", type: "multiple-choice", questionText: "Susan has 3 times as many books as Mary. Mary has 18 books. Which equation can be solved to figure out how many books Susan has?", options: [{label:"A",text:"□ − 3 = 18"},{label:"B",text:"3 + 18 = □"},{label:"C",text:"18 ÷ □ = 3"},{label:"D",text:"3 × 18 = □"}], correctAnswer: "D", rubric: "(1 point) The student selects the correct equation.", points: 1, official: exact(7, 9, "g4-math-cat") }),
  cat({ id: 40008, testType: "cat", claim: 3, domain: "NF", target: "F", dok: 2, standard: "4.NF.A.2", type: "multi-select", questionText: "Anna is using four models to compare fractions. She shades each rectangle to represent a fraction of a whole. Select all the statements that can be supported using Anna’s fraction models.", stimulusImages:[{src:"/images/grade-4/test-1/math/item-08-fraction-models.png",alt:"Official four shaded fraction-bar models.",sha256:"f9234b5e0267fc1749900788668f7897163c217f57e9a69212bb0c202804a286"}], options: [{label:"A",text:"2/6 = 4/12"},{label:"B",text:"2/12 = 4/12"},{label:"C",text:"2/6 > 1/6"},{label:"D",text:"2/12 > 2/6"}], correctAnswer: ["A","C"], rubric: "(1 point) The student correctly identifies the supporting statements.", points: 1, official: exact(8, 10, "g4-math-cat") }),
  cat({ id: 40009, testType: "cat", claim: 1, domain: "OA", target: "A", dok: 1, standard: "4.OA.A.2", type: "text-input", questionText: "Isabella has 2 times as many DVDs as Emma. Emma has 6 DVDs.\n\nEnter the number of DVDs Isabella has.", correctAnswer: "12", acceptedAnswers:["12","12.0"], rubric: "(1 point) The student enters the correct number of DVDs.", points: 1, official: exact(9, 12, "g4-math-cat") }),
  cat({ id: 40010, testType: "cat", claim: 3, domain: "NBT", target: "A", dok: 2, standard: "4.NBT.C.5", type: "multi-input", questionText: "Brittany solves 52 × 14 using an area model. Use the same reasoning as Brittany to solve 39 × 17. Drag numbers to complete the equation. You may use the area model to help you.", stimulusImages:[{src:"/images/grade-4/test-1/math/item-10-area-model.png",alt:"Official example and blank area models for 52 × 14 and 39 × 17.",sha256:"aa5b9e1c1d287eae1fce6c30d3ae21fdaa91f90f53774cce810ded5fa13f5bd1"}], responseFields:[{label:"Addend 1"},{label:"Addend 2"},{label:"Addend 3"},{label:"Addend 4"},{label:"Sum"}], correctAnswer:["300","210","90","63","663"], scoringRule:{kind:"constraints",constraint:{kind:"all",constraints:[{kind:"field-unordered-set",indexes:[0,1,2,3],values:["300","210","90","63"]},{kind:"field-equals",index:4,value:"663"}]}}, rubric:"(1 point) Student enters four correct addends (order doesn’t matter) and the correct sum. One possible response is shown.", points:1, official:exact(10,13,"g4-math-cat") }),
  cat({ id: 40011, testType: "cat", claim: 1, domain: "NF", target: "G", dok: 2, standard: "4.NF.B.4", type: "grid-match", questionText: "Decide whether each expression is equal to 4 × 2/3. Click in the table to respond.", gridRows:["2 × 4/3","3 × 2/4","8 × 1/3"], gridColumns:["Equal to 4 × 2/3","Not Equal to 4 × 2/3"], correctAnswer:["0:0","1:1","2:0"], rubric:"(1 point) The student correctly identifies the equal expressions.", points:1, official:exact(11,14,"g4-math-cat") }),
  cat({ id: 40012, testType: "cat", claim: 3, domain: "NBT", target: "E", dok: 2, standard: "4.NBT.B.5", type: "multiple-choice", questionText:"Conner solves 8 × 16. He says, “I can find the product if I multiply 8 × 15 and then add 8.”\n\nSelect the statement that best explains if Connor’s strategy is correct.", options:[{label:"A",text:"Connor is correct, because he can change the 16 to use an easier number to multiply, like 15."},{label:"B",text:"Connor is incorrect, because 8 × 16 is the same as 4 groups of 8, plus 4 groups of 8."},{label:"C",text:"Connor is correct, because 8 × 16 is the same as 15 groups of 8, plus 1 group of 8."},{label:"D",text:"Connor is incorrect, because he should add 16 instead of 8."}], correctAnswer:"C", rubric:"(1 point) The student selects the best statement.", points:1, official:exact(12,15,"g4-math-cat") }),
  cat({ id: 40013, testType: "cat", claim: 1, domain: "NBT", target: "D", dok: 2, standard: "4.NBT.A.2", type:"grid-match", questionText:"Select True or False for each comparison.", gridRows:["4581 > 4000 + 800 + 50 + 1","40 hundreds + 50 tens + 81 ones = 4581","4 thousands + 8 hundreds + 1 ten + 5 ones < 4581"], gridColumns:["True","False"], correctAnswer:["0:1","1:0","2:1"], rubric:"(1 point) The student correctly identifies the true and false comparisons.", points:1, official:exact(13,16,"g4-math-cat") }),
  cat({ id: 40014, testType: "cat", claim: 1, domain: "MD", target: "K", dok: 2, standard: "4.MD.C.7", type:"text-input", questionText:"Use the diagram to solve the problem.\n\n• The measure of ∠DCE = 70°\n• The measure of ∠ECF = 45°\n• The measure of ∠FCG = 45°\n\nEnter the measure, in degrees, of ∠DCF.", stimulusImages:[{src:"/images/grade-4/test-1/math/item-14-angle.png",alt:"Official angle diagram with rays CD, CE, CF, and CG.",sha256:"93cf3f278bd3e96b303a1bc33aa0c40ada3ecfae4c2d56a1cc6e977f67eca4e2"}], correctAnswer:"115", rubric:"(1 point) The student enters the correct measure of ∠DCF in degrees.", points:1, official:exact(14,17,"g4-math-cat") }),
  cat({ id: 40015, testType: "cat", claim:1, domain:"NF", target:"F", dok:1, standard:"4.NF.A.1", type:"grid-match", questionText:"Select True if the equation is true. Select False if the equation is not true.", gridRows:["1/4 = 3/12","1/2 = 50/100","9/10 = 99/100"], gridColumns:["True","False"], correctAnswer:["0:0","1:0","2:1"], rubric:"(1 point) The student correctly identifies the true and false equations.", points:1, official:exact(15,18,"g4-math-cat") }),
  cat({ id:40016,testType:"cat",claim:3,domain:"NBT",target:"C",dok:3,standard:"4.NBT.B",type:"multi-select",questionText:"Carlos uses this information to plan the number of packages of juice to buy:\n\n• He needs 480 juice boxes.\n• Some packages have 6 juice boxes.\n• Some packages have 8 juice boxes.\n\nCarlos claims, “To buy exactly 480 juice boxes, I need to buy 30 packages of apple juice and 40 packages of orange juice.”\n\nSelect two statements that must be true for Carlos’s claim to be correct.",options:[{label:"A",text:"There are 6 juice boxes in a package of apple juice."},{label:"B",text:"There are 8 juice boxes in a package of apple juice."},{label:"C",text:"There are 6 juice boxes in a package of orange juice."},{label:"D",text:"There are 8 juice boxes in a package of orange juice."}],correctAnswer:["B","C"],rubric:"(1 point) The student selects the two statements that must be true.",points:1,official:exact(16,19,"g4-math-cat")}),
  cat({id:40017,testType:"cat",claim:2,domain:"NF",target:"A",dok:2,standard:"4.NF.B.4",type:"text-input",questionText:"Steven made snack mix.\n\n• He used 1/4 cup of raisins and 2/4 cup of nuts to make one serving.\n\nSteven wants to make 5 servings of snack mix. How many cups of snack mix are in 5 servings?",correctAnswer:"3.75",acceptedAnswers:["3.75","3 3/4","15/4","3¾"],rubric:"(1 point) The student enters the correct number of cups of snack mix.",points:1,official:exact(17,20,"g4-math-cat")}),
  cat({id:40018,testType:"cat",claim:1,domain:"G",target:"L",dok:2,standard:"4.G.A.3",type:"symmetry-line",questionText:"Use the Add Arrow tool to draw all of the lines of symmetry for the shape. If there are no lines of symmetry, click None.",symmetry:{shapePath:"M100 55 L260 55 L300 175 L60 175 Z",shapeAlt:"Isosceles trapezoid",choices:[{id:"vertical",label:"Vertical line",path:"M180 20 L180 205"},{id:"horizontal",label:"Horizontal line",path:"M35 115 L325 115"},{id:"diagonal",label:"Diagonal line",path:"M75 195 L285 25"},{id:"none",label:"None"}],maxSelections:1,noneChoiceId:"none"},correctAnswer:"vertical",rubric:"(1 point) The student draws one line of symmetry.",points:1,official:exact(18,21,"g4-math-cat")}),
  cat({id:40019,testType:"cat",claim:2,domain:"NBT",target:"A",dok:3,standard:"4.NBT.C.5",type:"multi-input",questionText:"Casey multiplies two numbers.\n\n• The first number is 178.\n• The second number is a whole number that is greater than 0 but less than 10.\n• The product of the two numbers has a 2 in the ones place.\n\n**Part A:** What is a possible number that Casey multiplies 178 by? Enter your answer in the first response box.\n\n**Part B:** What is the product of Casey’s two numbers? Enter your answer in the second response box.",responseFields:[{label:"Part A"},{label:"Part B"}],correctAnswer:["4","712"],scoringRule:{kind:"partial-credit",tiers:[{points:2,constraint:{kind:"all",constraints:[{kind:"field-one-of",index:0,values:["4","9"]},{kind:"field-product",factor:178,multiplierIndex:0,productIndex:1}]}},{points:1,constraint:{kind:"all",constraints:[{kind:"field-number",index:0,min:1,max:9,integer:true},{kind:"field-number",index:1,min:100,max:9999,integer:true,endsWith:2}]}}]},rubric:"(2 points) The student enters a correct value in Part A and Part B.\n\n(1 point) The student enters a correct value in Part A AND any 3- or 4-digit number with a 2 in the ones place in Part B.\n\n(1 point) The student enters a correct value in Part B AND any 3- or 4-digit number with a 2 in the ones place in Part A.",points:2,official:exact(19,22,"g4-math-cat")}),
  cat({id:40020,testType:"cat",claim:3,domain:"OA",target:"B",dok:3,standard:"4.OA.B.4",type:"multi-input",questionText:"Jose made this statement:\n\n“All whole numbers except 1 have an even number of factors because factors always come in pairs.”\n\nSelect a whole number between 1 and 10 that proves Jose’s statement is incorrect.\n\n**Part A:** Enter a number and the number of factors it has.\n\n**Part B:** Enter the factors for your number.",responseFields:[{label:"Part A number"},{label:"Part A number of factors"},{label:"Part B factors (separated by spaces)"}],correctAnswer:["4","3","1 2 4"],scoringRule:{kind:"constraints",constraint:{kind:"field-factor-list",numberIndex:0,countIndex:1,factorsIndex:2}},rubric:"(1 point) The student enters one of the two correct combinations shown in the exemplar.",points:1,official:exact(20,23,"g4-math-cat")}),
  cat({id:40021,testType:"cat",claim:4,domain:"NF",target:"C,F",dok:2,standard:"4.NF.B.3d",type:"text-input",questionText:"Mrs. Taylor’s class is measuring the wingspans of butterflies, in inches. They record their results in this table.\n\nThe wingspan of the Tiger Butterfly is 3/4 inch longer than that of the Monarch Butterfly.\n\nWhat is the difference, in inches, between the longest and shortest wingspans? Enter your answer in the response box.",dataTable:{columns:["Wingspan (in)"],rows:[{label:"Monarch",values:["3 2/4"]},{label:"Zebra",values:["2 3/4"]},{label:"Checkered White",values:["1 2/4"]},{label:"Tiger",values:["?"]}]},correctAnswer:"2.75",acceptedAnswers:["2.75","2 3/4","2¾"],rubric:"(1 point) The student enters the correct difference.",points:1,official:exact(21,24,"g4-math-cat")}),
  cat({id:40022,testType:"cat",claim:4,domain:"MD",target:"D",dok:2,standard:"4.MD.B.4",type:"text-input",questionText:"The line plot shows the distances, in miles, Rex walked on seven days. Each × represents one day.\n\nEnter the total distance, in miles, Rex walked for all seven days.",stimulusImages:[{src:"/images/grade-4/test-1/math/item-22-line-plot.png",alt:"Official line plot of the distances Rex walked on seven days.",sha256:"131657b64c90692ac4ba836d3a1ca47e76f04b54e4dd1b9b1c68193dae13f7b6"}],correctAnswer:"17.5",acceptedAnswers:["17.5","17 1/2","17½","35/2"],rubric:"(1 point) The student correctly identifies the number of miles Rex walked.",points:1,official:exact(22,25,"g4-math-cat")}),
  cat({id:40023,testType:"cat",claim:1,domain:"NF",target:"G",dok:2,standard:"4.NF.B.3",type:"text-input",questionText:"At the beginning of June, a bean plant was 3 4/5 inches tall.\n\nBy the beginning of July, the plant was 6 2/5 inches tall. How many inches did the plant grow during June? Enter your answer in the response box.",correctAnswer:"2.6",acceptedAnswers:["2.6","2 3/5","2⅗","13/5"],rubric:"(1 point) The student enters the amount the plant has grown.",points:1,official:exact(23,26,"g4-math-cat")}),
  cat({id:40024,testType:"cat",claim:1,domain:"MD",target:"I",dok:1,standard:"4.MD.A.1",type:"text-input",questionText:"Enter the unknown number that makes the equation true.\n\n15 meters = □ centimeters",correctAnswer:"1500",rubric:"(1 point) The student enters the correct number of centimeters.",points:1,official:exact(24,27,"g4-math-cat")}),
  cat({id:40025,testType:"cat",claim:1,domain:"NBT",target:"E",dok:1,standard:"4.NBT.B.6",type:"text-input",questionText:"Enter the unknown number to make the equation true.\n\n348 ÷ 6 = (□ ÷ 6) + (48 ÷ 6)",correctAnswer:"300",rubric:"(1 point) The student enters the correct number.",points:1,official:exact(25,28,"g4-math-cat")}),
  cat({id:40026,testType:"cat",claim:1,domain:"NF",target:"F",dok:2,standard:"4.NF.A.1",type:"shade-grid",questionText:"Click the spaces of the figure to shade 3/5 of Figure R.",shadeGrid:{rows:10,cols:1,requiredCount:6},correctAnswer:["0:0","1:0","2:0","3:0","4:0","5:0"],rubric:"(1 point) The student shades the correct number of spaces.",points:1,official:exact(26,29,"g4-math-cat")}),
  cat({id:40027,testType:"cat",claim:1,domain:"NBT",target:"E",dok:1,standard:"4.NBT.B.5",type:"text-input",questionText:"Enter the product.\n\n96 × 78",correctAnswer:"7488",rubric:"(1 point) The student enters the correct product.",points:1,official:exact(27,30,"g4-math-cat")}),
  cat({id:40028,testType:"cat",claim:1,domain:"NF",target:"H",dok:1,standard:"4.NF.C.6",type:"text-input",questionText:"Enter a decimal that is equivalent to 6/100.",correctAnswer:"0.06",acceptedAnswers:["0.06",".06"],rubric:"(1 point) The student enters the correct decimal.",points:1,official:exact(28,31,"g4-math-cat")}),
  cat({id:40029,testType:"cat",claim:3,domain:"NF",target:"A,D",dok:2,standard:"4.NF.A.2",type:"multi-input",questionText:"Phil writes these fraction comparisons: 1/4 < 1/3 and 1/3 < 1/2.\n\nHe says, “When comparing two fractions, the lesser fraction has the greater denominator.”\n\n**Part A** Enter one digit to complete this comparison so that it supports Phil’s claim: □/6 < 1/3.\n\n**Part B** Enter one digit to complete this comparison and show that Phil’s claim is not always true: □/6 > 1/3.",responseFields:[{label:"Part A"},{label:"Part B"}],correctAnswer:["1","3"],scoringRule:{kind:"constraints",constraint:{kind:"all",constraints:[{kind:"field-one-of",index:0,values:["0","1"]},{kind:"field-number",index:1,min:2,max:9,integer:true}]}},rubric:"(1 point) The student enters a correct number in both parts.",points:1,official:exact(29,32,"g4-math-cat")}),
  cat({id:40030,testType:"cat",claim:3,domain:"OA",target:"D",dok:3,standard:"4.NF.A.2",type:"multi-input",questionText:"Each piece of fruit weighs 3/5 pound.\n\nDrag enough fruit into each box so that the total weight, in pounds, is within the given range.",interactionHelp:"Accessible response: enter the number of fruit pieces for each weight range. You do not need to drag the fruit.",stimulusImages:[{src:"/images/grade-4/test-1/math/item-30-fruit.png",alt:"The official fruit piece used in the grouping interaction.",sha256:"4b59a5d43aec93b506b3db25fe8dea620def69e04df93ad0b3704d52cf5ade12"}],responseFields:[{label:"Number of fruit between 1 and 1 1/2 pounds"},{label:"Number of fruit between 2 and 2 1/2 pounds"}],correctAnswer:["2","4"],scoringRule:{kind:"constraints",constraint:{kind:"all",constraints:[{kind:"field-equals",index:0,value:"2"},{kind:"field-equals",index:1,value:"4"}]}},rubric:"(1 point) The student drags 2 pieces of fruit into the first box and 4 pieces of fruit into the second box.",points:1,official:exact(30,33,"g4-math-cat")}),
  cat({id:40031,testType:"cat",claim:2,domain:"NF",target:"C",dok:2,standard:"4.NF.B.4",type:"multiple-choice",questionText:"A class is making 7 flags. It takes 3/4 of a yard of felt to make each flag.\n\nThe total number of yards of felt needed is between which two numbers?",options:[{label:"A",text:"1 and 2"},{label:"B",text:"3 and 4"},{label:"C",text:"5 and 6"},{label:"D",text:"7 and 8"}],correctAnswer:"C",rubric:"(1 point) The student selects the correct range.",points:1,official:exact(31,34,"g4-math-cat")}),
];

const artDayDirections = `# Art Day!

You are helping your 4th grade class organize an Art Day.

There will be three stations:

• Painting
• Pottery
• Chalk Art

You have two tasks. You will help create the supply list and the schedule for Art Day.

## Task 1: Supply List

You need to make sure there are enough supplies at each station for everyone to participate. You will use the following information to create a list of art supplies for your class.

• There are 24 students in your class.
• Each student needs—
  • 2 paint brushes for the Painting Station.
  • 3 pounds of clay for the Pottery Station.
  • 5 pieces of chalk for the Chalk Art Station.

## Task 2: Schedule

You also need to help plan the schedule for Art Day using the following information.

• The day starts at 9:00 a.m. and ends at 2:00 p.m.
• Your entire class will rotate through the three stations together.
• The Break has to be at least 10 minutes.
• The Break and Lunch together total 1 hour.
• The three stations (Painting, Pottery, and Chalk Art) do not need to be the same amount of time, but each one has to be 30 minutes or longer.`;

export const grade4MathPt: Question[] = [
  pt({id:40101,testType:"pt",claim:2,domain:"OA",target:"2A, 2D",dok:2,standard:"3.OA.A.3",type:"text-input",studentDirections:artDayDirections,questionText:"According to the supply list, how many paint brushes are needed for 24 students?",correctAnswer:"48",rubric:"1 point: Student writes the value correctly: 48.\n\n0 points: All other responses.",points:1,official:exact(1,2,"g4-math-pt")}),
  pt({id:40102,testType:"pt",claim:2,domain:"OA",target:"2A, 2D",dok:2,standard:"3.OA.A.3",type:"text-input",studentDirections:artDayDirections,questionText:"According to the supply list, how many pounds of clay are needed for 24 students?",correctAnswer:"72",rubric:"1 point: Student writes the value correctly: 72.\n\n0 points: All other responses.",points:1,official:exact(2,3,"g4-math-pt")}),
  pt({id:40103,testType:"pt",claim:3,domain:"OA",target:"3B",dok:2,standard:"3.OA.A.3",type:"short-answer",studentDirections:artDayDirections,questionText:"You need 120 pieces of chalk for Art Day. Your teacher has 6 boxes of chalk. Each box has 18 pieces of chalk. Is this enough chalk for Art Day?\n\nExplain the steps you used to figure this out.",correctAnswer:"A 2-point response compares the amount of chalk needed to the amount available, determines whether more chalk is needed, and gives a justification.",scoringRule:{kind:"manual-rubric"},rubric:"2 points: Student develops an approach (compares the amount of chalk needed to the amount available) to determine whether more chalk is needed AND gives a justification for the result.\n\n1 point: Student correctly calculates the amount of chalk available and determines that more chalk is needed, but does not provide a logical explanation why.\n\n0 points: All other responses.",points:2,official:exact(3,6,"g4-math-pt")}),
  pt({id:40104,testType:"pt",claim:4,domain:"MD",target:"A",dok:4,standard:"2.MD.C.7",type:"schedule-table",studentDirections:artDayDirections,questionText:"Your next task is to help plan the schedule for Art Day using the information from **Task 2: Schedule**.\n\nCreate a schedule for your class to follow on Art Day. You must follow the order given in the table.\n\n*Times must be given using a 12-hour clock.*",schedule:{start:"9:00 a.m.",end:"2:00 p.m.",activities:["Painting","Break","Pottery","Lunch","Chalk Art"],minimumActivityMinutes:30,minimumBreakMinutes:10,breakAndLunchMinutes:60,breakActivity:"Break",lunchActivity:"Lunch"},correctAnswer:["9:00","10:30","10:30","10:45","10:45","12:15","12:15","1:00","1:00","2:00"],scoringRule:{kind:"schedule"},rubric:"1 point: Student enters times that satisfy the restrictions listed in Task 2: Schedule (at least 10 minutes for Break, Break and Lunch take exactly one hour, and each station is at least 30 minutes in length).\n\n0 points: All other responses.\n\nScoring Note: Although students can enter a.m. and p.m. in the schedule, it is not required, nor should it count against the students if they use the wrong indication (a.m. or p.m.).",points:1,official:exact(4,12,"g4-math-pt")}),
  pt({id:40105,testType:"pt",claim:2,domain:"MD",target:"2A, 3F",dok:3,standard:"3.MD.A.2",type:"short-answer",studentDirections:artDayDirections,questionText:"When the class went to the Painting Station at 9:00 a.m., the container of paint was completely full. After 6 of the 24 students got their share of paint, the paint level had dropped to the level shown in the picture.\n\nKatie thinks there is not enough paint for the rest of the students.\n\nDo you agree with Katie? Explain why or why not. Use the information shown in your explanation.",stimulusImages:[{src:"/images/grade-4/test-1/math/pt-item-05-paint.png",alt:"Official diagram of a full tapered paint container and its level after 6 students received paint.",sha256:"749bdb27a8f884271ed41edb01c3077a9cc4adbfd3b08ae71bff263ce056fdf7"}],correctAnswer:"A valid response agrees or disagrees with Katie and supplies a mathematically logical explanation using the diagram.",scoringRule:{kind:"manual-rubric"},rubric:"1 point: Student states whether he/she agrees or disagrees with Katie and provides a mathematically logical explanation as to why or why not.\n\n0 points: The student may agree or disagree, but does not supply any logical explanation for his/her response.",points:1,official:exact(5,14,"g4-math-pt")}),
];
