import type { Question } from "./questions";
import {modelBuilding,roomForRoots,sandDunes,signalsAcrossCove,streetlightSources,streetlightTable} from "./grade4-test5-ela-sources";

const BANK_VERSION="2026-07-22.1";
type Item=Omit<Question,"grade"|"subject"|"practiceTest"|"provenance">;
const options=(texts:string[])=>texts.map((text,index)=>({label:"ABCDEF"[index],text}));
function sourceId(v:Item){if(v.testType==="pt")return"g4-t5-ela-pt-shielded-streetlights";if(v.id<=49007)return"g4-t5-ela-literary-signals-cove";if(v.id<=49015)return"g4-t5-ela-informational-roots-city";if(v.id<=49021)return`g4-t5-ela-writing-${v.id}`;if(v.id<=49024)return"g4-t5-ela-listening-model-building";if(v.id<=49027)return"g4-t5-ela-listening-sand-dunes";return`g4-t5-ela-research-${v.id}`;}
function item(v:Item):Question{return{...v,grade:4,subject:"ela",practiceTest:5,provenance:{sourceId:sourceId(v),origin:"original",author:"CAASPP Practice Project",license:"Original companion content; all rights reserved for this project.",reviewedAt:"2026-07-22"}};}
function balanceOptionPositions(question:Question):Question{
  const shift=question.id%4;
  const rotate=(list:NonNullable<Question["options"]>)=>{
    const length=list.length,amount=shift%length;
    const moved=[...list.slice(length-amount),...list.slice(0,length-amount)];
    const answerMap=new Map(list.map((entry,index)=>[entry.label,"ABCDEF"[(index+amount)%length]]));
    return{list:moved.map((entry,index)=>({...entry,label:"ABCDEF"[index]})),answerMap};
  };
  if(question.partAOptions&&question.partBOptions&&Array.isArray(question.correctAnswer)){
    const a=rotate(question.partAOptions),b=rotate(question.partBOptions);
    return{...question,partAOptions:a.list,partBOptions:b.list,correctAnswer:[a.answerMap.get(question.correctAnswer[0])!,b.answerMap.get(question.correctAnswer[1])!]};
  }
  if(question.options){const moved=rotate(question.options);const correctAnswer=Array.isArray(question.correctAnswer)?question.correctAnswer.map(answer=>moved.answerMap.get(answer)!):moved.answerMap.get(question.correctAnswer)!;const scoringRule=question.scoringRule?.kind==="unordered-set"?{...question.scoringRule,acceptedAnswers:question.scoringRule.acceptedAnswers.map(answer=>moved.answerMap.get(answer)!)}:question.scoringRule;return{...question,options:moved.list,correctAnswer,scoringRule};}
  return question;
}

export const grade4Test5ElaCat:Question[]=[
item({id:49001,testType:"cat",claim:1,target:"1",dok:2,standard:"RL.4.1",type:"multiple-choice",passage:signalsAcrossCove,passageTitle:"Signals Across the Cove",questionText:"Why does Nia box the disputed time instead of erasing it?",options:options(["It preserves evidence of where the two records separated.","It makes her total larger than Tomas's.","It proves the wind stopped at 9:30.","It removes the uncertain block from both pages."]),correctAnswer:"A",rubric:"1 point: A.",points:1,explanation:"Nia recognizes that the mismatch itself is useful evidence."}),
item({id:49002,testType:"cat",claim:1,target:"2",dok:3,standard:"RL.4.2",type:"multiple-choice",passage:signalsAcrossCove,passageTitle:"Signals Across the Cove",questionText:"Which theme is best developed through the students' first and second observation days?",options:options(["A careful system should be revised when evidence reveals an ambiguity.","Partners must always produce identical observations.","Nature can be studied only in calm weather.","Remembering an event is more reliable than written notes."]),correctAnswer:"A",rubric:"1 point: A.",points:1,explanation:"They preserve conflicting evidence, identify ambiguity, and redesign and retest the signals."}),
item({id:49003,testType:"cat",claim:1,target:"3",dok:2,standard:"RL.4.4",type:"two-part",passage:signalsAcrossCove,passageTitle:"Signals Across the Cove",questionText:"The story says sunlight “distorted” the card's color.",partAPrompt:"Part A: What does distorted mean?",partAOptions:options(["made unclear or changed in appearance","copied exactly","moved closer","recorded in a table"]),partBPrompt:"Part B: What effect does the word create?",partBOptions:options(["It explains how an honest observation could lead to a mistaken identification.","It proves Tomas used the wrong card.","It shows the card was broken.","It means the students stopped counting birds."]),correctAnswer:["A","A"],rubric:"1 point: Both parts.",points:1,explanation:"Glare and angle altered the appearance without anyone intending a false signal."}),
item({id:49004,testType:"cat",claim:1,target:"4",dok:3,standard:"RL.4.1",type:"two-part",passage:signalsAcrossCove,passageTitle:"Signals Across the Cove",questionText:"Answer both parts about Tomas's first explanation.",partAPrompt:"Part A: What assumption does Tomas make?",partAOptions:options(["The repeated red canceled or delayed the next block.","Nia never raised a red card.","Every bird crossed twice.","The wind could not change a card's appearance."]),partBPrompt:"Part B: Which evidence most directly reveals the assumption?",partBOptions:options(["He says he thought the first repeat meant the next block had not started.","He stands on the opposite deck.","He counts eleven birds.","He helps test the new system at the dock."]),correctAnswer:["A","A"],rubric:"1 point: Both parts.",points:1,explanation:"Tomas explicitly describes how he interpreted the repeated signal."}),
item({id:49005,testType:"cat",claim:1,target:"5",dok:3,standard:"RL.4.3",type:"multi-select",selection:{min:2,max:2},passage:signalsAcrossCove,passageTitle:"Signals Across the Cove",questionText:"Select the two events that most change both students' explanations of the mismatch.",options:options(["They compare Nia's timed card notes with Tomas's understanding marks.","They realize blue did not identify which action should be repeated.","Nia holds her blue card against a clipboard.","Their first totals differ by one bird."]),correctAnswer:["A","B"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B"]},rubric:"1 point: A and B.",points:1,explanation:"The note comparison and ambiguous repeat rule reconcile both partial accounts."}),
item({id:49006,testType:"cat",claim:1,target:"6",dok:3,standard:"RL.4.5",type:"grid-match",passage:signalsAcrossCove,passageTitle:"Signals Across the Cove",questionText:"Match each story detail to its main structural role.",gridRows:["The angled green card appears blue.","The pages show different kinds of marks.","The new position-and-color system is tested."],gridColumns:["Creates the central confusion","Provides evidence that reconciles accounts","Shows the resolution being evaluated"],gridSelection:{perRowMin:1,perRowMax:1,totalMin:3,totalMax:3},correctAnswer:["0:0","1:1","2:2"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","1:1","2:2"]},rubric:"1 point: All three.",points:1,explanation:"The details introduce, investigate, and resolve the conflict."}),
item({id:49007,testType:"cat",claim:1,target:"7",dok:3,standard:"L.4.5a",type:"two-part",passage:signalsAcrossCove,passageTitle:"Signals Across the Cove",questionText:"The text calls their notes “two maps of the same hour.”",partAPrompt:"Part A: What does the comparison suggest?",partAOptions:options(["Each record represents the same events from a different viewpoint.","Both students draw shore maps.","The pages contain identical information.","Their observation lasted two hours."]),partBPrompt:"Part B: Why is the comparison important?",partBOptions:options(["It shows why combining the records reveals more than choosing one as correct.","It proves maps are better than time notes.","It explains how to identify birds.","It shows the cove has two entrances."]),correctAnswer:["A","A"],rubric:"1 point: Both parts.",points:1,explanation:"Like partial maps, their records overlap but contain different clues."}),
item({id:49008,testType:"cat",claim:1,target:"8",dok:2,standard:"RI.4.1",type:"multiple-choice",passage:roomForRoots,passageTitle:"Room for Roots Beneath a City Street",questionText:"Why does compacted soil create two linked problems for roots?",options:options(["Closed pores reduce paths for both water and air.","Compaction adds too many utilities.","It makes every tree grow deeper.","It turns roots into pavement."]),correctAnswer:"A",rubric:"1 point: A.",points:1,explanation:"The same pore spaces support water movement and oxygen."}),
item({id:49009,testType:"cat",claim:1,target:"9",dok:3,standard:"RI.4.2",type:"multiple-choice",passage:roomForRoots,passageTitle:"Room for Roots Beneath a City Street",questionText:"Which statement best expresses the article's main idea?",options:options(["Successful street-tree plans balance root needs with structures, access, water, utilities, and long-term evidence.","Soil cells are the only acceptable planting method.","Tree roots should always be cut when pavement moves.","Every street should use the same tree species."]),correctAnswer:"A",rubric:"1 point: A.",points:1,explanation:"The article repeatedly connects root health with competing needs and monitoring."}),
item({id:49010,testType:"cat",claim:1,target:"10",dok:2,standard:"RI.4.4",type:"multiple-choice",passage:roomForRoots,passageTitle:"Room for Roots Beneath a City Street",questionText:"What does *network* mean in the section “A Crowded Underground Network”?",options:options(["A connected group of utilities and structures sharing space","A group of tree leaves","One single pipe","A plan for trimming branches"]),correctAnswer:"A",rubric:"1 point: A.",points:1,explanation:"The paragraph lists several connected underground systems."}),
item({id:49011,testType:"cat",claim:1,target:"11",dok:3,standard:"RI.4.1",type:"two-part",passage:roomForRoots,passageTitle:"Room for Roots Beneath a City Street",questionText:"Answer both parts about choosing a design.",partAPrompt:"Part A: Why does no single design work everywhere?",partAOptions:options(["Sites differ in width, utilities, drainage, street use, and tree needs.","Roots need no water in cities.","Every sidewalk has the same construction.","Monitoring replaces planning."]),partBPrompt:"Part B: Which detail best supports the answer?",partBOptions:options(["A system fitting a new street may be difficult to add beneath an old one with utilities.","Fine roots absorb water.","Mulch slows evaporation.","Trees have trunks."]),correctAnswer:["A","A"],rubric:"1 point: Both parts.",points:1,explanation:"Site conditions change the feasibility and tradeoffs of each design."}),
item({id:49012,testType:"cat",claim:1,target:"12",dok:3,standard:"RI.4.7",type:"multi-select",selection:{min:2,max:2},passage:roomForRoots,passageTitle:"Room for Roots Beneath a City Street",questionText:"Select the two relationships a soil-cell cross section and the article together would show.",options:options(["A frame supports pavement while less-compacted soil gives roots room below.","Utility corridors may remain separate from connected root space.","Roots grow only inside metal pipes.","Pavement needs no structural support."]),correctAnswer:["A","B"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B"]},rubric:"1 point: A and B.",points:1,explanation:"Both relationships are explicitly described in the soil-cell section."}),
item({id:49013,testType:"cat",claim:1,target:"13",dok:3,standard:"RI.4.5",type:"grid-match",passage:roomForRoots,passageTitle:"Room for Roots Beneath a City Street",questionText:"Match each feature to the reasoning it supports.",gridRows:["Connected-hallways comparison","Soil-cell benefit and cost contrast","Several-season monitoring examples"],gridColumns:["Explains pore movement","Shows a design tradeoff","Shows why patterns require repeated evidence"],gridSelection:{perRowMin:1,perRowMax:1,totalMin:3,totalMax:3},correctAnswer:["0:0","1:1","2:2"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","1:1","2:2"]},rubric:"1 point: All three.",points:1,explanation:"Each feature contributes a distinct explanatory function."}),
item({id:49014,testType:"cat",claim:1,target:"14",dok:2,standard:"L.4.5a",type:"two-part",passage:roomForRoots,passageTitle:"Room for Roots Beneath a City Street",questionText:"The author compares soil pores to connected hallways.",partAPrompt:"Part A: What similarity does the comparison emphasize?",partAOptions:options(["Both provide routes through a larger space.","Both are made of concrete.","Both contain streetlights.","Both prevent all water movement."]),partBPrompt:"Part B: What limitation of the comparison should a reader understand?",partBOptions:options(["Soil pores carry water and air and change with compaction; they are not human hallways.","Hallways are always outdoors.","Roots never enter pore spaces.","Soil contains no particles."]),correctAnswer:["A","A"],rubric:"1 point: Both parts.",points:1,explanation:"The comparison clarifies connection without making the systems identical."}),
item({id:49015,testType:"cat",claim:1,target:"8,11",dok:3,standard:"RI.4.1",type:"multi-select",selection:{min:2,max:2},passage:roomForRoots,passageTitle:"Room for Roots Beneath a City Street",questionText:"Select one benefit and one limitation of soil cells stated in the article.",options:options(["They can hold a larger root zone under supported pavement.","They may cost more and conflict with existing utilities.","They guarantee that every tree survives.","They remove the need for drainage and inspection."]),correctAnswer:["A","B"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B"]},rubric:"1 point: A and B.",points:1,explanation:"The article presents both the added soil volume and installation constraints."}),
item({id:49016,testType:"cat",claim:2,target:"1b",dok:3,standard:"W.4.3b",type:"multiple-choice",questionText:"Arun reached the second compass marker, but the path ahead split around a boulder. Which continuation best advances the action and reveals his response?",options:options(["He checked the bearing again, noticed the left path matched it, and felt his shoulders loosen.","Compasses have magnetic needles.","The boulder was gray.","Many paths exist in parks."]),correctAnswer:"A",rubric:"1 point: A.",points:1,explanation:"The sentence adds action, evidence, and an internal response."}),
item({id:49017,testType:"cat",claim:2,target:"3b",dok:3,standard:"W.4.2c",type:"two-part",questionText:"Rain strikes bare soil with force. ___, loose particles wash downhill. Plants slow this movement; ___, roots cannot prevent all erosion during a severe storm.",partAPrompt:"Part A: Choose the cause-and-effect transition.",partAOptions:options(["As a result","For example","Earlier","Similarly"]),partBPrompt:"Part B: Choose the qualifying transition.",partBOptions:options(["however","therefore","first","in addition"]),correctAnswer:["A","A"],rubric:"1 point: Both parts.",points:1,explanation:"As a result expresses consequence; however introduces a limit."}),
item({id:49018,testType:"cat",claim:2,target:"6b",dok:2,standard:"W.4.1a",type:"multiple-choice",questionText:"Which claim best fits reasons about fair access, repair time, and cost for shared science equipment?",options:options(["The school should create a checkout schedule and repair fund before buying additional shared equipment.","Science equipment is interesting.","Every student should purchase laboratory tools.","Broken equipment should remain in the cabinet."]),correctAnswer:"A",rubric:"1 point: A.",points:1,explanation:"The claim is qualified and addresses all three reasons."}),
item({id:49019,testType:"cat",claim:2,target:"8",dok:2,standard:"L.4.3",type:"multiple-choice",questionText:"Which revision is most precise? The second bridge model moved ___ than the first during the same test.",options:options(["less","2.4 centimeters less at its center","in a different way","somewhat"]),correctAnswer:"B",rubric:"1 point: B.",points:1,explanation:"The measured amount and location make the comparison precise."}),
item({id:49020,testType:"cat",claim:2,target:"9",dok:2,standard:"L.4.1",type:"two-part",questionText:"Neither the box of cables nor the two tool cases ___ on the marked shelf.",partAPrompt:"Part A: Choose the correct verb.",partAOptions:options(["belong","belongs"]),partBPrompt:"Part B: Which subject controls agreement?",partBOptions:options(["the nearer plural subject, two tool cases","the singular word box","the word shelf","the word cables only"]),correctAnswer:["A","A"],rubric:"1 point: Both parts.",points:1,explanation:"With neither/nor, the verb agrees with the nearer subject, cases."}),
item({id:49021,testType:"cat",claim:2,target:"9",dok:2,standard:"L.4.2",type:"multi-select",selection:{min:2,max:2},questionText:"Select the two edits needed: “Bring the ruler, tape and level” Mira said, “then meet me at the ramp.”",options:options(["Add a comma after tape.","Add a comma after level, before the closing quotation mark.","Remove the quotation marks.","Lowercase Mira."]),correctAnswer:["A","B"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B"]},rubric:"1 point: A and B.",points:1,explanation:"The series needs a comma, and the dialogue tag is separated by a comma inside the quotation."}),
item({id:49022,testType:"cat",claim:3,target:"4",dok:2,standard:"SL.4.2",type:"multiple-choice",passage:modelBuilding,passageTitle:"Testing a Model Building Against Shaking",audio:{src:"/audio/presentations/grade-4/test-5-testing-a-model-building-against-shaking.m4a",title:"Testing a Model Building Against Shaking narration",transcript:modelBuilding},questionText:"What main idea does the model-building presentation develop?",options:options(["A fair model comparison controls conditions, repeats measurements, and limits its conclusion.","The tallest model always moves least.","One trial proves how every real building behaves.","Craft sticks are stronger than all building materials."]),correctAnswer:"A",rubric:"1 point: A.",points:1,explanation:"The presentation connects controls, repetition, results, and evidence limits."}),
item({id:49023,testType:"cat",claim:3,target:"4",dok:3,standard:"SL.4.2",type:"multi-select",selection:{min:2,max:2},passage:modelBuilding,passageTitle:"Testing a Model Building Against Shaking",audio:{src:"/audio/presentations/grade-4/test-5-testing-a-model-building-against-shaking.m4a",title:"Testing a Model Building Against Shaking narration",transcript:modelBuilding},questionText:"Select the two details that are controlled to make the tower comparison fair.",options:options(["Both towers have the same height and floor masses.","The handle turns ten times at the same marked speed.","Tower B has diagonal braces.","The trial results use different rulers."]),correctAnswer:["A","B"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B"]},rubric:"1 point: A and B.",points:1,explanation:"Those conditions remain constant; braces are the planned difference."}),
item({id:49024,testType:"cat",claim:3,target:"4",dok:3,standard:"SL.4.3",type:"two-part",passage:modelBuilding,passageTitle:"Testing a Model Building Against Shaking",audio:{src:"/audio/presentations/grade-4/test-5-testing-a-model-building-against-shaking.m4a",title:"Testing a Model Building Against Shaking narration",transcript:modelBuilding},questionText:"Answer both parts about the test's conclusion.",partAPrompt:"Part A: Which conclusion is supported?",partAOptions:options(["Diagonal braces reduced roof movement in this model and test.","Every full-size building must copy Tower B.","Tower A can never be improved.","Side-to-side shaking represents every real motion."]),partBPrompt:"Part B: Which detail most strongly limits the conclusion?",partBOptions:options(["Real buildings differ in materials, foundations, connections, and shaking directions.","The models use craft sticks.","The ruler stands beside the tower.","The handle turns ten times."]),correctAnswer:["A","A"],rubric:"1 point: Both parts.",points:1,explanation:"The result is repeatable but applies only to the tested model conditions."}),
item({id:49025,testType:"cat",claim:3,target:"4",dok:2,standard:"SL.4.2",type:"multiple-choice",passage:sandDunes,passageTitle:"How Sand Dunes Move",audio:{src:"/audio/presentations/grade-4/test-5-how-sand-dunes-move.m4a",title:"How Sand Dunes Move narration",transcript:sandDunes},questionText:"Which statement best summarizes the dune presentation?",options:options(["Wind erodes and deposits sand, while repeated measurements reveal movement patterns and influences.","Dunes move forward as solid blocks.","One photograph proves a yearly direction.","Plants always stop every grain of sand."]),correctAnswer:"A",rubric:"1 point: A.",points:1,explanation:"The presentation explains both the process and the evidence needed to track it."}),
item({id:49026,testType:"cat",claim:3,target:"4",dok:3,standard:"SL.4.2",type:"grid-match",passage:sandDunes,passageTitle:"How Sand Dunes Move",audio:{src:"/audio/presentations/grade-4/test-5-how-sand-dunes-move.m4a",title:"How Sand Dunes Move narration",transcript:sandDunes},questionText:"Match each process or evidence detail to its role.",gridRows:["Grains leave the windward side","Grains settle on the leeward side","Distances from a fixed stake decrease over several seasons"],gridColumns:["Erosion","Deposition","Evidence of continued movement toward the stake"],gridSelection:{perRowMin:1,perRowMax:1,totalMin:3,totalMax:3},correctAnswer:["0:0","1:1","2:2"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","1:1","2:2"]},rubric:"1 point: All three.",points:1,explanation:"The speaker explicitly connects each detail to the named process or inference."}),
item({id:49027,testType:"cat",claim:3,target:"4",dok:3,standard:"SL.4.3",type:"multi-select",selection:{min:2,max:2},passage:sandDunes,passageTitle:"How Sand Dunes Move",audio:{src:"/audio/presentations/grade-4/test-5-how-sand-dunes-move.m4a",title:"How Sand Dunes Move narration",transcript:sandDunes},questionText:"Select the two details supporting the need for repeated dune measurements.",options:options(["A storm from an unusual direction may cause only a temporary change.","A single distance does not show the dune's earlier position.","Every dune moves at the same rate.","The leeward side always faces east."]),correctAnswer:["A","B"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B"]},rubric:"1 point: A and B.",points:1,explanation:"Repeated evidence distinguishes a sustained pattern from one event or position."}),
item({id:49028,testType:"cat",claim:4,target:"2",dok:3,standard:"W.4.8",type:"multi-select",selection:{min:2,max:2},questionText:"Select the two complementary sources most useful for explaining how suspension systems reduce bridge motion.",options:options(["An engineering-university diagram labeling cables, deck, towers, and dampers","A transportation-lab report comparing measured bridge movement before and after dampers","A list of bridge paint colors","A tourist's ranking of city views"]),correctAnswer:["A","B"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B"]},rubric:"1 point: A and B.",points:1,explanation:"The diagram explains components while the report provides measured performance evidence."}),
item({id:49029,testType:"cat",claim:4,target:"3",dok:3,standard:"W.4.8",type:"two-part",questionText:"An interview with one roofing contractor says a reflective roof kept one warehouse cooler last July.",partAPrompt:"Part A: Which claim can the interview support?",partAOptions:options(["The contractor observed a cooler interior at one warehouse during the stated period.","Every reflective roof lowers every building by the same amount.","Reflective roofs have no cost.","July weather is identical each year."]),partBPrompt:"Part B: Which caveat must accompany the evidence?",partBOptions:options(["One person's observation at one building does not establish results for all buildings.","Interviews can never be used.","Warehouses have no roofs.","Temperature cannot be measured."]),correctAnswer:["A","A"],rubric:"1 point: Both parts.",points:1,explanation:"The source supports its limited observation, not a universal result."}),
item({id:49030,testType:"cat",claim:4,target:"4",dok:3,standard:"W.4.9",type:"multi-select",selection:{min:2,max:2},questionText:"A writer claims reflective roofs may reduce summer cooling needs, but results depend on the building. Select the two sentences that jointly support the qualified claim.",options:options(["Three similar stores used 12–18% less cooling electricity after roof changes.","A shaded building in the same study showed almost no change.","The roofs were visible from an airplane.","The stores sold different signs."]),correctAnswer:["A","B"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B"]},rubric:"1 point: A and B.",points:1,explanation:"One detail supports a benefit and the other supports the stated limitation."}),
].map(balanceOptionPositions);

export const grade4Test5ElaPt:Question[]=[
item({id:49101,testType:"pt",claim:4,target:"4",dok:3,standard:"W.4.9",type:"short-answer",passage:streetlightSources,passageTitle:"Should the Town Use Shielded LED Streetlights?",dataTable:streetlightTable,questionText:"Compare how Sources 1 and 3 use different kinds of evidence. Include one accurate detail from each and explain one limitation of the pilot evidence.",correctAnswer:"Source 1 explains how shielding, output, color, and placement affect visibility and glare. Source 3 reports measured and observed pilot results, such as 44% lower electricity use. The twelve-week, four-block pilot cannot prove long-term or townwide results.",scoringRule:{kind:"manual-rubric"},rubric:"2 points: Accurately compares explanatory and pilot evidence, gives one relevant detail from each, and states a valid pilot limitation. 1 point: Partly accurate comparison or incomplete evidence/limitation. 0 points: Incorrect, irrelevant, insufficient, or blank.",points:2,explanation:"Source 1 explains mechanisms and choices; Source 3 provides local measurements with stated limits."}),
item({id:49102,testType:"pt",claim:4,target:"2,3",dok:3,standard:"W.4.8",type:"grid-match",passage:streetlightSources,passageTitle:"Should the Town Use Shielded LED Streetlights?",dataTable:streetlightTable,questionText:"Match each qualified planning statement to its supporting source or sources. Select exactly 1 source in Row 1, exactly 2 in Row 2, and exactly 1 in Row 3.",gridRows:["Row 1: Shielding can direct less light toward windows or sky.","Row 2: Expansion must preserve crossing visibility and account for location-specific problems.","Row 3: Pilot electricity use fell while all three measured crossings met the requirement."],gridColumns:["Source 1","Source 2","Source 3"],gridSelection:{perRowMin:1,perRowMax:2,rowSelections:[{min:1,max:1},{min:2,max:2},{min:1,max:1}],totalMin:4,totalMax:4},correctAnswer:["0:0","1:1","1:2","2:2"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","1:1","1:2","2:2"]},rubric:"1 point: All four source matches.",points:1,explanation:"Source 1 explains shielding; Sources 2 and 3 support requirements and local issues; Source 3 contains the pilot measures."}),
item({id:49103,testType:"pt",claim:2,target:"7",dok:4,standard:"W.4.1",type:"extended-writing",passage:streetlightSources,passageTitle:"Should the Town Use Shielded LED Streetlights?",dataTable:streetlightTable,studentDirections:"Write an opinion for the town planning team. You may recommend replacement, no replacement, or a conditional/phased plan. Use accurate evidence from more than one source, address competing evidence or a limitation, and keep safety and accessibility requirements in your plan.",questionText:"Should the town change to shielded LED streetlights, and if so, how? Write a well-organized opinion using the sources.",correctAnswer:"Responses will vary and are scored with the 4-4-2 opinion-writing rubric.",scoringRule:{kind:"manual-rubric"},rubric:"10 points: Organization/Purpose 0–4, Evidence/Elaboration 0–4, Conventions 0–2. NS applies to blank, copied, off-topic, or non-English responses that cannot be scored.",points:10,explanation:"A strong response states a defensible position, integrates multiple sources, addresses competing evidence, and preserves required safety and accessibility."}),
];

export const grade4Test5ElaBankVersion=BANK_VERSION;
