import type { Question } from "./questions";

const BANK_VERSION = "2026-07-22.1";
type Item = Omit<Question, "grade" | "subject" | "practiceTest" | "provenance">;

function item(value: Item): Question {
  return {
    ...value,
    grade: 4,
    subject: "math",
    practiceTest: 2,
    provenance: {
      sourceId: value.testType === "pt" ? "g4-t2-math-pt-walking-routes" : `g4-t2-math-cat-${value.id}`,
      origin: "original",
      author: "CAASPP Practice Project",
      license: "Original companion content; all rights reserved for this project.",
      reviewedAt: "2026-07-22",
    },
  };
}

const fourOptions = (texts: string[]) => texts.map((text, index) => ({ label: "ABCD"[index], text }));

export const grade4Test2MathCat: Question[] = [
  item({id:42001,testType:"cat",claim:1,domain:"OA",target:"A",dok:2,standard:"4.OA.A.3",type:"text-input",questionText:"A reading room has 6 shelves with 24 notebooks on each shelf. A teacher removes 19 notebooks. How many notebooks remain?",correctAnswer:"125",scoringRule:{kind:"numeric-equivalent",acceptedValues:[125]},rubric:"1 point: The student enters 125.",points:1,explanation:"Six groups of 24 make 144 notebooks. Then 144 − 19 = 125."}),
  item({id:42002,testType:"cat",claim:1,domain:"NBT",target:"D",dok:1,standard:"4.NBT.A.2",type:"multiple-choice",questionText:"Which comparison between 408,750 and 408,705 is true?",options:fourOptions(["408,750 < 408,705","408,750 = 408,705","408,750 > 408,705","408,750 is 10,000 greater than 408,705"]),correctAnswer:"C",rubric:"1 point: The student selects C.",points:1,explanation:"Both numbers match through the hundreds place. In the tens place, 5 tens is greater than 0 tens."}),
  item({id:42003,testType:"cat",claim:1,domain:"NBT",target:"D",dok:1,standard:"4.NBT.A.3",type:"text-input",questionText:"Round 376,482 to the nearest ten thousand.",correctAnswer:"380000",acceptedAnswers:["380000","380,000"],rubric:"1 point: The student enters 380,000.",points:1,explanation:"The thousands digit is 6, so 376,482 rounds up to 380,000."}),
  item({id:42004,testType:"cat",claim:1,domain:"NBT",target:"E",dok:1,standard:"4.NBT.B.4",type:"text-input",questionText:"Find the difference.\n\n802,314 − 276,895",correctAnswer:"525419",acceptedAnswers:["525419","525,419"],rubric:"1 point: The student enters 525,419.",points:1,explanation:"Regrouping by place value gives 802,314 − 276,895 = 525,419."}),
  item({id:42005,testType:"cat",claim:1,domain:"NBT",target:"E",dok:2,standard:"4.NBT.B.5",type:"multi-input",questionText:"Use partial products to find 34 × 26. Enter the four partial products in the order shown, then enter their sum.\n\n30 × 20; 30 × 6; 4 × 20; 4 × 6; sum",responseFields:[{label:"30 × 20"},{label:"30 × 6"},{label:"4 × 20"},{label:"4 × 6"},{label:"Sum"}],correctAnswer:["600","180","80","24","884"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: All four partial products and the sum are correct.",points:1,explanation:"The partial products are 600, 180, 80, and 24. Their sum is 884."}),
  item({id:42006,testType:"cat",claim:1,domain:"NBT",target:"E",dok:2,standard:"4.NBT.B.6",type:"multiple-choice",questionText:"A museum has 347 student tickets. The tickets are placed into groups of 8. What does the quotient and remainder mean?",options:fourOptions(["There are 42 full groups and 11 tickets left.","There are 43 full groups and 3 tickets left.","There are 44 full groups and 5 tickets left.","There are 45 full groups and 7 tickets left."]),correctAnswer:"B",rubric:"1 point: The student selects B.",points:1,explanation:"347 ÷ 8 = 43 remainder 3 because 43 × 8 = 344."}),
  item({id:42007,testType:"cat",claim:1,domain:"OA",target:"B",dok:1,standard:"4.OA.B.4",type:"multi-select",selection:{min:3,max:3},questionText:"Select all three factor pairs of 28.",options:[{label:"A",text:"1 and 28"},{label:"B",text:"2 and 14"},{label:"C",text:"3 and 9"},{label:"D",text:"4 and 7"},{label:"E",text:"5 and 6"}],correctAnswer:["A","B","D"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B","D"]},rubric:"1 point: The student selects A, B, and D only.",points:1,explanation:"The whole-number products equal to 28 are 1 × 28, 2 × 14, and 4 × 7."}),
  item({id:42008,testType:"cat",claim:1,domain:"OA",target:"C",dok:2,standard:"4.OA.C.5",type:"grid-match",questionText:"Match each completed input/output table to its rule.",gridRows:["Table A: 1→6, 2→7, 3→8","Table B: 1→4, 2→8, 3→12","Table C: 1→3, 2→6, 3→9"],gridColumns:["Add 5","Multiply by 4","Multiply by 3"],gridSelection:{perRowMin:1,perRowMax:1,totalMin:3,totalMax:3},correctAnswer:["0:0","1:1","2:2"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","1:1","2:2"]},rubric:"1 point: All three tables are matched correctly.",points:1,explanation:"Table A adds 5, Table B multiplies by 4, and Table C multiplies by 3."}),
  item({id:42009,testType:"cat",claim:1,domain:"NF",target:"F",dok:1,standard:"4.NF.A.1",type:"multiple-choice",questionText:"The strip model shows a fraction. Which fraction is equivalent to the shaded part?",stimulusImages:[{src:"/images/grade-4/test-2/math/fraction-strip.svg",alt:"A strip divided into four equal parts with three parts shaded.",sha256:"5461631b0e36d612c24325ea36c746b45920c0079507a4fbc0a4d917dcfbd8d1"}],options:fourOptions(["3/8","4/6","6/8","8/12"]),correctAnswer:"C",rubric:"1 point: The student selects 6/8.",points:1,explanation:"The model shows 3/4. Multiplying numerator and denominator by 2 gives 6/8."}),
  item({id:42010,testType:"cat",claim:1,domain:"NF",target:"F",dok:2,standard:"4.NF.A.2",type:"multi-select",selection:{min:2,max:2},questionText:"Select the two true comparisons.",options:[{label:"A",text:"5/8 > 1/2"},{label:"B",text:"3/10 < 1/2"},{label:"C",text:"7/12 < 1/2"},{label:"D",text:"4/9 > 1/2"}],correctAnswer:["A","B"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B"]},rubric:"1 point: The student selects A and B only.",points:1,explanation:"5/8 is greater than 4/8, and 3/10 is less than 5/10. The other comparisons are false."}),
  item({id:42011,testType:"cat",claim:1,domain:"NF",target:"G",dok:1,standard:"4.NF.B.3d",type:"text-input",questionText:"Mina uses 3/8 cup of oats and 2/8 cup of seeds. How many cups does she use in all?",correctAnswer:"5/8",scoringRule:{kind:"numeric-equivalent",acceptedValues:[0.625]},rubric:"1 point: The student enters a value equivalent to 5/8.",points:1,explanation:"The denominators are the same, so 3/8 + 2/8 = 5/8."}),
  item({id:42012,testType:"cat",claim:1,domain:"NF",target:"G",dok:2,standard:"4.NF.B.3c",type:"two-part",questionText:"Answer both parts about subtracting the mixed numbers.",partAPrompt:"Part A: What is 4 3/5 − 1 1/5?",partAOptions:fourOptions(["2 2/5","3 1/5","3 2/5","5 4/5"]),partBPrompt:"Part B: Which equation supports the answer?",partBOptions:fourOptions(["(4 − 1) + (3/5 − 1/5) = 3 2/5","(4 − 1) + (3/5 + 1/5) = 3 4/5","(4 + 1) − (3/5 − 1/5) = 4 3/5","(4 − 1) + (3 − 1)/10 = 3 2/10"]),correctAnswer:["C","A"],rubric:"1 point: Both parts are correct.",points:1,explanation:"Subtract the whole numbers and the like fractions: 3 + 2/5 = 3 2/5."}),
  item({id:42013,testType:"cat",claim:1,domain:"NF",target:"G",dok:2,standard:"4.NF.B.4",type:"multi-input",questionText:"Five groups each contain 3/8 yard of ribbon. Enter the product as an improper fraction and as a mixed number.",responseFields:[{label:"Improper fraction",acceptedAnswers:["15/8"]},{label:"Mixed number",acceptedAnswers:["1 7/8","1⅞"]}],correctAnswer:["15/8","1 7/8"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: Both equivalent forms are correct.",points:1,explanation:"5 × 3/8 = 15/8, which is 1 7/8."}),
  item({id:42014,testType:"cat",claim:1,domain:"NF",target:"H",dok:1,standard:"4.NF.C.6",type:"text-input",questionText:"A hundred grid has 37 of its 100 squares shaded. Write the shaded amount as a decimal.",correctAnswer:"0.37",scoringRule:{kind:"numeric-equivalent",acceptedValues:[0.37]},rubric:"1 point: The student enters 0.37.",points:1,explanation:"Thirty-seven hundredths is written 0.37."}),
  item({id:42015,testType:"cat",claim:1,domain:"NF",target:"H",dok:2,standard:"4.NF.C.7",type:"grid-match",questionText:"Use the shaded amounts in each pair. Choose the correct comparison symbol for each row.",stimulusImages:[{src:"/images/grade-4/test-2/math/decimal-grids.svg",alt:"Pair A shows 45 and 50 shaded hundredths; Pair B shows 32 and 29 shaded hundredths; Pair C shows 70 and 70 shaded hundredths.",sha256:"1a872dec3b6f7c5ca6d0687c07a9aaa0852edce810748d73c631d832da84ad3d"}],gridRows:["Pair A: 0.45 ___ 0.50","Pair B: 0.32 ___ 0.29","Pair C: 0.70 ___ 0.70"],gridColumns:["<","=",">"],gridSelection:{perRowMin:1,perRowMax:1,totalMin:3,totalMax:3},correctAnswer:["0:0","1:2","2:1"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","1:2","2:1"]},rubric:"1 point: All three comparisons are correct.",points:1,explanation:"45 hundredths is less than 50 hundredths; 32 hundredths is greater than 29 hundredths; 70 hundredths equals 70 hundredths."}),
  item({id:42016,testType:"cat",claim:1,domain:"MD",target:"I",dok:2,standard:"4.MD.A.1",type:"table-input",questionText:"Complete the conversion row.",dataTable:{columns:["Relationship"],rows:[{label:"Length",values:["1 meter = 100 centimeters"]},{label:"Capacity",values:["1 liter = 1,000 milliliters"]},{label:"Mass",values:["1 kilogram = 1,000 grams"]}]},tableColumns:["3 meters in centimeters","5 liters in milliliters","4 kilograms in grams"],tableRowLabel:"Converted value",correctAnswer:["300","5000","4000"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: All three conversions are correct.",points:1,explanation:"Multiply by the number of smaller units in one larger unit: 300 cm, 5,000 mL, and 4,000 g."}),
  item({id:42017,testType:"cat",claim:1,domain:"MD",target:"K",dok:2,standard:"4.MD.C.5",type:"multiple-choice",questionText:"How should angle ABC be classified?",stimulusImages:[{src:"/images/grade-4/test-2/math/angle-type.svg",alt:"Angle ABC measures 112 degrees.",sha256:"c4d13e93670cdaf517b322d053e3c97f4151b92645d25b0288f5842e13e6fc19"}],options:fourOptions(["acute angle","right angle","obtuse angle","straight angle"]),correctAnswer:"C",rubric:"1 point: The student selects obtuse angle.",points:1,explanation:"An angle greater than 90° and less than 180° is obtuse. 112° is obtuse."}),
  item({id:42018,testType:"cat",claim:2,domain:"OA",target:"A,C",dok:2,standard:"4.OA.A.3",type:"text-input",questionText:"Seven swimming classes each have 18 students registered. On lesson day, 22 students are absent. How many students attend?",correctAnswer:"104",scoringRule:{kind:"numeric-equivalent",acceptedValues:[104]},rubric:"1 point: The student enters 104.",points:1,explanation:"7 × 18 = 126 registered students, and 126 − 22 = 104 attending students."}),
  item({id:42019,testType:"cat",claim:2,domain:"MD",target:"A,D",dok:2,standard:"4.MD.A.2",type:"multi-input",questionText:"A club buys 3 notebooks and 2 folders. Enter the two quantities used, then the total cost in dollars.",dataTable:{columns:["Price"],rows:[{label:"Pencil pack",values:["$3"]},{label:"Notebook",values:["$4"]},{label:"Folder",values:["$2"]}]},responseFields:[{label:"Notebooks"},{label:"Folders"},{label:"Total cost ($)"}],correctAnswer:["3","2","16"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: The student enters 3, 2, and 16 in order.",points:1,explanation:"Three notebooks cost $12 and two folders cost $4, for a total of $16."}),
  item({id:42020,testType:"cat",claim:2,domain:"NBT",target:"A,C",dok:3,standard:"4.NBT.B.5",type:"multi-input",questionText:"A student uses partial products for 46 × 23. The student writes 800 + 120 + 120 + 12. The last partial product is incorrect.\n\nField 1: Enter the corrected last partial product.\nField 2: Enter the corrected final product.",responseFields:[{label:"Corrected partial product"},{label:"Corrected final product"}],correctAnswer:["18","1058"],scoringRule:{kind:"partial-credit",tiers:[{points:2,constraint:{kind:"all",constraints:[{kind:"field-equals",index:0,value:"18"},{kind:"field-equals",index:1,value:"1058"}]}},{points:1,constraint:{kind:"field-equals",index:0,value:"18"}}]},rubric:"2 points: Both 18 and 1,058 are correct. 1 point: The corrected partial product 18 is correct, but the final product is not. 0 points: Otherwise.",points:2,explanation:"The last partial product is 6 × 3 = 18. Then 800 + 120 + 120 + 18 = 1,058."}),
  item({id:42021,testType:"cat",claim:3,domain:"NF",target:"F",dok:2,standard:"4.NF.A.1",type:"two-part",questionText:"Answer both parts about equivalent fractions.",partAPrompt:"Part A: Which fraction is equivalent to 2/3?",partAOptions:fourOptions(["4/9","6/10","8/12","10/18"]),partBPrompt:"Part B: Which statement explains why?",partBOptions:fourOptions(["Add 6 to both 2 and 3.","Multiply both 2 and 3 by 4.","Multiply 2 by 4 and 3 by 3.","Add 2 and 3, then multiply by 2."]),correctAnswer:["C","B"],rubric:"1 point: Both parts are correct.",points:1,explanation:"Multiplying the numerator and denominator of 2/3 by 4 produces 8/12."}),
  item({id:42022,testType:"cat",claim:3,domain:"NF",target:"E,F",dok:2,standard:"4.NF.A.2",type:"multiple-choice",questionText:"Leo says 5/8 is greater than 5/6 because 8 is greater than 6. Which statement best explains Leo's error?",options:fourOptions(["Leo is correct because the larger denominator always makes a larger fraction.","With equal numerators, sixths are larger pieces than eighths, so 5/6 is greater.","The fractions are equal because both numerators are 5.","Both fractions are greater than 1, so they cannot be compared."]),correctAnswer:"B",rubric:"1 point: The student selects B.",points:1,explanation:"When numerators match, the fraction with fewer equal parts has larger parts. Therefore 5/6 > 5/8."}),
  item({id:42023,testType:"cat",claim:3,domain:"OA",target:"A",dok:2,standard:"4.OA.B.4",type:"two-part",questionText:"Use factor pairs to answer both parts.",partAPrompt:"Part A: Is 21 prime or composite?",partAOptions:[{label:"A",text:"prime"},{label:"B",text:"composite"}],partBPrompt:"Part B: Which factor pair proves the answer?",partBOptions:fourOptions(["1 × 20","2 × 11","3 × 7","4 × 6"]),correctAnswer:["B","C"],rubric:"1 point: Both parts are correct.",points:1,explanation:"Because 3 × 7 = 21, the number has factors besides 1 and itself and is composite."}),
  item({id:42024,testType:"cat",claim:3,domain:"G",target:"F",dok:2,standard:"4.G.A.2",type:"grid-match",questionText:"Select exactly two properties that are true for each figure.",stimulusImages:[{src:"/images/grade-4/test-2/math/figure-properties.svg",alt:"Figure A is a rectangle, Figure B is a right triangle, and Figure C is an obtuse triangle.",sha256:"8e039658f167e702c32352a69ad4f8069a22dbccddb4a021d45018aea8c76b34"}],gridRows:["Figure A","Figure B","Figure C"],gridColumns:["Has parallel sides","Has perpendicular sides","Has acute angles","Has an obtuse angle"],gridSelection:{perRowMin:2,perRowMax:2,totalMin:6,totalMax:6},correctAnswer:["0:0","0:1","1:1","1:2","2:2","2:3"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","0:1","1:1","1:2","2:2","2:3"]},rubric:"1 point: All six properties are selected correctly.",points:1,explanation:"The rectangle has parallel and perpendicular sides. The right triangle has perpendicular sides and acute angles. The obtuse triangle has acute and obtuse angles."}),
  item({id:42025,testType:"cat",claim:3,domain:"G",target:"F",dok:2,standard:"4.G.A.3",type:"symmetry-line",questionText:"Select all lines of symmetry for the rectangle. If there are no lines of symmetry, select None.",symmetry:{shapePath:"M80 65 L280 65 L280 165 L80 165 Z",shapeAlt:"A non-square rectangle",choices:[{id:"vertical",label:"Vertical line",path:"M180 30 L180 200"},{id:"horizontal",label:"Horizontal line",path:"M35 115 L325 115"},{id:"diag-up",label:"Diagonal rising line",path:"M60 185 L300 45"},{id:"diag-down",label:"Diagonal falling line",path:"M60 45 L300 185"},{id:"none",label:"None"}],minSelections:2,maxSelections:2,noneChoiceId:"none"},correctAnswer:["vertical","horizontal"],scoringRule:{kind:"unordered-set",acceptedAnswers:["vertical","horizontal"]},rubric:"1 point: The vertical and horizontal lines are selected.",points:1,explanation:"A non-square rectangle has one vertical and one horizontal line of symmetry, but neither diagonal is a line of symmetry."}),
  item({id:42026,testType:"cat",claim:3,domain:"NBT",target:"B,E",dok:3,standard:"4.NBT.B.6",type:"two-part",questionText:"A student finds 728 ÷ 7 by writing 700 ÷ 7 = 100 and 28 ÷ 7 = 4.",partAPrompt:"Part A: Is the student's quotient of 104 correct?",partAOptions:[{label:"A",text:"Yes"},{label:"B",text:"No"}],partBPrompt:"Part B: Which statement best explains the reasoning?",partBOptions:fourOptions(["728 can be decomposed into 700 + 28, and both parts can be divided by 7.","The student should subtract 28 from 700 before dividing.","The student used multiplication instead of division.","The two partial quotients should be multiplied, not added."]),correctAnswer:["A","A"],rubric:"1 point: Both parts are correct.",points:1,explanation:"Because 728 = 700 + 28, the partial quotients 100 and 4 may be added to get 104."}),
  item({id:42027,testType:"cat",claim:3,domain:"MD",target:"F",dok:2,standard:"4.MD.C.7",type:"text-input",questionText:"The total measure of angle AOC is 145°. Angle AOB measures 68°. What is the measure of angle BOC?",stimulusImages:[{src:"/images/grade-4/test-2/math/angle-addition.svg",alt:"Adjacent angles AOB and BOC form angle AOC. Angle AOB is 68 degrees and the total is 145 degrees.",sha256:"e62baacda430a386e7c3cb5a0def8476f001c6ce420ffd272de415dcdadc724a"}],correctAnswer:"77",scoringRule:{kind:"numeric-equivalent",acceptedValues:[77]},rubric:"1 point: The student enters 77.",points:1,explanation:"Subtract the known part from the total: 145° − 68° = 77°."}),
  item({id:42028,testType:"cat",claim:3,domain:"OA",target:"B",dok:3,standard:"4.OA.C.5",type:"multi-select",selection:{min:2,max:2},questionText:"A pattern starts at 2 and adds 4 each time: 2, 6, 10, 14, ... A student claims, “Every term is even, and every term is a multiple of 4.” Select one evidence statement and the correct conclusion.",options:[{label:"A",text:"Evidence: 2, 6, 10, and 14 are all even."},{label:"B",text:"Evidence: 6 is not a multiple of 4."},{label:"C",text:"Conclusion: The entire claim is true."},{label:"D",text:"Conclusion: The claim is false because its second part fails."}],correctAnswer:["B","D"],scoringRule:{kind:"unordered-set",acceptedAnswers:["B","D"]},rubric:"1 point: The student selects B and D.",points:1,explanation:"The value 6 is in the pattern but is not a multiple of 4, so the combined claim is false."}),
  item({id:42029,testType:"cat",claim:4,domain:"MD",target:"A,D",dok:2,standard:"4.MD.B.4",type:"line-plot",questionText:"The measured lengths are 1/4, 1/4, 1/2, 3/4, 3/4, 3/4, 1, and 1 inch. Place one X for each measurement.",linePlotLabels:["1/4","1/2","3/4","1"],linePlotMaxDots:3,correctAnswer:["0:1","0:2","1:1","2:1","2:2","2:3","3:1","3:2"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:1","0:2","1:1","2:1","2:2","2:3","3:1","3:2"]},rubric:"1 point: The plot contains counts 2, 1, 3, and 2 at the four labels.",points:1,explanation:"Count each value in the list: two fourths, one half, three three-fourths, and two ones."}),
  item({id:42030,testType:"cat",claim:4,domain:"MD",target:"A,F",dok:2,standard:"4.MD.A.2",type:"grid-match",questionText:"Match each trip quantity to the operation needed to find it.",gridRows:["Total miles for 3 equal 4-mile segments","Miles per day when 20 miles are split equally across 5 days","Combined distance of 12.5 miles and 3.25 miles"],gridColumns:["Addition","Multiplication","Division"],gridSelection:{perRowMin:1,perRowMax:1,totalMin:3,totalMax:3},correctAnswer:["0:1","1:2","2:0"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:1","1:2","2:0"]},rubric:"1 point: All three quantities are matched correctly.",points:1,explanation:"Equal repeated segments use multiplication, equal sharing uses division, and combining two distances uses addition."}),
  item({id:42031,testType:"cat",claim:4,domain:"NF",target:"B,E",dok:3,standard:"4.NF.B.3, 4.MD.A.2",type:"multi-input",questionText:"A path has sections that are 1/2 mile, 3/4 mile, and 1/4 mile long. Enter the matching addition model, the total, and the unit.",responseFields:[{label:"Addition model"},{label:"Total length"},{label:"Unit"}],correctAnswer:["1/2 + 3/4 + 1/4","1 1/2","miles"],scoringRule:{kind:"constraints",constraint:{kind:"all",constraints:[{kind:"field-one-of",index:0,values:["1/2 + 3/4 + 1/4","3/4 + 1/4 + 1/2","1/4 + 1/2 + 3/4"]},{kind:"field-one-of",index:1,values:["1 1/2","1.5","3/2","1½"]},{kind:"field-one-of",index:2,values:["mile","miles","mi"]}]}},rubric:"1 point: A correct model, equivalent total, and unit are entered.",points:1,explanation:"3/4 + 1/4 makes 1 mile, and another 1/2 mile makes 1 1/2 miles."}),
];

const routeDirections = `Use the Neighborhood Walking Routes map and table for all five tasks.

Segment A connects the Library and Park and is 450 meters long.
Segment B connects the Park and Museum and is 600 meters long. It passes the orange Rest Point.
Segment C connects the Museum and Library and is 750 meters long.

Walkers may travel a segment more than once. A route model lists how many times each segment is traveled.`;

const routeTable = {columns:["Distance","Important feature"],rows:[{label:"Segment A: Library–Park",values:["450 m","No rest point"]},{label:"Segment B: Park–Museum",values:["600 m","Passes Rest Point"]},{label:"Segment C: Museum–Library",values:["750 m","No rest point"]}]};
const routeImage = [{src:"/images/grade-4/test-2/math/walking-routes.svg",alt:"Triangular route map: Segment A is 450 meters, Segment B is 600 meters and passes a rest point, and Segment C is 750 meters.",sha256:"b26d3db0fa2a03d41bfef3a3c92ae71d7042bb52337b77eb5f0267b49f793de2"}];

export const grade4Test2MathPt: Question[] = [
  item({id:42101,testType:"pt",claim:2,domain:"OA",target:"A",dok:2,standard:"4.OA.A.3",type:"text-input",studentDirections:routeDirections,dataTable:routeTable,stimulusImages:routeImage,questionText:"A walking group travels Segment A four times. What total distance, in meters, does the group travel?",correctAnswer:"1800",scoringRule:{kind:"numeric-equivalent",acceptedValues:[1800]},rubric:"1 point: The student enters 1,800 meters.",points:1,explanation:"Four trips of 450 meters total 4 × 450 = 1,800 meters."}),
  item({id:42102,testType:"pt",claim:2,domain:"NBT",target:"A,C",dok:2,standard:"4.NBT.B.6",type:"text-input",studentDirections:routeDirections,dataTable:routeTable,stimulusImages:routeImage,questionText:"A group plans to walk 3,250 meters by repeating Segment C. It can complete 4 full trips on Segment C. How many meters remain after those 4 full trips?",correctAnswer:"250",scoringRule:{kind:"numeric-equivalent",acceptedValues:[250]},rubric:"1 point: The student enters 250 meters.",points:1,explanation:"Four trips use 4 × 750 = 3,000 meters. The remaining distance is 3,250 − 3,000 = 250 meters."}),
  item({id:42103,testType:"pt",claim:2,domain:"MD",target:"A,D",dok:3,standard:"4.MD.A.1, 4.MD.A.2",type:"multi-input",studentDirections:routeDirections,dataTable:routeTable,stimulusImages:routeImage,questionText:"Segment B is 0.6 kilometer long. Enter its length in meters. Then enter the combined length of Segments A and B in meters.",responseFields:[{label:"Segment B in meters"},{label:"Segments A + B in meters"}],correctAnswer:["600","1050"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: The student enters 600 and 1,050 in order.",points:1,explanation:"0.6 kilometer equals 600 meters. Then 450 + 600 = 1,050 meters."}),
  item({id:42104,testType:"pt",claim:3,domain:"MD",target:"B,E,F",dok:3,standard:"4.OA.A.3, 4.MD.A.2",type:"short-answer",studentDirections:routeDirections,dataTable:routeTable,stimulusImages:routeImage,questionText:"Kai says, “Traveling each segment exactly once makes a 2-kilometer route.” Do you agree or disagree? Use at least two values from the map or table to justify your answer.",correctAnswer:"Disagree. The three segments total 450 + 600 + 750 = 1,800 meters, which is 1.8 kilometers, not 2 kilometers.",scoringRule:{kind:"manual-rubric"},rubric:"2 points: The response disagrees, uses at least two accurate route values, and shows or explains that the total is 1,800 meters (1.8 km), not 2 km. 1 point: The response reaches the correct conclusion and provides one relevant accurate value or a correct total without a complete explanation. 0 points: The response is incorrect, irrelevant, insufficient, or blank.",points:2,explanation:"An exemplar adds 450 + 600 + 750 to get 1,800 meters, then compares 1.8 kilometers with 2 kilometers."}),
  item({id:42105,testType:"pt",claim:4,domain:"MD",target:"A,D,F",dok:4,standard:"4.OA.A.3, 4.MD.A.1, 4.MD.A.2",type:"multi-input",studentDirections:routeDirections,dataTable:routeTable,stimulusImages:routeImage,questionText:"Create a route model that meets every rule.\n\n• The total distance is at least 2,400 meters and at most 2,700 meters.\n• The route uses at least two different segment types.\n• The route travels Segment B at least once so it passes the Rest Point.\n\nEnter nonnegative whole-number counts for Segments A, B, and C.",responseFields:[{label:"Number of Segment A trips"},{label:"Number of Segment B trips"},{label:"Number of Segment C trips"}],correctAnswer:["1","2","1"],scoringRule:{kind:"constraints",constraint:{kind:"all",constraints:[{kind:"field-number",index:0,min:0,integer:true},{kind:"field-number",index:1,min:1,integer:true},{kind:"field-number",index:2,min:0,integer:true},{kind:"linear-comparison",terms:[{index:0,coefficient:450},{index:1,coefficient:600},{index:2,coefficient:750}],operator:">=",value:2400},{kind:"linear-comparison",terms:[{index:0,coefficient:450},{index:1,coefficient:600},{index:2,coefficient:750}],operator:"<=",value:2700},{kind:"any",constraints:[{kind:"all",constraints:[{kind:"field-number",index:0,min:1},{kind:"field-number",index:1,min:1}]},{kind:"all",constraints:[{kind:"field-number",index:0,min:1},{kind:"field-number",index:2,min:1}]},{kind:"all",constraints:[{kind:"field-number",index:1,min:1},{kind:"field-number",index:2,min:1}]}]}]}},rubric:"1 point: The three whole-number counts satisfy the distance range, use at least two segment types, and include Segment B. One example is A=1, B=2, C=1, totaling 2,400 meters.",points:1,explanation:"One valid model is 1 trip on A, 2 on B, and 1 on C: 450 + 1,200 + 750 = 2,400 meters. It uses all three types and passes the Rest Point."}),
];

export const grade4Test2MathBankVersion = BANK_VERSION;
