import type { Question } from "./questions";

const BANK_VERSION = "2026-07-22.1";
type Item = Omit<Question, "grade" | "subject" | "practiceTest" | "provenance">;

function item(value: Item): Question {
  return {...value,grade:4,subject:"math",practiceTest:4,provenance:{sourceId:value.testType==="pt"?"g4-t4-math-pt-food-pantry":`g4-t4-math-cat-${value.id}`,origin:"original",author:"CAASPP Practice Project",license:"Original companion content; all rights reserved for this project.",reviewedAt:"2026-07-22"}};
}
const options=(texts:string[])=>texts.map((text,index)=>({label:"ABCDEF"[index],text}));

export const grade4Test4MathCat: Question[] = [
  item({id:46001,testType:"cat",claim:1,domain:"NBT",target:"D",dok:1,standard:"4.NBT.A.3",type:"text-input",questionText:"Round 648,351 to the nearest ten thousand.",correctAnswer:"650000",acceptedAnswers:["650000","650,000"],scoringRule:{kind:"numeric-equivalent",acceptedValues:[650000]},rubric:"1 point: The student enters 650,000.",points:1,explanation:"The thousands digit is 8, so 648,351 rounds to 650,000."}),
  item({id:46002,testType:"cat",claim:1,domain:"NBT",target:"D",dok:2,standard:"4.NBT.A.2",type:"multiple-choice",questionText:"A number has 5 in the hundred-thousands place, 7 in the thousands place, and 3 in the tens place. It is greater than 507,200 and less than 507,500. Which number could it be?",options:options(["507,134","507,238","507,530","570,238"]),correctAnswer:"B",rubric:"1 point: The student selects 507,238.",points:1,explanation:"507,238 has the named digits and lies between both bounds."}),
  item({id:46003,testType:"cat",claim:1,domain:"NBT",target:"D",dok:2,standard:"4.NBT.A.1",type:"two-part",questionText:"The digit 6 appears in 364,120 and 246,903.",partAPrompt:"Part A: How many times the value of the 6 in 246,903 is the value of the 6 in 364,120?",partAOptions:options(["1/10 as much","the same","10 times as much","100 times as much"]),partBPrompt:"Part B: Which equation supports the answer?",partBOptions:options(["6,000 = 10 × 600","60,000 = 10 × 6,000","600,000 = 10 × 60,000","60,000 = 100 × 600"]),correctAnswer:["C","B"],rubric:"1 point: Both parts are correct.",points:1,explanation:"The values are 60,000 and 6,000, and 60,000 is ten times 6,000."}),
  item({id:46004,testType:"cat",claim:1,domain:"NBT",target:"E",dok:1,standard:"4.NBT.B.4",type:"text-input",questionText:"Find 703,205 − 287,946.",correctAnswer:"415259",acceptedAnswers:["415259","415,259"],scoringRule:{kind:"numeric-equivalent",acceptedValues:[415259]},rubric:"1 point: The student enters 415,259.",points:1,explanation:"Regrouping across place values gives 415,259."}),
  item({id:46005,testType:"cat",claim:1,domain:"NBT",target:"E",dok:2,standard:"4.NBT.B.5",type:"multi-input",questionText:"Complete the area-model partial products for 68 × 34, then enter the product.",responseFields:[{label:"60 × 30"},{label:"60 × 4"},{label:"8 × 30"},{label:"8 × 4"},{label:"Product"}],correctAnswer:["1800","240","240","32","2312"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: All four partial products and 2,312 are correct.",points:1,explanation:"1,800 + 240 + 240 + 32 = 2,312."}),
  item({id:46006,testType:"cat",claim:1,domain:"NBT",target:"E",dok:2,standard:"4.NBT.B.6",type:"two-part",questionText:"A library packs 735 books equally into 7 carts.",partAPrompt:"Part A: How many books go on each cart?",partAOptions:options(["95","105","115","125"]),partBPrompt:"Part B: Which equation verifies the quotient?",partBOptions:options(["7 × 100 + 5 = 705","7 × 105 = 735","735 − 7 = 728","735 ÷ 5 = 147"]),correctAnswer:["B","B"],rubric:"1 point: Both parts are correct.",points:1,explanation:"735 ÷ 7 = 105 because 7 × 105 = 735."}),
  item({id:46007,testType:"cat",claim:1,domain:"OA",target:"A",dok:2,standard:"4.OA.A.3",type:"multiple-choice",questionText:"A shop fills 8 equal cases with 36 jars each and places 17 extra jars on a shelf. Which expression finds the total jars?",options:options(["8 + 36 + 17","8 × (36 + 17)","8 × 36 + 17","36 ÷ 8 + 17"]),correctAnswer:"C",rubric:"1 point: The student selects 8 × 36 + 17.",points:1,explanation:"Multiply for the equal cases, then add the extra jars."}),
  item({id:46008,testType:"cat",claim:1,domain:"OA",target:"B",dok:2,standard:"4.OA.B.4",type:"multi-select",selection:{min:5,max:5},questionText:"Select all five factor pairs of 48.",options:options(["1 and 48","2 and 24","3 and 16","4 and 12","5 and 10","6 and 8"]),correctAnswer:["A","B","C","D","F"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B","C","D","F"]},rubric:"1 point: A, B, C, D, and F only.",points:1,explanation:"Each selected pair has a product of 48."}),
  item({id:46009,testType:"cat",claim:1,domain:"OA",target:"C",dok:2,standard:"4.OA.C.5",type:"grid-match",questionText:"Match each input/output pattern to its rule.",gridRows:["1→9, 2→10, 3→11","1→4, 2→8, 3→12","1→7, 2→12, 3→17","1→3, 2→5, 3→7"],gridColumns:["Add 8","Multiply by 4","Multiply by 5, then add 2","Multiply by 2, then add 1"],gridSelection:{perRowMin:1,perRowMax:1,totalMin:4,totalMax:4},correctAnswer:["0:0","1:1","2:2","3:3"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","1:1","2:2","3:3"]},rubric:"1 point: All four patterns are matched.",points:1,explanation:"Applying each rule gives the displayed outputs."}),
  item({id:46010,testType:"cat",claim:1,domain:"OA",target:"A",dok:2,standard:"4.OA.A.2",type:"multi-select",selection:{min:3,max:3},questionText:"Kira has 4 times as many beads as Luis. Luis has 18 beads. Select the three equations that represent this comparison.",options:options(["4 × 18 = 72","72 ÷ 4 = 18","72 ÷ 18 = 4","18 + 4 = 22","72 − 18 = 4"]),correctAnswer:["A","B","C"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B","C"]},rubric:"1 point: A, B, and C only.",points:1,explanation:"The three equations show the product and both related divisions."}),
  item({id:46011,testType:"cat",claim:1,domain:"NF",target:"F",dok:2,standard:"4.NF.A.2",type:"multiple-choice",questionText:"Use one half as a benchmark. Which fraction comparison is true?",options:options(["3/8 > 1/2","5/12 > 1/2","7/10 > 1/2","4/9 = 1/2"]),correctAnswer:"C",rubric:"1 point: The student selects 7/10 > 1/2.",points:1,explanation:"Seven tenths is greater than five tenths."}),
  item({id:46012,testType:"cat",claim:1,domain:"NF",target:"G",dok:2,standard:"4.NF.B.3c",type:"two-part",questionText:"Find 2 5/8 + 3 7/8.",partAPrompt:"Part A: What is the sum?",partAOptions:options(["5 12/8","6 1/2","6 4/8","7 1/2"]),partBPrompt:"Part B: Which regrouping is used?",partBOptions:options(["12/8 = 1 4/8","12/8 = 1 2/8","5/8 + 7/8 = 5/16","2 + 3 = 6"]),correctAnswer:["B","A"],rubric:"1 point: Both parts are correct.",points:1,explanation:"5/8 + 7/8 = 12/8 = 1 4/8, so the sum is 6 1/2."}),
  item({id:46013,testType:"cat",claim:1,domain:"NF",target:"G",dok:2,standard:"4.NF.B.4b",type:"text-input",questionText:"Find 6 × 3/8. Enter a fraction or mixed number.",correctAnswer:"18/8",scoringRule:{kind:"numeric-equivalent",acceptedValues:[2.25]},rubric:"1 point: Any value equivalent to 18/8 or 2 1/4.",points:1,explanation:"Six groups of 3/8 make 18/8, or 2 1/4."}),
  item({id:46014,testType:"cat",claim:1,domain:"NF",target:"H",dok:2,standard:"4.NF.C.5",type:"grid-match",questionText:"Match each fraction in tenths to an equivalent fraction in hundredths.",gridRows:["3/10","6/10","9/10"],gridColumns:["90/100","30/100","60/100"],gridSelection:{perRowMin:1,perRowMax:1,totalMin:3,totalMax:3},correctAnswer:["0:1","1:2","2:0"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:1","1:2","2:0"]},rubric:"1 point: All three equivalents are matched.",points:1,explanation:"Multiply each numerator and denominator by 10."}),
  item({id:46015,testType:"cat",claim:1,domain:"NF",target:"H",dok:3,standard:"4.NF.C.7",type:"two-part",questionText:"Noah says 0.47 is greater than 0.5 because 47 is greater than 5.",partAPrompt:"Part A: Is Noah correct?",partAOptions:options(["Yes","No"]),partBPrompt:"Part B: Which statement best explains?",partBOptions:options(["47 hundredths is greater than 5 hundredths.","0.5 equals 0.50, and 47 hundredths is less than 50 hundredths.","Every two-digit decimal is greater than a one-digit decimal.","Tenths and hundredths cannot be compared."]),correctAnswer:["B","B"],rubric:"1 point: Both parts are correct.",points:1,explanation:"Rename 0.5 as 0.50; then 0.47 < 0.50."}),
  item({id:46016,testType:"cat",claim:1,domain:"MD",target:"I",dok:1,standard:"4.MD.A.1",type:"multi-input",questionText:"Complete each conversion.",responseFields:[{label:"5 feet in inches"},{label:"3 pounds in ounces"},{label:"2 hours 15 minutes in minutes"}],correctAnswer:["60","48","135"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: 60, 48, and 135 in order.",points:1,explanation:"Use 12 inches per foot, 16 ounces per pound, and 60 minutes per hour."}),
  item({id:46017,testType:"cat",claim:1,domain:"G",target:"F",dok:2,standard:"4.G.A.2",type:"grid-match",questionText:"Match each figure description to its most specific category.",gridRows:["Four right angles and four equal sides","Exactly one pair of parallel sides","Three sides and one right angle"],gridColumns:["Square","Trapezoid","Right triangle"],gridSelection:{perRowMin:1,perRowMax:1,totalMin:3,totalMax:3},correctAnswer:["0:0","1:1","2:2"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","1:1","2:2"]},rubric:"1 point: All descriptions are matched.",points:1,explanation:"The listed properties identify a square, trapezoid, and right triangle."}),
  item({id:46018,testType:"cat",claim:2,domain:"MD",target:"A",dok:2,standard:"4.MD.A.2",type:"multi-input",questionText:"A workshop starts at 11:35 a.m. and ends at 1:20 p.m. Enter the elapsed minutes and how many minutes remain after a 65-minute activity.",responseFields:[{label:"Elapsed minutes"},{label:"Minutes remaining"}],correctAnswer:["105","40"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: 105 and 40 in order.",points:1,explanation:"There are 105 minutes from 11:35 to 1:20; 105 − 65 = 40."}),
  item({id:46019,testType:"cat",claim:2,domain:"NF",target:"A,D",dok:3,standard:"4.NF.B.3d",type:"multi-input",questionText:"Three ribbons are 1 3/4, 2 1/4, and 3/4 yards long. Enter an addition expression and the total length.",responseFields:[{label:"Expression"},{label:"Total (yards)"}],correctAnswer:["1 3/4 + 2 1/4 + 3/4","4 3/4"],scoringRule:{kind:"constraints",constraint:{kind:"all",constraints:[{kind:"field-one-of",index:0,values:["1 3/4 + 2 1/4 + 3/4","2 1/4 + 1 3/4 + 3/4","3/4 + 1 3/4 + 2 1/4"]},{kind:"field-one-of",index:1,values:["4 3/4","4.75","19/4","4¾"]}]}},rubric:"1 point: A valid expression and equivalent total.",points:1,explanation:"The first two lengths total 4 yards; another 3/4 gives 4 3/4."}),
  item({id:46020,testType:"cat",claim:2,domain:"NBT",target:"A,C",dok:3,standard:"4.NBT.B.6",type:"multi-input",questionText:"A student writes 958 ÷ 6 = 158 remainder 10. Enter the corrected quotient and corrected remainder.",responseFields:[{label:"Quotient"},{label:"Remainder"}],correctAnswer:["159","4"],scoringRule:{kind:"partial-credit",tiers:[{points:2,constraint:{kind:"all",constraints:[{kind:"field-equals",index:0,value:"159"},{kind:"field-equals",index:1,value:"4"}]}},{points:1,constraint:{kind:"any",constraints:[{kind:"field-equals",index:0,value:"159"},{kind:"field-equals",index:1,value:"4"}]}}]},rubric:"2 points: 159 R4. 1 point: One correct field. 0 points: Otherwise.",points:2,explanation:"6 × 159 = 954, leaving a remainder of 4."}),
  item({id:46021,testType:"cat",claim:3,domain:"OA",target:"B,E",dok:3,standard:"4.OA.A.3",type:"two-part",questionText:"Two classes collect 6 boxes of 24 cans and 4 boxes of 36 cans.",partAPrompt:"Part A: Do the classes collect the same number of cans?",partAOptions:options(["Yes","No"]),partBPrompt:"Part B: Which equation supports the answer?",partBOptions:options(["6 × 24 = 4 × 36","6 + 24 = 4 + 36","6 × 36 = 4 × 24","24 − 6 = 36 − 4"]),correctAnswer:["A","A"],rubric:"1 point: Both parts are correct.",points:1,explanation:"Both products equal 144."}),
  item({id:46022,testType:"cat",claim:3,domain:"NF",target:"B,E",dok:2,standard:"4.NF.A.1",type:"multi-select",selection:{min:2,max:2},questionText:"Select the two arguments that prove 3/5 = 6/10.",options:options(["Multiply 3 and 5 by 2.","Three fifth-size parts cover the same amount as six tenth-size parts.","Add 3 to both numerator and denominator.","Because 6 is greater than 3."]),correctAnswer:["A","B"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B"]},rubric:"1 point: A and B only.",points:1,explanation:"Scaling both terms and comparing equal-area partitions both prove equivalence."}),
  item({id:46023,testType:"cat",claim:3,domain:"MD",target:"B,E",dok:2,standard:"4.MD.A.3",type:"multiple-choice",questionText:"Rectangle A is 8 by 5. Rectangle B is 10 by 4. They have equal area, but B has a larger perimeter. Which change explains the result?",options:options(["B is longer and narrower.","B has a larger area.","A has no width.","Area and perimeter are always equal."]),correctAnswer:"A",rubric:"1 point: The student selects that B is longer and narrower.",points:1,explanation:"Both areas are 40, while the side-length combinations produce different perimeters."}),
  item({id:46024,testType:"cat",claim:3,domain:"G",target:"B,E",dok:2,standard:"4.G.A.2",type:"grid-match",questionText:"For each description, select every category that must apply.",gridRows:["Four equal sides and four right angles","Four right angles, with opposite sides equal","Four equal sides, but no right angles"],gridColumns:["Quadrilateral","Parallelogram","Rectangle","Rhombus","Square"],gridSelection:{perRowMin:3,perRowMax:5,rowSelections:[{min:5,max:5},{min:3,max:3},{min:3,max:3}],totalMin:11,totalMax:11},correctAnswer:["0:0","0:1","0:2","0:3","0:4","1:0","1:1","1:2","2:0","2:1","2:3"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","0:1","0:2","0:3","0:4","1:0","1:1","1:2","2:0","2:1","2:3"]},rubric:"1 point: All required overlapping categories are selected.",points:1,explanation:"A square belongs to all five groups; a nonsquare rectangle and rhombus each belong to three."}),
  item({id:46025,testType:"cat",claim:3,domain:"G",target:"F",dok:2,standard:"4.G.A.3",type:"symmetry-line",questionText:"Select both lines of symmetry for the nonsquare rectangle.",symmetry:{shapePath:"M65 65 L295 65 L295 185 L65 185 Z",shapeAlt:"A rectangle wider than it is tall",choices:[{id:"vertical",label:"Vertical line",path:"M180 40 L180 210"},{id:"horizontal",label:"Horizontal line",path:"M40 125 L320 125"},{id:"diag-up",label:"Rising diagonal",path:"M65 185 L295 65"},{id:"diag-down",label:"Falling diagonal",path:"M65 65 L295 185"},{id:"none",label:"None"}],minSelections:2,maxSelections:2,noneChoiceId:"none"},correctAnswer:["vertical","horizontal"],scoringRule:{kind:"unordered-set",acceptedAnswers:["vertical","horizontal"]},rubric:"1 point: Vertical and horizontal only.",points:1,explanation:"A nonsquare rectangle maps onto itself across its horizontal and vertical midlines."}),
  item({id:46026,testType:"cat",claim:3,domain:"MD",target:"B,E",dok:3,standard:"4.MD.C.7",type:"two-part",questionText:"A straight angle is split into angles of 64°, 38°, and x°.",partAPrompt:"Part A: What is x?",partAOptions:options(["78°","88°","102°","142°"]),partBPrompt:"Part B: Which equation is valid?",partBOptions:options(["64 + 38 + x = 180","64 + 38 = x","180 + 38 = 64 + x","64 + x = 38"]),correctAnswer:["A","A"],rubric:"1 point: Both parts are correct.",points:1,explanation:"180 − 64 − 38 = 78."}),
  item({id:46027,testType:"cat",claim:3,domain:"NBT",target:"B,E",dok:2,standard:"4.NBT.B.5",type:"multiple-choice",questionText:"For 46 × 23, a student writes partial products 800, 120, 80, and 18. Which correction is needed?",options:options(["800 should be 920.","120 should be 80.","80 should be 120.","18 should be 12."]),correctAnswer:"C",rubric:"1 point: The student selects 80 should be 120.",points:1,explanation:"The tens partial product is 6 × 20 = 120; the other three listed products are correct."}),
  item({id:46028,testType:"cat",claim:3,domain:"MD",target:"B,E",dok:2,standard:"4.MD.B.4",type:"multi-select",selection:{min:2,max:2},questionText:"A line plot has ribbon counts: 1/4 yard—2, 1/2 yard—4, 3/4 yard—3, 1 yard—1. Select two supported conclusions.",options:options(["The most common length is 1/2 yard.","There are 10 ribbons total.","More ribbons are 1 yard than 3/4 yard.","Exactly half the ribbons are 1/4 yard."]),correctAnswer:["A","B"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B"]},rubric:"1 point: A and B only.",points:1,explanation:"The largest count is 4 at 1/2, and 2 + 4 + 3 + 1 = 10."}),
  item({id:46029,testType:"cat",claim:4,domain:"MD",target:"A,D",dok:3,standard:"4.MD.B.4",type:"line-plot",questionText:"Plot the package masses: 1/4, 1/4, 1/2, 1/2, 1/2, 3/4, 1, and 1 pound.",linePlotLabels:["1/4","1/2","3/4","1"],linePlotMaxDots:3,correctAnswer:["0:1","0:2","1:1","1:2","1:3","2:1","3:1","3:2"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:1","0:2","1:1","1:2","1:3","2:1","3:1","3:2"]},rubric:"1 point: Counts 2, 3, 1, and 2.",points:1,explanation:"Place one X for each listed mass."}),
  item({id:46030,testType:"cat",claim:4,domain:"OA",target:"A,D,F",dok:3,standard:"4.OA.A.3",type:"multi-input",questionText:"Choose whole-number counts of small and large boxes. Small boxes hold 6 items; large boxes hold 10. The plan must hold 54–62 items and use at least 2 of each box.",responseFields:[{label:"Small boxes"},{label:"Large boxes"}],correctAnswer:["4","3"],scoringRule:{kind:"constraints",constraint:{kind:"all",constraints:[{kind:"field-number",index:0,min:2,integer:true},{kind:"field-number",index:1,min:2,integer:true},{kind:"linear-comparison",terms:[{index:0,coefficient:6},{index:1,coefficient:10}],operator:">=",value:54},{kind:"linear-comparison",terms:[{index:0,coefficient:6},{index:1,coefficient:10}],operator:"<=",value:62}]}},rubric:"1 point: Any whole-number plan meeting all constraints.",points:1,explanation:"Four small and three large boxes hold 54 items."}),
  item({id:46031,testType:"cat",claim:4,domain:"MD",target:"A,D,F",dok:3,standard:"4.MD.A.2",type:"multi-input",questionText:"A notebook costs $4.75 and each pen costs $1.25. Mina buys 1 notebook and 3 pens with $10. Enter the total cost and change.",responseFields:[{label:"Total cost"},{label:"Change"}],correctAnswer:["8.50","1.50"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: $8.50 and $1.50 in order.",points:1,explanation:"$4.75 + 3($1.25) = $8.50, and $10 − $8.50 = $1.50."}),
];

const pantryDirections=`Use the Community Food Pantry Packing Plan for all five tasks. Volunteers make identical family boxes from three foods. Reserved packages cannot be packed. Each cart may carry at most 180 pounds.`;
const pantryTable={rowHeader:"Food",columns:["Packages available","Packages per family box","Package mass","Required reserve"],rows:[{label:"Rice",values:[96,3,"2 lb",12]},{label:"Beans",values:[78,2,"1 lb",10]},{label:"Oats",values:[65,1,"3 lb",5]}]};
export const grade4Test4MathPt: Question[] = [
  item({id:46101,testType:"pt",claim:2,domain:"OA",target:"A",dok:2,standard:"4.OA.A.3",type:"text-input",studentDirections:pantryDirections,dataTable:pantryTable,questionText:"After the rice reserve is removed, how many complete family boxes can be supplied with rice?",correctAnswer:"28",scoringRule:{kind:"numeric-equivalent",acceptedValues:[28]},rubric:"1 point: The student enters 28.",points:1,explanation:"96 − 12 = 84 packages, and 84 ÷ 3 = 28 boxes."}),
  item({id:46102,testType:"pt",claim:2,domain:"NBT",target:"A",dok:2,standard:"4.NBT.B.5",type:"multi-input",studentDirections:pantryDirections,dataTable:pantryTable,questionText:"For 24 family boxes, enter the bean packages used and the bean packages left before setting aside the reserve.",responseFields:[{label:"Bean packages used"},{label:"Packages left"}],correctAnswer:["48","30"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: 48 and 30 in order.",points:1,explanation:"24 × 2 = 48; 78 − 48 = 30."}),
  item({id:46103,testType:"pt",claim:2,domain:"MD",target:"A,D",dok:3,standard:"4.MD.A.1, 4.MD.A.2",type:"multi-input",studentDirections:pantryDirections,dataTable:pantryTable,questionText:"A cart holds food for 10 complete family boxes. Enter the total mass and how many pounds below the 180-pound limit it is.",responseFields:[{label:"Total pounds"},{label:"Pounds below limit"}],correctAnswer:["110","70"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: 110 and 70 in order.",points:1,explanation:"Each box weighs 3(2) + 2(1) + 1(3) = 11 pounds; ten weigh 110."}),
  item({id:46104,testType:"pt",claim:3,domain:"OA",target:"B,E,F",dok:3,standard:"4.OA.A.3",type:"short-answer",studentDirections:pantryDirections,dataTable:pantryTable,questionText:"A volunteer says, “Ten family boxes use the same number of packages of every food.” Do you agree or disagree? Use at least two values from the table.",correctAnswer:"Disagree. Ten boxes use 30 rice packages, 20 bean packages, and 10 oat packages, so the package totals are not equal.",scoringRule:{kind:"manual-rubric"},rubric:"2 points: Disagrees and accurately compares at least two package totals for ten boxes. 1 point: Correct conclusion with one accurate relevant calculation. 0 points: Incorrect, irrelevant, insufficient, or blank.",points:2,explanation:"The per-box counts differ, so ten boxes use 30 rice, 20 bean, and 10 oat packages."}),
  item({id:46105,testType:"pt",claim:4,domain:"OA",target:"A,D,F",dok:4,standard:"4.OA.A.3",type:"multi-input",studentDirections:pantryDirections,dataTable:pantryTable,questionText:"Create a whole-number packing plan for one cart. Enter family boxes, extra bean packages, and extra oat packages. The plan must make 12–16 complete family boxes, keep every reserve, include at least 2 extra packages of both beans and oats, and weigh no more than 180 pounds.",responseFields:[{label:"Family boxes"},{label:"Extra bean packages"},{label:"Extra oat packages"}],correctAnswer:["12","2","2"],scoringRule:{kind:"constraints",constraint:{kind:"all",constraints:[{kind:"field-number",index:0,min:12,max:16,integer:true},{kind:"field-number",index:1,min:2,integer:true},{kind:"field-number",index:2,min:2,integer:true},{kind:"linear-comparison",terms:[{index:0,coefficient:3}],operator:"<=",value:84},{kind:"linear-comparison",terms:[{index:0,coefficient:2},{index:1,coefficient:1}],operator:"<=",value:68},{kind:"linear-comparison",terms:[{index:0,coefficient:1},{index:2,coefficient:1}],operator:"<=",value:60},{kind:"linear-comparison",terms:[{index:0,coefficient:11},{index:1,coefficient:1},{index:2,coefficient:3}],operator:"<=",value:180}]}},rubric:"1 point: Any integer plan meeting the box range, reserves, extra-food minimums, availability, and weight ceiling.",points:1,explanation:"Twelve boxes plus 2 extra bean and 2 extra oat packages use available food and weigh 140 pounds."}),
];

export const grade4Test4MathBankVersion = BANK_VERSION;
