import type { Question } from "./questions";

const BANK_VERSION = "2026-07-22.1";
type Item = Omit<Question, "grade" | "subject" | "practiceTest" | "provenance">;

function item(value: Item): Question {
  return {
    ...value,
    grade: 4,
    subject: "math",
    practiceTest: 3,
    provenance: {
      sourceId: value.testType === "pt" ? "g4-t3-math-pt-theater-seating" : `g4-t3-math-cat-${value.id}`,
      origin: "original",
      author: "CAASPP Practice Project",
      license: "Original companion content; all rights reserved for this project.",
      reviewedAt: "2026-07-22",
    },
  };
}

const options = (texts: string[]) => texts.map((text, index) => ({ label: "ABCDEF"[index], text }));

export const grade4Test3MathCat: Question[] = [
  item({id:44001,testType:"cat",claim:1,domain:"NBT",target:"D",dok:1,standard:"4.NBT.A.3",type:"text-input",questionText:"Round 286,472 to the nearest thousand.",correctAnswer:"286000",acceptedAnswers:["286000","286,000"],rubric:"1 point: The student enters 286,000.",points:1,explanation:"The hundreds digit is 4, so the thousands digit stays 6."}),
  item({id:44002,testType:"cat",claim:1,domain:"NBT",target:"D",dok:1,standard:"4.NBT.A.2",type:"multiple-choice",questionText:"Which comparison between 517,090 and 517,900 is true?",options:options(["517,090 > 517,900","517,090 < 517,900","517,090 = 517,900","517,090 is 9,000 greater than 517,900"]),correctAnswer:"B",rubric:"1 point: The student selects B.",points:1,explanation:"The numbers match through the thousands place, and 0 hundreds is less than 9 hundreds."}),
  item({id:44003,testType:"cat",claim:1,domain:"NBT",target:"D",dok:1,standard:"4.NBT.A.1",type:"text-input",questionText:"What is the value of the digit 7 in 372,615?",correctAnswer:"70000",acceptedAnswers:["70000","70,000"],rubric:"1 point: The student enters 70,000.",points:1,explanation:"The 7 is in the ten-thousands place, so its value is 70,000."}),
  item({id:44004,testType:"cat",claim:1,domain:"NBT",target:"E",dok:1,standard:"4.NBT.B.4",type:"text-input",questionText:"Find the sum.\n\n268,457 + 419,386",correctAnswer:"687843",acceptedAnswers:["687843","687,843"],rubric:"1 point: The student enters 687,843.",points:1,explanation:"Adding by place value with regrouping gives 687,843."}),
  item({id:44005,testType:"cat",claim:1,domain:"NBT",target:"E",dok:2,standard:"4.NBT.B.5",type:"multi-input",questionText:"Use partial products to find 43 × 27. Enter the four partial products in the order shown, then enter their sum.\n\n40 × 20; 40 × 7; 3 × 20; 3 × 7; sum",responseFields:[{label:"40 × 20"},{label:"40 × 7"},{label:"3 × 20"},{label:"3 × 7"},{label:"Sum"}],correctAnswer:["800","280","60","21","1161"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: All four partial products and the sum are correct.",points:1,explanation:"The partial products 800, 280, 60, and 21 total 1,161."}),
  item({id:44006,testType:"cat",claim:1,domain:"OA",target:"A",dok:2,standard:"4.OA.A.3",type:"multiple-choice",questionText:"Seven buses each have 48 seats. A school assigns 319 students to the buses. How many seats remain empty?",options:options(["7","17","29","41"]),correctAnswer:"B",rubric:"1 point: The student selects 17.",points:1,explanation:"Seven buses hold 336 students, and 336 − 319 = 17 seats remain."}),
  item({id:44007,testType:"cat",claim:1,domain:"OA",target:"B",dok:1,standard:"4.OA.B.4",type:"multi-select",selection:{min:5,max:5},questionText:"Select all five factor pairs of 36.",options:options(["1 and 36","2 and 18","3 and 12","4 and 9","5 and 7","6 and 6"]),correctAnswer:["A","B","C","D","F"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B","C","D","F"]},rubric:"1 point: The student selects A, B, C, D, and F only.",points:1,explanation:"Each selected pair has a whole-number product of 36."}),
  item({id:44008,testType:"cat",claim:1,domain:"OA",target:"C",dok:2,standard:"4.OA.C.5",type:"grid-match",questionText:"Match each input/output table to its rule.",gridRows:["Table A: 1→8, 2→9, 3→10","Table B: 1→5, 2→10, 3→15","Table C: 1→6, 2→12, 3→18"],gridColumns:["Add 7","Multiply by 5","Multiply by 6"],gridSelection:{perRowMin:1,perRowMax:1,totalMin:3,totalMax:3},correctAnswer:["0:0","1:1","2:2"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","1:1","2:2"]},rubric:"1 point: All three tables are matched correctly.",points:1,explanation:"Table A adds 7, Table B multiplies by 5, and Table C multiplies by 6."}),
  item({id:44009,testType:"cat",claim:1,domain:"OA",target:"B",dok:2,standard:"4.OA.B.4",type:"multiple-choice",questionText:"What is the least positive number that is a multiple of both 6 and 8?",options:options(["12","18","24","48"]),correctAnswer:"C",rubric:"1 point: The student selects 24.",points:1,explanation:"The multiples first meet at 24: 6 × 4 and 8 × 3."}),
  item({id:44010,testType:"cat",claim:1,domain:"OA",target:"A",dok:2,standard:"4.OA.A.1",type:"multi-select",selection:{min:3,max:3},questionText:"Select the three expressions equal to 63.",options:options(["60 + 3","9 × 7","8 × 8","70 − 7","54 + 8"]),correctAnswer:["A","B","D"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B","D"]},rubric:"1 point: The student selects A, B, and D only.",points:1,explanation:"60 + 3, 9 × 7, and 70 − 7 each equal 63."}),
  item({id:44011,testType:"cat",claim:1,domain:"NF",target:"H",dok:1,standard:"4.NF.C.6",type:"text-input",questionText:"Write seven tenths as a fraction.",correctAnswer:"7/10",scoringRule:{kind:"numeric-equivalent",acceptedValues:[0.7]},rubric:"1 point: The student enters a fraction equivalent to 7/10.",points:1,explanation:"Seven tenths is 7/10."}),
  item({id:44012,testType:"cat",claim:1,domain:"NF",target:"G",dok:2,standard:"4.NF.B.3c",type:"two-part",questionText:"Answer both parts about subtracting 5 4/6 − 2 1/6.",partAPrompt:"Part A: What is the difference?",partAOptions:options(["2 3/6","3 1/6","3 3/6","7 5/6"]),partBPrompt:"Part B: Which equation supports the answer?",partBOptions:options(["(5 − 2) + (4/6 − 1/6) = 3 3/6","(5 − 2) + (4/6 + 1/6) = 3 5/6","(5 + 2) − (4/6 − 1/6) = 6 3/6","(5 − 2) + (4 − 1)/12 = 3 3/12"]),correctAnswer:["C","A"],rubric:"1 point: Both parts are correct.",points:1,explanation:"Subtract the whole numbers and like fractions to get 3 3/6."}),
  item({id:44013,testType:"cat",claim:1,domain:"NF",target:"G",dok:2,standard:"4.NF.B.3a",type:"text-input",questionText:"What is 3/4 + 4/4?",correctAnswer:"7/4",scoringRule:{kind:"numeric-equivalent",acceptedValues:[1.75]},rubric:"1 point: The student enters a value equivalent to 7/4 or 1 3/4.",points:1,explanation:"Add the numerators: 3/4 + 4/4 = 7/4 = 1 3/4."}),
  item({id:44014,testType:"cat",claim:1,domain:"NF",target:"H",dok:1,standard:"4.NF.C.6",type:"text-input",questionText:"A hundred grid has 62 of its 100 squares shaded. Write the shaded amount as a decimal.",correctAnswer:"0.62",scoringRule:{kind:"numeric-equivalent",acceptedValues:[0.62]},rubric:"1 point: The student enters 0.62.",points:1,explanation:"Sixty-two hundredths is 0.62."}),
  item({id:44015,testType:"cat",claim:1,domain:"NF",target:"F",dok:2,standard:"4.NF.A.1",type:"grid-match",questionText:"Match each fraction to an equivalent fraction.",gridRows:["2/3","1/4","3/5"],gridColumns:["2/8","4/6","6/10"],gridSelection:{perRowMin:1,perRowMax:1,totalMin:3,totalMax:3},correctAnswer:["0:1","1:0","2:2"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:1","1:0","2:2"]},rubric:"1 point: All three fractions are matched correctly.",points:1,explanation:"Multiply numerator and denominator by 2 in each row."}),
  item({id:44016,testType:"cat",claim:1,domain:"MD",target:"I",dok:2,standard:"4.MD.A.1",type:"table-input",questionText:"Complete the metric conversion row for 7 meters, 3 kilograms, and 5 liters.",dataTable:{rowHeader:"Quantity",columns:["Relationship"],rows:[{label:"Length",values:["1 meter = 100 centimeters"]},{label:"Mass",values:["1 kilogram = 1,000 grams"]},{label:"Capacity",values:["1 liter = 1,000 milliliters"]}]},tableColumns:["7 meters in centimeters","3 kilograms in grams","5 liters in milliliters"],tableRowLabel:"Converted value",correctAnswer:["700","3000","5000"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: All three conversions are correct.",points:1,explanation:"The converted values are 700 cm, 3,000 g, and 5,000 mL."}),
  item({id:44017,testType:"cat",claim:1,domain:"MD",target:"K",dok:2,standard:"4.MD.C.5",type:"multiple-choice",questionText:"How should the 125° angle be classified?",stimulusImages:[{src:"/images/grade-4/test-3/math/angle-125.svg",alt:"Angle ABC measures 125 degrees.",sha256:"3c3d90390c4da31aa53a2c5716fc3f6f86fe17e3d1d09a6d3739f87addee9c9e"}],options:options(["acute","right","obtuse","straight"]),correctAnswer:"C",rubric:"1 point: The student selects obtuse.",points:1,explanation:"125° is greater than 90° and less than 180°, so it is obtuse."}),
  item({id:44018,testType:"cat",claim:2,domain:"MD",target:"F",dok:2,standard:"4.MD.C.7",type:"text-input",questionText:"A right angle is split into a 37° angle and an unknown angle. What is the unknown angle measure?",correctAnswer:"53",scoringRule:{kind:"numeric-equivalent",acceptedValues:[53]},rubric:"1 point: The student enters 53.",points:1,explanation:"A right angle is 90°, and 90 − 37 = 53."}),
  item({id:44019,testType:"cat",claim:2,domain:"MD",target:"A,D",dok:2,standard:"4.MD.A.3",type:"multi-input",questionText:"A rectangle has an area of 48 square centimeters and a length of 8 centimeters. Enter its width and then its perimeter.",responseFields:[{label:"Width (cm)"},{label:"Perimeter (cm)"}],correctAnswer:["6","28"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: The student enters 6 and 28 in order.",points:1,explanation:"48 ÷ 8 = 6, and 2 × (8 + 6) = 28."}),
  item({id:44020,testType:"cat",claim:2,domain:"NBT",target:"A,C",dok:3,standard:"4.NBT.B.5",type:"multi-input",questionText:"A student uses partial products for 57 × 32 and writes 1,500 + 100 + 210 + 12. The last partial product is incorrect. Enter the corrected last partial product and the corrected final product.",responseFields:[{label:"Corrected partial product"},{label:"Corrected final product"}],correctAnswer:["14","1824"],scoringRule:{kind:"partial-credit",tiers:[{points:2,constraint:{kind:"all",constraints:[{kind:"field-equals",index:0,value:"14"},{kind:"field-equals",index:1,value:"1824"}]}},{points:1,constraint:{kind:"field-equals",index:0,value:"14"}}]},rubric:"2 points: Both 14 and 1,824 are correct. 1 point: Only the corrected partial product 14 is correct. 0 points: Otherwise.",points:2,explanation:"7 × 2 = 14, and the four corrected partial products total 1,824."}),
  item({id:44021,testType:"cat",claim:3,domain:"NBT",target:"B,E",dok:3,standard:"4.NBT.B.6",type:"two-part",questionText:"A student says 486 ÷ 6 = 81. Answer both parts about the student's claim.",partAPrompt:"Part A: Is the quotient correct?",partAOptions:options(["Yes","No"]),partBPrompt:"Part B: Which equation best supports the answer?",partBOptions:options(["6 × 80 + 6 = 486","6 × 81 = 496","486 − 6 = 480","480 ÷ 8 = 60"]),correctAnswer:["A","A"],rubric:"1 point: Both parts are correct.",points:1,explanation:"6 × 81 = 6 × 80 + 6 = 486, so the quotient is correct."}),
  item({id:44022,testType:"cat",claim:3,domain:"MD",target:"F",dok:2,standard:"4.MD.A.3",type:"multiple-choice",questionText:"A student covers the entire top of a rectangular floor mat with square tiles. Which measurement is the student finding?",options:options(["area, in square units","perimeter, in units","length, in cubic units","angle, in degrees"]),correctAnswer:"A",rubric:"1 point: The student selects area in square units.",points:1,explanation:"Covering a surface with equal squares measures area."}),
  item({id:44023,testType:"cat",claim:3,domain:"G",target:"F",dok:2,standard:"4.G.A.2",type:"multi-select",selection:{min:2,max:2},questionText:"Which two properties must be true for every rhombus?",options:options(["All four sides have equal length.","Both pairs of opposite sides are parallel.","All four angles are right angles.","It has exactly one pair of parallel sides.","It has no lines of symmetry."]),correctAnswer:["A","B"],scoringRule:{kind:"unordered-set",acceptedAnswers:["A","B"]},rubric:"1 point: The student selects A and B.",points:1,explanation:"A rhombus has four equal sides and two pairs of parallel opposite sides."}),
  item({id:44024,testType:"cat",claim:3,domain:"G",target:"F",dok:2,standard:"4.G.A.2",type:"grid-match",questionText:"Select exactly two properties that are true for each shown figure.",stimulusImages:[{src:"/images/grade-4/test-3/math/figure-properties.svg",alt:"Three labeled geometric figures, A through C, for the property-matching task.",sha256:"efdb9d7125329e616721c5cd052ac7600ead01c01dd5333a5d568a4f2d5176a6"}],gridRows:["Figure A","Figure B","Figure C"],gridColumns:["Has two pairs of parallel sides","Has perpendicular sides","Has three acute angles","Has no right angles"],gridSelection:{perRowMin:2,perRowMax:2,totalMin:6,totalMax:6},correctAnswer:["0:0","0:1","1:2","1:3","2:0","2:3"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","0:1","1:2","1:3","2:0","2:3"]},rubric:"1 point: All six properties are selected correctly.",points:1,explanation:"The square has parallel and perpendicular sides; the acute triangle has three acute angles and no right angles; the shown parallelogram has two parallel pairs and no right angles."}),
  item({id:44025,testType:"cat",claim:3,domain:"G",target:"F",dok:2,standard:"4.G.A.3",type:"symmetry-line",questionText:"Select the line of symmetry for the isosceles triangle. If there is none, select None.",symmetry:{shapePath:"M180 35 L310 200 L50 200 Z",shapeAlt:"An isosceles triangle with its top vertex centered over its base",choices:[{id:"vertical",label:"Vertical line",path:"M180 20 L180 220"},{id:"horizontal",label:"Horizontal line",path:"M25 120 L335 120"},{id:"diag-up",label:"Diagonal rising line",path:"M45 205 L300 45"},{id:"diag-down",label:"Diagonal falling line",path:"M45 45 L300 205"},{id:"none",label:"None"}],minSelections:1,maxSelections:1,noneChoiceId:"none"},correctAnswer:["vertical"],scoringRule:{kind:"unordered-set",acceptedAnswers:["vertical"]},rubric:"1 point: The vertical line is selected.",points:1,explanation:"Only a vertical fold maps the two equal sides and base halves onto each other."}),
  item({id:44026,testType:"cat",claim:3,domain:"MD",target:"K",dok:2,standard:"4.MD.C.5",type:"two-part",questionText:"Answer both parts about an angle measuring 38°.",partAPrompt:"Part A: How is the angle classified?",partAOptions:options(["acute","right","obtuse","straight"]),partBPrompt:"Part B: Which statement explains the classification?",partBOptions:options(["38° is less than 90°.","38° equals 90°.","38° is between 90° and 180°.","38° is greater than 180°."]),correctAnswer:["A","A"],rubric:"1 point: Both parts are correct.",points:1,explanation:"An angle smaller than a 90° right angle is acute."}),
  item({id:44027,testType:"cat",claim:3,domain:"MD",target:"F",dok:2,standard:"4.MD.A.3",type:"text-input",questionText:"A rectangle has a perimeter of 54 centimeters. One side is 11 centimeters. What is the length of the adjacent side?",correctAnswer:"16",scoringRule:{kind:"numeric-equivalent",acceptedValues:[16]},rubric:"1 point: The student enters 16.",points:1,explanation:"The two unknown equal sides total 54 − 22 = 32 centimeters, so each is 16."}),
  item({id:44028,testType:"cat",claim:3,domain:"MD",target:"I",dok:2,standard:"4.MD.A.1",type:"multi-select",selection:{min:2,max:2},questionText:"Select the two reasonable measurement statements.",options:options(["A classroom doorway is about 4 millimeters tall.","A watermelon can have a mass of about 2 kilograms.","A paper clip can be about 3 centimeters long.","A bathtub can hold about 5 milliliters of water."]),correctAnswer:["B","C"],scoringRule:{kind:"unordered-set",acceptedAnswers:["B","C"]},rubric:"1 point: The student selects B and C.",points:1,explanation:"Kilograms are reasonable for a watermelon, and centimeters are reasonable for a paper clip."}),
  item({id:44029,testType:"cat",claim:4,domain:"MD",target:"A,D",dok:2,standard:"4.MD.B.4",type:"line-plot",questionText:"The ribbon lengths are 1/8, 3/8, 3/8, 3/8, 5/8, 5/8, 7/8, and 7/8 yard. Place one X for each measurement.",linePlotLabels:["1/8","3/8","5/8","7/8"],linePlotMaxDots:3,correctAnswer:["0:1","1:1","1:2","1:3","2:1","2:2","3:1","3:2"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:1","1:1","1:2","1:3","2:1","2:2","3:1","3:2"]},rubric:"1 point: The plot contains counts 1, 3, 2, and 2.",points:1,explanation:"Count the number of times each eighth-inch value appears."}),
  item({id:44030,testType:"cat",claim:4,domain:"G",target:"A,F",dok:3,standard:"4.G.A.1",type:"grid-match",questionText:"Match each labeled pair of lines to its relationship.",stimulusImages:[{src:"/images/grade-4/test-3/math/line-pairs.svg",alt:"Three labeled pairs of lines, A through C, for the relationship-matching task.",sha256:"72d46f54ae772cdb65c51158ebcde51b7013445e19aece92a3ba8da1dd0f9438"}],gridRows:["Pair A","Pair B","Pair C"],gridColumns:["Parallel","Perpendicular","Intersecting but not perpendicular"],gridSelection:{perRowMin:1,perRowMax:1,totalMin:3,totalMax:3},correctAnswer:["0:0","1:1","2:2"],scoringRule:{kind:"unordered-set",acceptedAnswers:["0:0","1:1","2:2"]},rubric:"1 point: All three line pairs are matched correctly.",points:1,explanation:"Pair A never meets, Pair B forms a right angle, and Pair C meets without a right angle."}),
  item({id:44031,testType:"cat",claim:4,domain:"NF",target:"B,E",dok:3,standard:"4.NF.B.3, 4.MD.A.2",type:"multi-input",questionText:"A banner uses ribbon pieces that are 3/4 yard, 1 1/4 yards, and 1/2 yard long. Enter a matching addition model, the total, and the unit.",responseFields:[{label:"Addition model"},{label:"Total length"},{label:"Unit"}],correctAnswer:["3/4 + 1 1/4 + 1/2","2 1/2","yards"],scoringRule:{kind:"constraints",constraint:{kind:"all",constraints:[{kind:"field-one-of",index:0,values:["3/4 + 1 1/4 + 1/2","1 1/4 + 3/4 + 1/2","1/2 + 3/4 + 1 1/4"]},{kind:"field-one-of",index:1,values:["2 1/2","2.5","5/2","2½"]},{kind:"field-one-of",index:2,values:["yard","yards","yd"]}]}},rubric:"1 point: A correct addition model, equivalent total, and unit are entered.",points:1,explanation:"3/4 + 1 1/4 = 2, and another 1/2 gives 2 1/2 yards."}),
];

const seatingDirections = `Use the Community Theater Seating Plan for all five tasks.

The Orchestra section has 8 rows with 24 seats in each row.
The Center section has 6 rows with 18 seats in each row.
The Balcony section has 5 rows with 16 seats in each row.

Two aisles remain open between the sections. A seating model lists how many complete rows from each section will be opened.`;
const seatingTable = {rowHeader:"Section",columns:["Rows","Seats per row","Full capacity"],rows:[{label:"Orchestra",values:[8,24,192]},{label:"Center",values:[6,18,108]},{label:"Balcony",values:[5,16,80]}]};
const seatingImage = [{src:"/images/grade-4/test-3/math/theater-seating.svg",alt:"Community theater diagram with Orchestra, Center, and Balcony seating sections separated by aisles.",sha256:"fb3a01ae92f998927940b8812c344f90b2de2288ae483db36b60748a24d6989e"}];

export const grade4Test3MathPt: Question[] = [
  item({id:44101,testType:"pt",claim:2,domain:"OA",target:"A",dok:2,standard:"4.OA.A.3",type:"text-input",studentDirections:seatingDirections,dataTable:seatingTable,stimulusImages:seatingImage,questionText:"How many seats are in the full Center section?",correctAnswer:"108",scoringRule:{kind:"numeric-equivalent",acceptedValues:[108]},rubric:"1 point: The student enters 108.",points:1,explanation:"Six rows of 18 seats make 6 × 18 = 108 seats."}),
  item({id:44102,testType:"pt",claim:2,domain:"OA",target:"A",dok:2,standard:"4.OA.A.3",type:"text-input",studentDirections:seatingDirections,dataTable:seatingTable,stimulusImages:seatingImage,questionText:"What is the theater's total capacity when every listed row is open?",correctAnswer:"380",scoringRule:{kind:"numeric-equivalent",acceptedValues:[380]},rubric:"1 point: The student enters 380.",points:1,explanation:"192 + 108 + 80 = 380 seats."}),
  item({id:44103,testType:"pt",claim:2,domain:"OA",target:"A,C",dok:3,standard:"4.OA.A.3",type:"multi-input",studentDirections:seatingDirections,dataTable:seatingTable,stimulusImages:seatingImage,questionText:"The theater has 250 reserved seats. Enter the full theater capacity and then the number of seats still available.",responseFields:[{label:"Full capacity"},{label:"Seats still available"}],correctAnswer:["380","130"],scoringRule:{kind:"ordered-fields"},rubric:"1 point: The student enters 380 and 130 in order.",points:1,explanation:"The full capacity is 380, and 380 − 250 = 130 seats remain."}),
  item({id:44104,testType:"pt",claim:3,domain:"OA",target:"B,E,F",dok:3,standard:"4.OA.A.3",type:"short-answer",studentDirections:seatingDirections,dataTable:seatingTable,stimulusImages:seatingImage,questionText:"Avery says, “If one complete Balcony row is closed, the theater will still have 370 seats.” Do you agree or disagree? Use at least two values from the plan to justify your answer.",correctAnswer:"Disagree. The full capacity is 380 seats and one Balcony row contains 16 seats, so closing that row leaves 364 seats, not 370.",scoringRule:{kind:"manual-rubric"},rubric:"2 points: The response disagrees, uses at least two accurate values, and shows or explains 380 − 16 = 364. 1 point: The response reaches the correct conclusion with one accurate relevant value or the correct remaining capacity but incomplete explanation. 0 points: The response is incorrect, irrelevant, insufficient, or blank.",points:2,explanation:"The plan gives a full capacity of 380 and 16 seats per Balcony row, so one closed row leaves 364."}),
  item({id:44105,testType:"pt",claim:4,domain:"OA",target:"A,D,F",dok:4,standard:"4.OA.A.3",type:"multi-input",studentDirections:seatingDirections,dataTable:seatingTable,stimulusImages:seatingImage,questionText:"Create a seating model that meets every rule.\n\n• The model opens at least 250 and at most 280 seats.\n• It uses complete rows from at least two different sections.\n• It opens at least one Center row.\n\nEnter nonnegative whole-number counts for Orchestra, Center, and Balcony rows.",responseFields:[{label:"Orchestra rows"},{label:"Center rows"},{label:"Balcony rows"}],correctAnswer:["4","6","4"],scoringRule:{kind:"constraints",constraint:{kind:"all",constraints:[{kind:"field-number",index:0,min:0,max:8,integer:true},{kind:"field-number",index:1,min:1,max:6,integer:true},{kind:"field-number",index:2,min:0,max:5,integer:true},{kind:"linear-comparison",terms:[{index:0,coefficient:24},{index:1,coefficient:18},{index:2,coefficient:16}],operator:">=",value:250},{kind:"linear-comparison",terms:[{index:0,coefficient:24},{index:1,coefficient:18},{index:2,coefficient:16}],operator:"<=",value:280},{kind:"any",constraints:[{kind:"all",constraints:[{kind:"field-number",index:0,min:1},{kind:"field-number",index:1,min:1}]},{kind:"all",constraints:[{kind:"field-number",index:0,min:1},{kind:"field-number",index:2,min:1}]},{kind:"all",constraints:[{kind:"field-number",index:1,min:1},{kind:"field-number",index:2,min:1}]}]}]}},rubric:"1 point: The row counts produce 250–280 seats, use at least two sections, include a Center row, and stay within available rows. One example is 4 Orchestra, 6 Center, and 4 Balcony rows for 268 seats.",points:1,explanation:"4 × 24 + 6 × 18 + 4 × 16 = 268, and the model uses all three sections within their row limits."}),
];

export const grade4Test3MathBankVersion = BANK_VERSION;
