import type { Question } from "./questions";

function makeQuestion(
  id: number,
  data: Omit<Question, "id" | "grade" | "practiceTest">
): Question {
  return {
    id,
    grade: 3,
    practiceTest: 14,
    ...data,
  };
}

const midnightRehearsalPassage = `The school auditorium was supposed to be quiet after dismissal, but on Thursday evening it buzzed like a beehive. Chairs scraped across the floor. Costume boxes thumped shut. Someone tested the stage lights, and narrow beams flashed across the curtains.

Maya tucked a violin folder under her arm and hurried inside. The winter concert was only two nights away, and this was the last full rehearsal. She liked concerts because everything had a place: the music stands in neat rows, the chairs set in a curve, and the notes lined up on the page like tiny instructions. But when she stepped onto the stage, nothing looked neat at all.

"The back riser is wobbling again," said Mr. Baird, the music teacher. He pressed one hand against the metal frame while two fifth graders held the other side. "No one stand on this row until we fix it."

Maya looked at the seating chart clipped to her folder. Her class was supposed to sing from the top row. Without the riser, half the students would be hidden behind the others.

"Can we just move everyone closer together?" asked Eli.

Mr. Baird shook his head. "If we crowd the singers, the audience won't hear the middle voices well. We need a plan, not a squeeze."

Maya studied the stage. The hand chime tables stood near one curtain. The drum sat by the piano. A long bench from the art room leaned against the wall because students had painted scenery on it earlier that week.

"What if the top row stands on the floor behind the chairs?" Maya asked.

"Then the audience in the back might not see them," said Mr. Baird.

Maya thought for a moment. She remembered something from science class about sound bouncing off hard surfaces and getting blocked by people or furniture. She walked to the front row and whispered, "La, la, la," toward the empty hall. The sound seemed to fall straight down.

Then she dragged the art-room bench to the side of the stage. "What if the tall students stand here for the last song, but only after the drummers move their instruments? The bench is low enough to be safe, and the sound won't be stuck behind the chairs."

Mr. Baird frowned the way he did when he was testing an idea in his head. "Show me."

The students rearranged the stage. Drums shifted to the far corner. The chime tables moved closer to the curtain. Four singers stepped onto the bench while the others spread out below.

"Try the chorus," Mr. Baird said.

The first notes rose, and Maya heard them travel farther than before. Instead of a messy blur, the parts fit together. Even the soft middle voices could be heard.

Mr. Baird walked to the back of the auditorium while the students sang again. When the song ended, he lifted both hands. "That is better. Much better."

The room relaxed at once. Students smiled. Someone tapped a rhythm on a music stand. Eli whispered, "You saved rehearsal."

Maya laughed. "I just moved a bench."

"You noticed what the room needed," Mr. Baird said. "That is what musicians do. They listen."

The rehearsal continued. During breaks, students marked their places with sticky notes and practiced tricky lines under their breath. By the time the custodian flicked the hallway lights twice, the stage looked different from the one Maya had seen an hour earlier. It was still crowded, but now every chair, instrument, and singer seemed to belong in exactly the right place.

On concert night, the audience filled the rows from front to back. When the final song began, the singers stepped into their new positions. Maya felt a flutter in her stomach, but it was not fear. It was the feeling of waiting for something carefully built to finally shine. As the last note echoed into the hall, the audience stood up clapping before Mr. Baird could lower his hands.`;

const soundMovesPassage = `A room can change the way sound is heard. When people speak, sing, or play instruments, they make vibrations. Those vibrations travel through the air as sound waves. The waves spread out until they meet something, such as a wall, a curtain, a ceiling, or even a crowd of people.

Hard surfaces, like brick walls or wooden floors, can bounce sound back into a room. This is called reflection. If many sound waves reflect, the room may seem lively and bright. In a gym or a long hallway, reflected sound can make a voice ring or blur. That is why it may be hard to understand words in a very echoey place.

Soft materials absorb more sound. Curtains, rugs, seat cushions, and coats worn by an audience can soak up some of the sound waves instead of sending them back. A room with too much absorption may seem dull because the sound stops quickly.

Designers think carefully about reflection and absorption when they plan a concert hall. They do not want sound to vanish right away, but they also do not want every note to bounce around so long that the next note gets lost. Good acoustics happen when sound is clear, strong, and balanced.

The shape of a room matters, too. A flat back wall may send sound straight back, while angled walls can spread the sound more evenly. A high ceiling may help music feel wide and open. Small changes in where musicians stand can matter as well. If a drummer is placed in front of quiet instruments, the loud beats can cover softer sounds. If singers stand behind tall objects, some of their sound may be blocked before it reaches the audience.

People in the audience also affect sound. Before a concert begins, a rehearsal in an empty hall may sound different from the real performance. Once seats are filled, coats and people absorb more sound. That is one reason performers often test a space more than once.

Learning how sound behaves helps musicians solve problems. They may move a chair, spread out a group, lower a curtain, or change where instruments are placed. These changes may seem small, but each one can help sound travel more clearly from the stage to the audience.

When a performance sounds clear and balanced, listeners can pay attention to the music instead of struggling to hear it. Good acoustics do not happen by accident. They come from careful listening, smart planning, and an understanding of how sound moves through space.`;

const balloonPresentation = `Presentation Notes: "Saving the Midnight Rehearsal"

Speaker 1: Our class visited the school auditorium to learn how students prepare for a concert. We expected to hear music, but first we noticed a problem. One of the back risers was shaky. That meant some singers could not stand where they had practiced.

Speaker 2: The music teacher did not want the students to crowd together. If they stood too close, some voices would be hidden. A student named Maya looked around the room and noticed that the stage had extra furniture and instruments along the sides.

Speaker 1: Maya remembered that sound can get blocked by objects and people. She also knew that where a person stands can change how well the audience hears. She suggested moving the drums to one side and using a low bench for a few singers during the last song.

Speaker 2: The class tested the idea. When they sang again, the middle voices were clearer. The teacher said Maya had done something important: she had listened to the room, not only to the notes.

Speaker 1: This rehearsal showed that a good performance needs more than talent. It also needs careful planning, safe choices, and smart changes when something unexpected happens.`;

const pizzaPresentation = `Presentation Notes: "Rooms That Help Music Travel"

Speaker 1: Have you ever noticed that some rooms make music sound bright while others make it sound soft? That happens because sound waves move differently in different spaces.

Speaker 2: Hard surfaces such as wood and brick bounce sound. Curtains, rugs, and seat cushions absorb more sound. A room that has only hard surfaces may become too echoey. A room with too many soft materials may make music seem weak.

Speaker 1: Designers of concert halls try to create balance. They may angle walls to spread sound, raise ceilings so music feels open, and choose where to place curtains or panels.

Speaker 2: Musicians also help create good acoustics. They may move loud instruments so softer ones can still be heard. They may rehearse in the room more than once because an empty hall sounds different after the audience arrives.

Speaker 1: The best concert spaces do not happen by luck. They are planned so sound can travel clearly from the stage to every listener.`;

const concertSourceOne = `Saving the Concert

When the East Harbor Elementary concert band arrived for its final rehearsal, everyone expected a quick run-through. Instead, the group found a problem. Several folding panels that usually helped sound move across the stage were missing. Without them, the room sounded uneven. The trumpets near the front seemed too loud, while the flutes on the far side were hard to hear.

Band director Ms. Cho asked the students to pause and listen. She reminded them that rehearsals are not only for practicing notes. They are also for studying how the room responds.

One student suggested pulling the piano a few feet back so it would not block the flutes. Another student noticed that stacked chairs near the side curtain were reflecting sound in an odd way. After the chairs were moved and the instruments were spread out more carefully, the music sounded clearer.

By the end of rehearsal, the students understood that performing well requires teamwork. Each person had to notice details, solve problems, and help the entire group sound better.`;

const concertSourceTwo = `Why Acoustics Matter

Acoustics is the way sound behaves in a space. In a concert hall, good acoustics help music reach listeners clearly. If sound reflects too much, notes may echo and blur together. If too much sound is absorbed, music may seem weak and dull.

Architects and sound designers use many tools to improve acoustics. They may place panels on walls, choose soft or hard materials, or design ceilings that help sound spread. They also think about where people and instruments will be during a performance.

Performers depend on these choices. When acoustics are balanced, soft instruments can still be heard, loud instruments do not take over, and listeners in many seats can enjoy the same performance.

Good acoustics matter because they help a performance share its full sound with the audience.`;

const renovationTable = {
  columns: ["Main Floor", "Side Floor", "Wall Panels", "Seat Rows"],
  rows: [
    { label: "Length", values: [12, 5, 4, 9] },
    { label: "Width or Count", values: [8, 3, 6, 8] },
    { label: "Used on Day 1", values: [48, 15, 14, 5] },
  ],
};

const rehearsalScheduleTable = {
  columns: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
  rows: [
    { label: "Choir minutes", values: [35, 40, 45, 50, 60] },
    { label: "Band minutes", values: [30, 35, 45, 55, 60] },
    { label: "Stage crew minutes", values: [20, 25, 30, 40, 50] },
  ],
};

const test14MathCAT: Question[] = [
  makeQuestion(14001, { testType: "cat", subject: "math", claim: 2, domain: "OA", target: "D", dok: 3, standard: "3.OA.D.8", type: "text-input", questionText: "A harbor crew stacks 7 piles of rope. Each pile has 9 coils. Then 16 coils are loaded onto a boat. How many coils are left on the dock?", correctAnswer: "47", rubric: "The student solves a two-step problem correctly.", points: 1, explanation: "7 × 9 = 63 and 63 − 16 = 47." }),
  makeQuestion(14002, { testType: "cat", subject: "math", claim: 3, domain: "OA", target: "F", dok: 3, standard: "3.OA.B.5", type: "multiple-choice", questionText: "Which equation could be used to find 6 × 14 using the distributive property?", options: [{ label: "A", text: "(6 × 10) + (6 × 4)" }, { label: "B", text: "(6 + 10) × 4" }, { label: "C", text: "6 × (14 + 14)" }, { label: "D", text: "(6 × 14) + 6" }], correctAnswer: "A", rubric: "The student identifies a correct distributive expression.", points: 1, explanation: "14 can be broken into 10 + 4." }),
  makeQuestion(14003, { testType: "cat", subject: "math", claim: 1, domain: "OA", target: "B", dok: 2, standard: "3.OA.A.4", type: "text-input", questionText: "What number makes this equation true?\n\n8 × ? = 96", correctAnswer: "12", rubric: "The student enters the missing factor.", points: 1, explanation: "8 × 12 = 96." }),
  makeQuestion(14004, { testType: "cat", subject: "math", claim: 4, domain: "OA", target: "E", dok: 3, standard: "3.OA.A.3", type: "multiple-choice", questionText: "A builder places 4 rows of 12 dock boards on one side and 3 rows of 8 dock boards on the other side. How many boards are placed in all?", options: [{ label: "A", text: "64" }, { label: "B", text: "68" }, { label: "C", text: "72" }, { label: "D", text: "80" }], correctAnswer: "C", rubric: "The student combines two products.", points: 1, explanation: "4 × 12 = 48 and 3 × 8 = 24. The total is 72." }),
  makeQuestion(14005, { testType: "cat", subject: "math", claim: 2, domain: "NBT", target: "E", dok: 3, standard: "3.NBT.A.2", type: "text-input", questionText: "What is 786 + 497?", correctAnswer: "1283", rubric: "The student enters the correct sum.", points: 1, explanation: "786 + 497 = 1,283." }),
  makeQuestion(14006, { testType: "cat", subject: "math", claim: 2, domain: "NBT", target: "E", dok: 3, standard: "3.NBT.A.2", type: "text-input", questionText: "What is 1,004 − 586?", correctAnswer: "418", rubric: "The student enters the correct difference.", points: 1, explanation: "1,004 − 586 = 418." }),
  makeQuestion(14007, { testType: "cat", subject: "math", claim: 1, domain: "NBT", target: "E", dok: 2, standard: "3.NBT.A.1", type: "multiple-choice", questionText: "Which number rounds to 900 when rounded to the nearest hundred?", options: [{ label: "A", text: "848" }, { label: "B", text: "853" }, { label: "C", text: "949" }, { label: "D", text: "951" }], correctAnswer: "B", rubric: "The student chooses the number that rounds to 900.", points: 1, explanation: "853 rounds to 900." }),
  makeQuestion(14008, { testType: "cat", subject: "math", claim: 3, domain: "NF", target: "F", dok: 3, standard: "3.NF.A.3", type: "multiple-choice", questionText: "Which pair of fractions is equivalent?", options: [{ label: "A", text: "2/3 and 4/6" }, { label: "B", text: "3/4 and 5/8" }, { label: "C", text: "1/2 and 3/5" }, { label: "D", text: "4/5 and 5/4" }], correctAnswer: "A", rubric: "The student identifies equivalent fractions.", points: 1, explanation: "4/6 names the same amount as 2/3." }),
  makeQuestion(14009, { testType: "cat", subject: "math", claim: 3, domain: "NF", target: "F", dok: 3, standard: "3.NF.A.3", type: "multiple-choice", questionText: "Which statement is true?", options: [{ label: "A", text: "5/8 is less than 1/2" }, { label: "B", text: "3/6 is greater than 1/2" }, { label: "C", text: "4/8 is equal to 1/2" }, { label: "D", text: "1/3 is greater than 2/3" }], correctAnswer: "C", rubric: "The student chooses the true fraction statement.", points: 1, explanation: "4/8 and 1/2 are equal." }),
  makeQuestion(14010, { testType: "cat", subject: "math", claim: 2, domain: "NF", target: "F", dok: 3, standard: "3.NF.A.2", type: "text-input", questionText: "A number line from 0 to 1 is divided into 10 equal parts. What fraction is at the seventh mark after 0?", correctAnswer: "7/10", rubric: "The student enters the correct fraction.", points: 1, explanation: "The seventh mark in tenths is 7/10." }),
  makeQuestion(14011, { testType: "cat", subject: "math", claim: 2, domain: "MD", target: "G", dok: 3, standard: "3.MD.A.1", type: "multiple-choice", questionText: "A ferry leaves the harbor at 11:45 a.m. and arrives at 1:20 p.m. How long is the trip?", options: [{ label: "A", text: "1 hour 25 minutes" }, { label: "B", text: "1 hour 35 minutes" }, { label: "C", text: "1 hour 45 minutes" }, { label: "D", text: "2 hours 20 minutes" }], correctAnswer: "B", rubric: "The student finds elapsed time.", points: 1, explanation: "From 11:45 to 12:45 is 1 hour, then 35 minutes more." }),
  makeQuestion(14012, { testType: "cat", subject: "math", claim: 4, domain: "MD", target: "H", dok: 3, standard: "3.MD.B.3", type: "multiple-choice", dataTable: rehearsalScheduleTable, questionText: "How many total minutes did the choir rehearse during the week?", options: [{ label: "A", text: "220" }, { label: "B", text: "230" }, { label: "C", text: "240" }, { label: "D", text: "250" }], correctAnswer: "B", rubric: "The student adds data values in one row.", points: 1, explanation: "35 + 40 + 45 + 50 + 60 = 230." }),
  makeQuestion(14013, { testType: "cat", subject: "math", claim: 2, domain: "MD", target: "I", dok: 3, standard: "3.MD.C.7", type: "text-input", questionText: "A storage platform at the harbor is 14 feet long and 6 feet wide. What is its area?", correctAnswer: "84", rubric: "The student enters the correct area.", points: 1, explanation: "14 × 6 = 84." }),
  makeQuestion(14014, { testType: "cat", subject: "math", claim: 2, domain: "MD", target: "J", dok: 3, standard: "3.MD.D.8", type: "text-input", questionText: "A storage platform at the harbor is 14 feet long and 6 feet wide. What is its perimeter?", correctAnswer: "40", rubric: "The student enters the correct perimeter.", points: 1, explanation: "2 × 14 + 2 × 6 = 40." }),
  makeQuestion(14015, { testType: "cat", subject: "math", claim: 4, domain: "MD", target: "I", dok: 4, standard: "3.MD.C.7", type: "multiple-choice", questionText: "A work area is made from a 7-by-4 rectangle and a 5-by-3 rectangle. What is the total area?", options: [{ label: "A", text: "35 square units" }, { label: "B", text: "38 square units" }, { label: "C", text: "43 square units" }, { label: "D", text: "49 square units" }], correctAnswer: "C", rubric: "The student combines the areas of two rectangles.", points: 1, explanation: "7 × 4 = 28 and 5 × 3 = 15. Total area is 43." }),
  makeQuestion(14016, { testType: "cat", subject: "math", claim: 3, domain: "G", target: "K", dok: 3, standard: "3.G.A.1", type: "multiple-choice", questionText: "Which statement is always true?", options: [{ label: "A", text: "Every quadrilateral is a rectangle" }, { label: "B", text: "Every rectangle is a quadrilateral" }, { label: "C", text: "Every triangle has parallel sides" }, { label: "D", text: "Every pentagon has 4 sides" }], correctAnswer: "B", rubric: "The student identifies the always-true statement.", points: 1, explanation: "All rectangles have 4 sides." }),
  makeQuestion(14017, { testType: "cat", subject: "math", claim: 2, domain: "G", target: "K", dok: 3, standard: "3.G.A.2", type: "multiple-choice", questionText: "A banner is divided into 12 equal parts. 5 parts are painted blue. Which fraction of the banner is not blue?", options: [{ label: "A", text: "5/12" }, { label: "B", text: "7/12" }, { label: "C", text: "12/7" }, { label: "D", text: "1/7" }], correctAnswer: "B", rubric: "The student finds the unshaded fraction.", points: 1, explanation: "12 total parts minus 5 blue parts leaves 7 parts." }),
  makeQuestion(14018, { testType: "cat", subject: "math", claim: 4, domain: "OA", target: "E", dok: 4, standard: "3.OA.D.8", type: "multiple-choice", questionText: "A harbor office buys 4 boxes of 18 tickets and 3 boxes of 12 tickets. How many tickets are bought in all?", options: [{ label: "A", text: "96" }, { label: "B", text: "102" }, { label: "C", text: "108" }, { label: "D", text: "120" }], correctAnswer: "C", rubric: "The student combines two products.", points: 1, explanation: "4 × 18 = 72 and 3 × 12 = 36. Total = 108." }),
  makeQuestion(14019, { testType: "cat", subject: "math", claim: 2, domain: "OA", target: "D", dok: 3, standard: "3.OA.D.8", type: "multiple-choice", questionText: "A concert hall has 6 rows of 11 folding chairs. Workers move 28 chairs to the lobby and 17 to a classroom. How many chairs are left in the hall?", options: [{ label: "A", text: "19" }, { label: "B", text: "21" }, { label: "C", text: "26" }, { label: "D", text: "31" }], correctAnswer: "B", rubric: "The student solves a multi-step problem.", points: 1, explanation: "6 × 11 = 66. Then 66 − 28 − 17 = 21." }),
  makeQuestion(14020, { testType: "cat", subject: "math", claim: 1, domain: "NBT", target: "E", dok: 2, standard: "3.NBT.A.3", type: "multiple-choice", questionText: "What is 400 × 2?", options: [{ label: "A", text: "80" }, { label: "B", text: "800" }, { label: "C", text: "8,000" }, { label: "D", text: "402" }], correctAnswer: "B", rubric: "The student selects the correct product.", points: 1, explanation: "4 hundreds times 2 is 8 hundreds." }),
  makeQuestion(14021, { testType: "cat", subject: "math", claim: 2, domain: "OA", target: "A", dok: 3, standard: "3.OA.A.3", type: "text-input", questionText: "A dock has 12 posts in each row. There are 8 rows. How many posts are there in all?", correctAnswer: "96", rubric: "The student enters the correct total.", points: 1, explanation: "12 × 8 = 96." }),
  makeQuestion(14022, { testType: "cat", subject: "math", claim: 3, domain: "OA", target: "E", dok: 4, standard: "3.OA.A.3", type: "multiple-choice", questionText: "Which expression shows 4 shelves with 12 speakers each and 5 shelves with 12 lights each?", options: [{ label: "A", text: "(4 + 5) × 12" }, { label: "B", text: "4 + 5 + 12" }, { label: "C", text: "(12 + 12) × 5" }, { label: "D", text: "4 × 5 × 12" }], correctAnswer: "A", rubric: "The student matches the expression to the situation.", points: 1, explanation: "There are 9 groups of 12." }),
  makeQuestion(14023, { testType: "cat", subject: "math", claim: 2, domain: "NF", target: "F", dok: 3, standard: "3.NF.A.1", type: "multiple-choice", questionText: "A worker finished 9 of 15 sound panels. What fraction of the panels is finished?", options: [{ label: "A", text: "9/15" }, { label: "B", text: "6/15" }, { label: "C", text: "15/9" }, { label: "D", text: "1/9" }], correctAnswer: "A", rubric: "The student identifies the correct fraction.", points: 1, explanation: "9 of 15 equal parts are completed." }),
  makeQuestion(14024, { testType: "cat", subject: "math", claim: 4, domain: "NF", target: "F", dok: 4, standard: "3.NF.A.3", type: "multi-select", questionText: "Select all the fractions that are greater than 1/2.", options: [{ label: "A", text: "3/4" }, { label: "B", text: "4/8" }, { label: "C", text: "5/6" }, { label: "D", text: "2/5" }], correctAnswer: ["A", "C"], rubric: "The student selects all fractions greater than one-half and no others.", points: 1, explanation: "3/4 and 5/6 are greater than 1/2. 4/8 equals 1/2, and 2/5 is less." }),
  makeQuestion(14025, { testType: "cat", subject: "math", claim: 4, domain: "MD", target: "H", dok: 3, standard: "3.MD.B.4", type: "line-plot", questionText: "A team measured cable pieces in feet. Make a line plot that shows pieces with lengths 2, 2, 3, 4, 4, 4, and 5 feet.", linePlotLabels: ["2", "3", "4", "5"], linePlotMaxDots: 4, correctAnswer: ["0:2", "1:1", "2:3", "3:1"], rubric: "The student places the correct number of marks above each length.", points: 1, explanation: "Two pieces are 2 feet, one is 3 feet, three are 4 feet, and one is 5 feet." }),
  makeQuestion(14026, { testType: "cat", subject: "math", claim: 3, domain: "NF", target: "F", dok: 3, standard: "3.NF.A.3", type: "text-input", questionText: "Write a fraction that is greater than 1/4 and less than 3/4.", correctAnswer: "1/2", fractionRange: { greaterThan: "1/4", lessThan: "3/4" }, rubric: "The student enters any fraction in the correct range.", points: 1, explanation: "One possible answer is 1/2." }),
  makeQuestion(14027, { testType: "cat", subject: "math", claim: 4, domain: "G", target: "K", dok: 3, standard: "3.G.A.2", type: "shade-grid", questionText: "Shade 6 of the 12 equal boxes in the grid.", shadeGrid: { rows: 3, cols: 4, requiredCount: 6 }, correctAnswer: ["0:0", "0:1", "0:2", "1:0", "1:1", "1:2"], rubric: "The student shades exactly 6 boxes.", points: 1, explanation: "Any 6 of the 12 equal boxes is correct." }),
  makeQuestion(14028, { testType: "cat", subject: "math", claim: 3, domain: "OA", target: "D", dok: 3, standard: "3.OA.D.8", type: "text-input", questionText: "A stage crew packs 9 boxes with 7 cords in each box. Then 11 cords are used during rehearsal. How many cords remain packed?", correctAnswer: "52", rubric: "The student solves the two-step problem.", points: 1, explanation: "9 × 7 = 63 and 63 − 11 = 52." }),
  makeQuestion(14029, { testType: "cat", subject: "math", claim: 3, domain: "NF", target: "F", dok: 3, standard: "3.NF.A.1", type: "fraction-model", questionText: "Choose a model that shows 3/4.", fractionModel: { thirdsMax: 3, fourthsMax: 4 }, correctAnswer: ["0", "3", ">"], rubric: "The student chooses 0 thirds, 3 fourths, and the correct comparison symbol showing fourths are used.", points: 1, explanation: "Three fourths means 3 of 4 equal parts." }),
  makeQuestion(14030, { testType: "cat", subject: "math", claim: 4, domain: "MD", target: "I", dok: 4, standard: "3.MD.C.7", type: "grid-match", questionText: "Complete the chart to show the area of each rectangle.", gridRows: ["6 by 4 rectangle", "9 by 3 rectangle", "8 by 5 rectangle"], gridColumns: ["24 square units", "27 square units", "40 square units"], correctAnswer: ["0:0", "1:1", "2:2"], rubric: "The student matches each rectangle with its area.", points: 1, explanation: "6 × 4 = 24, 9 × 3 = 27, and 8 × 5 = 40." }),
  makeQuestion(14031, { testType: "cat", subject: "math", claim: 3, domain: "OA", target: "F", dok: 3, standard: "3.OA.B.5", type: "multi-select", questionText: "Select all equations that are true.", options: [{ label: "A", text: "7 × 8 = 56" }, { label: "B", text: "9 × 6 = 45" }, { label: "C", text: "12 × 4 = 48" }, { label: "D", text: "8 × 5 = 48" }], correctAnswer: ["A", "C"], rubric: "The student selects all true equations and no others.", points: 1, explanation: "A and C are true." }),
  makeQuestion(14032, { testType: "cat", subject: "math", claim: 4, domain: "MD", target: "H", dok: 3, standard: "3.MD.B.3", type: "multiple-choice", dataTable: rehearsalScheduleTable, questionText: "On which day did the choir and band rehearse for the same number of minutes?", options: [{ label: "A", text: "Monday" }, { label: "B", text: "Tuesday" }, { label: "C", text: "Wednesday" }, { label: "D", text: "Friday" }], correctAnswer: "C", rubric: "The student compares data from two rows.", points: 1, explanation: "Both groups rehearsed 45 minutes on Wednesday." }),
  makeQuestion(14033, { testType: "cat", subject: "math", claim: 2, domain: "G", target: "K", dok: 2, standard: "3.G.A.1", type: "multiple-choice", questionText: "Which shape has exactly one pair of parallel sides?", options: [{ label: "A", text: "Trapezoid" }, { label: "B", text: "Triangle" }, { label: "C", text: "Circle" }, { label: "D", text: "Pentagon" }], correctAnswer: "A", rubric: "The student identifies the shape property.", points: 1, explanation: "A trapezoid has exactly one pair of parallel sides." }),
  makeQuestion(14034, { testType: "cat", subject: "math", claim: 3, domain: "OA", target: "D", dok: 3, standard: "3.OA.D.9", type: "text-input", questionText: "Complete the pattern: 18, 27, 36, 45, __, __", correctAnswer: "54, 63", rubric: "The student extends the pattern correctly.", points: 1, explanation: "The pattern adds 9 each time." }),
  makeQuestion(14035, { testType: "cat", subject: "math", claim: 4, domain: "OA", target: "D", dok: 4, standard: "3.OA.D.8", type: "short-answer", questionText: "A harbor worker loads 8 crates with 12 lanterns in each crate. Then 19 lanterns are sent to one ship and 27 to another ship. How many lanterns are left? Show your work.", correctAnswer: "There are 8 × 12 = 96 lanterns. Then 19 + 27 = 46 lanterns are sent away. 96 − 46 = 50, so 50 lanterns are left.", rubric: "2 points: correct multiplication, subtraction, and conclusion. 1 point: correct strategy with a small error or incomplete explanation.", points: 2, explanation: "Multiply first, then subtract the lanterns sent away." }),
  makeQuestion(14036, { testType: "cat", subject: "math", claim: 4, domain: "MD", target: "G", dok: 3, standard: "3.MD.A.1", type: "multiple-choice", questionText: "A concert begins at 6:35 p.m. and ends at 8:10 p.m. How long is the concert?", options: [{ label: "A", text: "1 hour 15 minutes" }, { label: "B", text: "1 hour 25 minutes" }, { label: "C", text: "1 hour 35 minutes" }, { label: "D", text: "1 hour 45 minutes" }], correctAnswer: "C", rubric: "The student finds the elapsed time.", points: 1, explanation: "From 6:35 to 7:35 is 1 hour, then 35 more minutes." }),
];

const mathPTDirections = "Use the Concert Hall Renovation table to answer the questions. The main floor is a rectangle, the side floor is a smaller rectangle, wall panels are grouped in equal rows, and seat rows hold the same number of chairs in each row.";

const test14MathPT: Question[] = [
  makeQuestion(14040, { testType: "pt", subject: "math", claim: 2, domain: "MD", target: "I", dok: 3, standard: "3.MD.C.7", type: "multiple-choice", studentDirections: mathPTDirections, dataTable: renovationTable, questionText: "What is the area of the main floor?", options: [{ label: "A", text: "20 square feet" }, { label: "B", text: "48 square feet" }, { label: "C", text: "96 square feet" }, { label: "D", text: "120 square feet" }], correctAnswer: "C", rubric: "The student selects the correct area for the main floor.", points: 1, explanation: "12 × 8 = 96." }),
  makeQuestion(14041, { testType: "pt", subject: "math", claim: 2, domain: "MD", target: "J", dok: 3, standard: "3.MD.D.8", type: "text-input", studentDirections: mathPTDirections, dataTable: renovationTable, questionText: "How many feet of border are needed to go around the side floor?", correctAnswer: "16", rubric: "The student enters the perimeter of the side floor.", points: 1, explanation: "2 × 5 + 2 × 3 = 16." }),
  makeQuestion(14042, { testType: "pt", subject: "math", claim: 4, domain: "OA", target: "D", dok: 3, standard: "3.OA.D.8", type: "text-input", studentDirections: mathPTDirections, dataTable: renovationTable, questionText: "Each seat row holds 8 chairs. There are 9 seat rows. Workers already set up 5 rows on Day 1. Enter the total chairs, the chairs already set up, and the chairs still left to set up, in that order, separated by commas.", correctAnswer: "72,40,32", rubric: "The student enters all three values correctly.", points: 1, explanation: "9 × 8 = 72 chairs total. 5 × 8 = 40 chairs set up. 72 − 40 = 32 chairs left." }),
  makeQuestion(14043, { testType: "pt", subject: "math", claim: 3, domain: "OA", target: "E", dok: 3, standard: "3.OA.A.3", type: "multiple-choice", studentDirections: mathPTDirections, dataTable: renovationTable, questionText: "Which expression shows the total number of wall panels if there are 6 rows with 4 panels in each row?", options: [{ label: "A", text: "6 + 4" }, { label: "B", text: "6 × 4" }, { label: "C", text: "6 × 6" }, { label: "D", text: "4 + 4 + 4" }], correctAnswer: "B", rubric: "The student chooses the expression that matches the equal groups.", points: 1, explanation: "Six rows of four panels means 6 × 4." }),
  makeQuestion(14044, { testType: "pt", subject: "math", claim: 4, domain: "OA", target: "D", dok: 4, standard: "3.OA.D.8", type: "short-answer", studentDirections: mathPTDirections, dataTable: renovationTable, questionText: "Workers used 48 square feet of flooring on the main floor and 15 square feet on the side floor during Day 1. The total finished flooring goal is the whole main floor and whole side floor. How many more square feet of flooring are still needed? Show your work.", correctAnswer: "The main floor is 12 × 8 = 96 square feet and the side floor is 5 × 3 = 15 square feet, so the total goal is 111 square feet. Workers finished 48 + 15 = 63 square feet on Day 1. 111 − 63 = 48, so 48 more square feet are needed.", rubric: "2 points: correct total area, amount completed, and amount left with explanation. 1 point: correct strategy with one minor error or partial explanation.", points: 2, explanation: "Add both floor areas for the goal, add what is finished, then subtract." }),
];

const test14ELACAT: Question[] = [
  makeQuestion(14101, { testType: "cat", subject: "ela", claim: 1, target: "1", dok: 2, standard: "RL.3.1", type: "multiple-choice", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", questionText: "What problem do the students discover at rehearsal?", options: [{ label: "A", text: "The violin music is missing" }, { label: "B", text: "One of the stage risers is shaky" }, { label: "C", text: "The audience arrives too early" }, { label: "D", text: "The curtains will not open" }], correctAnswer: "B", rubric: "The student identifies a key detail from the story.", points: 1, explanation: "Mr. Baird says the back riser is wobbling." }),
  makeQuestion(14102, { testType: "cat", subject: "ela", claim: 1, target: "2", dok: 3, standard: "RL.3.2", type: "multiple-choice", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", questionText: "What is a theme of the story?", options: [{ label: "A", text: "Careful listening can help solve problems" }, { label: "B", text: "Performances are never stressful" }, { label: "C", text: "Students should always work alone" }, { label: "D", text: "Music is less important than science" }], correctAnswer: "A", rubric: "The student identifies a theme.", points: 1, explanation: "Maya solves the problem by listening and observing carefully." }),
  makeQuestion(14103, { testType: "cat", subject: "ela", claim: 1, target: "3", dok: 3, standard: "RL.3.3", type: "multiple-choice", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", questionText: "How do Maya's feelings change from the beginning to the end of the story?", options: [{ label: "A", text: "She is calm at first and confused at the end" }, { label: "B", text: "She is worried at first and proud by the end" }, { label: "C", text: "She is bored at first and angry later" }, { label: "D", text: "She feels exactly the same the whole time" }], correctAnswer: "B", rubric: "The student describes character change.", points: 1, explanation: "Maya first sees a problem and later feels confident that the performance will succeed." }),
  makeQuestion(14104, { testType: "cat", subject: "ela", claim: 1, target: "4", dok: 3, standard: "RL.3.4", type: "multiple-choice", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", questionText: 'What does the phrase "the room relaxed at once" suggest?', options: [{ label: "A", text: "The students fell asleep" }, { label: "B", text: "The new plan made everyone feel less worried" }, { label: "C", text: "The lights became dimmer" }, { label: "D", text: "The chairs were folded away" }], correctAnswer: "B", rubric: "The student interprets figurative language.", points: 1, explanation: "The phrase means everyone felt relief after the new plan worked." }),
  makeQuestion(14105, { testType: "cat", subject: "ela", claim: 1, target: "5", dok: 2, standard: "RL.3.5", type: "multiple-choice", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", questionText: "Which event happens first?", options: [{ label: "A", text: "The audience stands to clap" }, { label: "B", text: "Maya suggests using the art-room bench" }, { label: "C", text: "Mr. Baird walks to the back of the auditorium" }, { label: "D", text: "The students mark their places with sticky notes" }], correctAnswer: "B", rubric: "The student identifies the correct sequence of events.", points: 1, explanation: "Maya suggests using the bench before the group tests the plan." }),
  makeQuestion(14106, { testType: "cat", subject: "ela", claim: 1, target: "6", dok: 3, standard: "RL.3.6", type: "multiple-choice", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", questionText: "What is Mr. Baird's point of view about solving rehearsal problems?", options: [{ label: "A", text: "Problems should be ignored until concert night" }, { label: "B", text: "Students should notice details and test smart ideas" }, { label: "C", text: "Only teachers should move anything on stage" }, { label: "D", text: "The easiest plan is always the best plan" }], correctAnswer: "B", rubric: "The student identifies a character's viewpoint.", points: 1, explanation: "Mr. Baird asks for a plan, then tests Maya's idea carefully." }),
  makeQuestion(14107, { testType: "cat", subject: "ela", claim: 1, target: "1", dok: 2, standard: "RL.3.1", type: "multiple-choice", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", questionText: "Why does Maya whisper toward the empty hall?", options: [{ label: "A", text: "She is practicing a solo" }, { label: "B", text: "She is testing how the room carries sound" }, { label: "C", text: "She is trying not to wake the custodian" }, { label: "D", text: "She wants to scare Eli" }], correctAnswer: "B", rubric: "The student identifies Maya's purpose.", points: 1, explanation: "Maya is checking how sound travels in the room." }),
  makeQuestion(14108, { testType: "cat", subject: "ela", claim: 1, target: "3", dok: 3, standard: "RL.3.3", type: "multiple-choice", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", questionText: "Why is the art-room bench important to the story?", options: [{ label: "A", text: "It becomes part of Maya's solution to the stage problem" }, { label: "B", text: "It is where the audience sits" }, { label: "C", text: "It hides the instruments" }, { label: "D", text: "It holds the sticky notes" }], correctAnswer: "A", rubric: "The student explains the role of an event or object.", points: 1, explanation: "The bench helps the singers be seen and heard better." }),
  makeQuestion(14109, { testType: "cat", subject: "ela", claim: 1, target: "2", dok: 3, standard: "RL.3.2", type: "multiple-choice", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", questionText: "Which detail best supports the idea that Maya is observant?", options: [{ label: "A", text: "She carries a violin folder" }, { label: "B", text: "She remembers a science idea about sound and studies the stage before making a suggestion" }, { label: "C", text: "She arrives after school" }, { label: "D", text: "She feels a flutter in her stomach" }], correctAnswer: "B", rubric: "The student selects the best supporting detail.", points: 1, explanation: "Maya notices details and connects them to what she learned before." }),
  makeQuestion(14110, { testType: "cat", subject: "ela", claim: 1, target: "4", dok: 2, standard: "RL.3.4", type: "two-part", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", partAPrompt: "Part A: What does the word \"buzzed\" mean in the first paragraph?", partAOptions: [{ label: "A", text: "moved slowly" }, { label: "B", text: "was noisy and busy" }, { label: "C", text: "became dark" }, { label: "D", text: "smelled sweet" }], partBPrompt: "Part B: Which detail from the story best helps the reader understand the meaning of \"buzzed\"?", partBOptions: [{ label: "A", text: "Maya tucked a violin folder under her arm" }, { label: "B", text: "The winter concert was only two nights away" }, { label: "C", text: "Chairs scraped across the floor and costume boxes thumped shut" }, { label: "D", text: "The audience filled the rows from front to back" }], questionText: "Answer both parts of the question.", correctAnswer: ["B", "C"], rubric: "The student identifies the meaning of the word and supporting evidence.", points: 1, explanation: "The opening details show the auditorium was loud and full of activity." }),
  makeQuestion(14111, { testType: "cat", subject: "ela", claim: 1, target: "7", dok: 2, standard: "RI.3.1", type: "multiple-choice", passage: soundMovesPassage, passageTitle: "How Sound Moves Through Space", questionText: "What are sound waves made by?", options: [{ label: "A", text: "Reflections" }, { label: "B", text: "Vibrations" }, { label: "C", text: "Curtains" }, { label: "D", text: "Seats" }], correctAnswer: "B", rubric: "The student recalls a detail from the article.", points: 1, explanation: "The article says people and instruments make vibrations that travel as sound waves." }),
  makeQuestion(14112, { testType: "cat", subject: "ela", claim: 1, target: "8", dok: 3, standard: "RI.3.2", type: "multiple-choice", passage: soundMovesPassage, passageTitle: "How Sound Moves Through Space", questionText: "What is the main idea of the article?", options: [{ label: "A", text: "Only loud instruments matter in a concert hall" }, { label: "B", text: "Sound changes depending on the space, and people can plan rooms to help it travel clearly" }, { label: "C", text: "Every room sounds exactly the same" }, { label: "D", text: "Musicians should always perform outdoors" }], correctAnswer: "B", rubric: "The student identifies the main idea.", points: 1, explanation: "The article explains how rooms affect sound and how people plan for that." }),
  makeQuestion(14113, { testType: "cat", subject: "ela", claim: 1, target: "9", dok: 3, standard: "RI.3.3", type: "multiple-choice", passage: soundMovesPassage, passageTitle: "How Sound Moves Through Space", questionText: "Why might an empty concert hall sound different from a full concert hall?", options: [{ label: "A", text: "The lights are brighter when people arrive" }, { label: "B", text: "People and coats absorb more sound" }, { label: "C", text: "The stage becomes smaller" }, { label: "D", text: "The instruments change size" }], correctAnswer: "B", rubric: "The student explains a cause-and-effect relationship from the text.", points: 1, explanation: "The article says audiences absorb sound, changing the room." }),
  makeQuestion(14114, { testType: "cat", subject: "ela", claim: 1, target: "10", dok: 2, standard: "RI.3.4", type: "multiple-choice", passage: soundMovesPassage, passageTitle: "How Sound Moves Through Space", questionText: 'What does the word "absorb" most nearly mean in the article?', options: [{ label: "A", text: "to soak up" }, { label: "B", text: "to shine brightly" }, { label: "C", text: "to move quickly" }, { label: "D", text: "to break apart" }], correctAnswer: "A", rubric: "The student uses context clues to determine word meaning.", points: 1, explanation: "Soft materials soak up sound instead of sending it back." }),
  makeQuestion(14115, { testType: "cat", subject: "ela", claim: 1, target: "11", dok: 2, standard: "RI.3.5", type: "multiple-choice", passage: soundMovesPassage, passageTitle: "How Sound Moves Through Space", questionText: "Why does the author organize the article into short paragraphs with topic sentences?", options: [{ label: "A", text: "To tell a fictional story in order" }, { label: "B", text: "To separate different ideas about how sound behaves" }, { label: "C", text: "To hide the main idea" }, { label: "D", text: "To make the article rhyme" }], correctAnswer: "B", rubric: "The student identifies how text features support understanding.", points: 1, explanation: "Each paragraph explains a different part of acoustics." }),
  makeQuestion(14116, { testType: "cat", subject: "ela", claim: 1, target: "12", dok: 3, standard: "RI.3.6", type: "multiple-choice", passage: soundMovesPassage, passageTitle: "How Sound Moves Through Space", questionText: "What is the author's purpose?", options: [{ label: "A", text: "To entertain readers with a concert story" }, { label: "B", text: "To inform readers about how sound moves in a room" }, { label: "C", text: "To persuade readers to become musicians" }, { label: "D", text: "To compare two different orchestras" }], correctAnswer: "B", rubric: "The student identifies the author's purpose.", points: 1, explanation: "The article explains scientific ideas about sound and rooms." }),
  makeQuestion(14117, { testType: "cat", subject: "ela", claim: 1, target: "7", dok: 2, standard: "RI.3.1", type: "multiple-choice", passage: soundMovesPassage, passageTitle: "How Sound Moves Through Space", questionText: "According to the article, what can angled walls do?", options: [{ label: "A", text: "Spread sound more evenly" }, { label: "B", text: "Stop all echoes" }, { label: "C", text: "Make instruments louder by themselves" }, { label: "D", text: "Keep people from entering" }], correctAnswer: "A", rubric: "The student recalls a supporting detail.", points: 1, explanation: "The article says angled walls can spread sound more evenly." }),
  makeQuestion(14118, { testType: "cat", subject: "ela", claim: 1, target: "8", dok: 3, standard: "RI.3.2", type: "multiple-choice", passage: soundMovesPassage, passageTitle: "How Sound Moves Through Space", questionText: "What is the main idea of the paragraph about hard and soft surfaces?", options: [{ label: "A", text: "Only soft surfaces belong in music rooms" }, { label: "B", text: "Different materials can either reflect sound or absorb it" }, { label: "C", text: "Walls and floors are not important" }, { label: "D", text: "People should always sing in hallways" }], correctAnswer: "B", rubric: "The student identifies the main idea of part of the text.", points: 1, explanation: "The paragraph explains how materials affect sound in different ways." }),
  makeQuestion(14119, { testType: "cat", subject: "ela", claim: 1, target: "9", dok: 3, standard: "RI.3.3", type: "multiple-choice", passage: soundMovesPassage, passageTitle: "How Sound Moves Through Space", questionText: "Why might musicians move loud instruments away from quiet ones?", options: [{ label: "A", text: "So the loud instruments can play faster" }, { label: "B", text: "So softer sounds are not covered up" }, { label: "C", text: "So the audience cannot see them" }, { label: "D", text: "So the stage looks emptier" }], correctAnswer: "B", rubric: "The student explains a relationship described in the article.", points: 1, explanation: "The text says loud instruments can block softer sounds." }),
  makeQuestion(14120, { testType: "cat", subject: "ela", claim: 1, target: "10", dok: 2, standard: "RI.3.4", type: "multiple-choice", passage: soundMovesPassage, passageTitle: "How Sound Moves Through Space", questionText: 'What does the word "balanced" most nearly mean in the last paragraph?', options: [{ label: "A", text: "Even and well matched" }, { label: "B", text: "Standing on one foot" }, { label: "C", text: "Very expensive" }, { label: "D", text: "Quickly finished" }], correctAnswer: "A", rubric: "The student determines word meaning from context.", points: 1, explanation: "Balanced sound is clear and well matched, not too much or too little." }),
  makeQuestion(14121, { testType: "cat", subject: "ela", claim: 2, target: "13", dok: 2, standard: "L.3.1", type: "multiple-choice", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", questionText: "Which sentence uses commas correctly?", options: [{ label: "A", text: "Maya moved the bench, the drums, and the chime tables." }, { label: "B", text: "Maya moved the bench the drums, and the chime tables." }, { label: "C", text: "Maya, moved the bench, the drums and the chime tables." }, { label: "D", text: "Maya moved, the bench the drums, and the chime tables." }], correctAnswer: "A", rubric: "The student identifies correct comma use.", points: 1, explanation: "Choice A uses commas correctly in a series." }),
  makeQuestion(14122, { testType: "cat", subject: "ela", claim: 2, target: "14", dok: 2, standard: "L.3.2", type: "multiple-choice", passage: soundMovesPassage, passageTitle: "How Sound Moves Through Space", questionText: "Which sentence is written correctly?", options: [{ label: "A", text: "Good acoustics help singers, drummers and listeners." }, { label: "B", text: "Good acoustics help singers drummers, and listeners." }, { label: "C", text: "Good acoustics help singers, drummers, and listeners." }, { label: "D", text: "Good acoustics, help singers, drummers and listeners." }], correctAnswer: "C", rubric: "The student identifies correct punctuation.", points: 1, explanation: "Choice C correctly punctuates the series." }),
  makeQuestion(14123, { testType: "cat", subject: "ela", claim: 2, target: "15", dok: 2, standard: "L.3.4", type: "multiple-choice", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", questionText: 'What does the word "curve" mean in the phrase "chairs set in a curve"?', options: [{ label: "A", text: "a straight line" }, { label: "B", text: "a bent shape" }, { label: "C", text: "a loud sound" }, { label: "D", text: "a piece of paper" }], correctAnswer: "B", rubric: "The student determines word meaning from context.", points: 1, explanation: "The chairs are arranged in a bent or rounded shape." }),
  makeQuestion(14124, { testType: "cat", subject: "ela", claim: 2, target: "16", dok: 2, standard: "L.3.5", type: "multiple-choice", passage: soundMovesPassage, passageTitle: "How Sound Moves Through Space", questionText: "Which word is an antonym for \"clear\" as it is used in the article?", options: [{ label: "A", text: "sharp" }, { label: "B", text: "blurry" }, { label: "C", text: "helpful" }, { label: "D", text: "steady" }], correctAnswer: "B", rubric: "The student identifies an antonym.", points: 1, explanation: "Blurry is the opposite of clear in this context." }),
  makeQuestion(14125, { testType: "cat", subject: "ela", claim: 2, target: "17", dok: 2, standard: "L.3.6", type: "multiple-choice", passage: midnightRehearsalPassage, passageTitle: "The Midnight Rehearsal", questionText: "Which word best means the same as \"belong\" in the sentence about the stage?", options: [{ label: "A", text: "fit" }, { label: "B", text: "hide" }, { label: "C", text: "borrow" }, { label: "D", text: "wonder" }], correctAnswer: "A", rubric: "The student identifies a synonym from context.", points: 1, explanation: "Belong means fit in the right place." }),
  makeQuestion(14126, { testType: "cat", subject: "ela", claim: 3, target: "18", dok: 3, standard: "SL.3.2", type: "two-part", passage: balloonPresentation, passageTitle: "Saving the Midnight Rehearsal", partAPrompt: "Part A: What is the most likely reason the speakers gave this presentation?", partAOptions: [{ label: "A", text: "to explain how a rehearsal problem was solved" }, { label: "B", text: "to advertise tickets for a concert" }, { label: "C", text: "to compare two different schools" }, { label: "D", text: "to describe how to build a violin" }], partBPrompt: "Part B: Which detail from the presentation best supports your answer?", partBOptions: [{ label: "A", text: "The winter concert was only two nights away." }, { label: "B", text: "The class tested the idea and the middle voices were clearer." }, { label: "C", text: "Students like concerts because they are exciting." }, { label: "D", text: "The audience arrived at the end of the rehearsal." }], questionText: "Answer both parts of the question.", correctAnswer: ["A", "B"], rubric: "The student identifies the purpose of the presentation and the best supporting detail.", points: 1, explanation: "The presentation mainly explains the rehearsal problem and how Maya's idea solved it." }),
  makeQuestion(14127, { testType: "cat", subject: "ela", claim: 3, target: "19", dok: 3, standard: "SL.3.2", type: "grid-match", passage: balloonPresentation, passageTitle: "Saving the Midnight Rehearsal", questionText: "Complete the chart to show which events happened before or after Maya made her suggestion.", gridRows: ["The class found a shaky riser.", "The drums were moved to the side.", "Mr. Baird said the sound was better.", "Maya remembered a science idea about sound."], gridColumns: ["Before the suggestion", "After the suggestion"], correctAnswer: ["0:0", "1:1", "2:1", "3:0"], rubric: "The student correctly sorts the events by when they happened.", points: 1, explanation: "The problem and Maya's thinking happened first. The changes and teacher response happened later." }),
  makeQuestion(14128, { testType: "cat", subject: "ela", claim: 3, target: "19", dok: 3, standard: "SL.3.2", type: "multiple-choice", passage: pizzaPresentation, passageTitle: "Rooms That Help Music Travel", questionText: "Which idea is explained in the presentation?", options: [{ label: "A", text: "All concert halls should use only curtains" }, { label: "B", text: "Different rooms affect sound in different ways" }, { label: "C", text: "Music sounds best outdoors at night" }, { label: "D", text: "Soft instruments should never rehearse" }], correctAnswer: "B", rubric: "The student identifies a main idea from the presentation.", points: 1, explanation: "The speakers explain that room features change how music sounds." }),
  makeQuestion(14129, { testType: "cat", subject: "ela", claim: 3, target: "20", dok: 3, standard: "W.3.8", type: "multi-select", questionText: "A student is writing a report about concert halls. Which two sources would give the most helpful information about how sound moves in a room?", options: [{ label: "A", text: "A website about famous singers' birthdays" }, { label: "B", text: "A book that explains vibrations, echoes, and sound waves" }, { label: "C", text: "An article about how architects design rooms for music" }, { label: "D", text: "A recipe for snacks sold at concerts" }, { label: "E", text: "A story about a family driving to a recital" }], correctAnswer: ["B", "C"], rubric: "The student selects the two most relevant research sources.", points: 1, explanation: "Sources B and C both directly explain sound and room design." }),
  makeQuestion(14130, { testType: "cat", subject: "ela", claim: 4, target: "21", dok: 4, standard: "RI.3.9", type: "multiple-choice", passage: midnightRehearsalPassage + "\n\n---\n\n" + soundMovesPassage, passageTitle: "The Midnight Rehearsal / How Sound Moves Through Space", questionText: "Which idea is supported by both passages?", options: [{ label: "A", text: "Careful changes in a room can help sound become clearer" }, { label: "B", text: "Concerts are easier in empty rooms" }, { label: "C", text: "Only teachers understand sound" }, { label: "D", text: "All hard surfaces ruin music" }], correctAnswer: "A", rubric: "The student compares ideas across the two texts.", points: 1, explanation: "The story and article both show that smart changes can improve how sound is heard." }),
];

const test14ELAPT: Question[] = [
  makeQuestion(14150, { testType: "pt", subject: "ela", claim: 1, target: "1", dok: 3, standard: "RL.3.1", type: "multiple-choice", passage: concertSourceOne + "\n\n---\n\n" + concertSourceTwo, passageTitle: "Saving the Concert / Why Acoustics Matter", questionText: "Which detail from BOTH sources shows that planning can improve a performance?", options: [{ label: "A", text: "Students moved chairs and instruments more carefully, and designers choose materials and layouts that help sound travel" }, { label: "B", text: "The rehearsal was after school, and acoustics is a science word" }, { label: "C", text: "The trumpets were loud, and some rooms have ceilings" }, { label: "D", text: "The folding panels were missing, and listeners enjoy music" }], correctAnswer: "A", rubric: "The student identifies related evidence from both sources.", points: 1, explanation: "Both sources show that careful planning helps a performance sound better." }),
  makeQuestion(14151, { testType: "pt", subject: "ela", claim: 2, target: "3", dok: 3, standard: "W.3.9", type: "short-answer", passage: concertSourceOne + "\n\n---\n\n" + concertSourceTwo, passageTitle: "Saving the Concert / Why Acoustics Matter", questionText: "Explain one way the students in 'Saving the Concert' and the designers in 'Why Acoustics Matter' are similar. Use details from BOTH sources.", correctAnswer: "Both the students and the designers try to help sound travel clearly. In the story, students move chairs and instruments to make the music easier to hear. In the article, designers choose materials and room shapes so sound can reach listeners clearly.", rubric: "2 points: clear similarity with a detail from each source. 1 point: partial response or only one source used.", points: 2, explanation: "A strong response explains that both groups make choices to improve how sound is heard." }),
  makeQuestion(14152, { testType: "pt", subject: "ela", claim: 2, target: "4", dok: 4, standard: "W.3.2", type: "extended-writing", passage: concertSourceOne + "\n\n---\n\n" + concertSourceTwo, passageTitle: "Saving the Concert / Why Acoustics Matter", studentDirections: "You have read 'Saving the Concert' and 'Why Acoustics Matter.' Write an informational response explaining how preparation and room design can help a performance succeed.\n\nIn your response:\n- State your main idea clearly\n- Use at least one detail from 'Saving the Concert'\n- Use at least one detail from 'Why Acoustics Matter'\n- Explain how the details support your idea\n- Use complete sentences and correct punctuation", questionText: "Write an informational response explaining how preparation and room design can help a performance succeed. Use details from BOTH sources.", correctAnswer: "Responses will vary. See rubric.", rubric: "4 points: clear main idea, relevant details from both sources, organized explanation, and mostly correct conventions. 3 points: uses both sources with some explanation but less development or some errors. 2 points: limited use of one or both sources. 1 point: minimal response. 0 points: off-topic or blank.", points: 4, explanation: "A strong response explains that successful performances need both teamwork in rehearsal and smart acoustic planning in the room." }),
];

export const practiceTest14Questions: Question[] = [
  ...test14MathCAT,
  ...test14MathPT,
  ...test14ELACAT,
  ...test14ELAPT,
];
