import { type Question } from "./questions";

const fossilSchoolyardPassage = `Read the passage and answer the questions.

**The Fossil in the Schoolyard**
*by Lena Morales*

The third-grade class at Ridgeview Elementary was supposed to spend Friday afternoon pulling weeds from the school garden. No one cheered when Mr. Bennett announced the plan.

"It will only take twenty minutes," he said. "Then you can have extra recess."

Nia sighed and picked up a small hand shovel. She liked recess much more than weeding. Still, she followed the class outside and knelt beside the garden fence.

The ground was dry from three sunny days. Nia loosened the dirt around a patch of grass and dropped the weeds into a bucket. A few feet away, her friend Omar was pretending his shovel was a racecar. His row of weeds was still standing straight and green.

"You're not helping much," Nia said.

"I am testing the speed of the shovel," Omar replied.

Nia laughed and reached for another clump of weeds. As she pulled, a hard, flat rock tipped out of the dirt and landed near her shoe. She almost tossed it aside, but something on its surface made her pause.

Thin curved lines crossed the rock in a neat pattern. They looked like the ribs of a leaf, except the lines were pressed into the stone.

"Omar, look at this."

He leaned over. "Maybe somebody drew on it."

"In the dirt?" Nia asked. She brushed the rock with her fingers. The lines stayed. "It looks old."

Mr. Bennett was carrying a wheelbarrow to the compost bin. Nia hurried over and held out the stone.

"Can you tell what this is?" she asked.

Mr. Bennett studied it. His eyebrows lifted. "I can't be sure yet, but this looks interesting."

That was enough to get everyone's attention. Soon the class crowded around. Even Omar stopped racing his shovel.

"Is it treasure?" Mateo asked.

"Maybe not treasure," Mr. Bennett said, smiling, "but it could be evidence."

"Evidence of what?" Nia asked.

"Of something that lived long ago."

The class grew quiet. Mr. Bennett explained that sometimes plants or animals leave marks in mud or soft ground. Over many years, the ground can harden into rock. If the mark remains, it becomes a fossil.

"Like dinosaur bones?" asked Talia.

"Bones can become fossils," Mr. Bennett said. "But so can leaves, shells, footprints, and other traces."

Nia looked down at the stone in her hand. She imagined a leaf falling into soft mud long before the school, the playground, and even the road beside the building had existed.

"What happens now?" Omar asked.

"Now," said Mr. Bennett, "we observe carefully."

He brought out a magnifying lens from the science cabinet and placed the rock on a tray. The students took turns studying it. The lines spread from a center stem and curved outward in a pattern that looked too exact to be random.

"It really does look like a leaf," Nia said.

Mr. Bennett nodded. "I know someone who can help us learn more."

That afternoon, he emailed Dr. Cruz, a scientist from the county museum. On Monday morning, she visited Ridgeview with a box of tools and several sample fossils.

Dr. Cruz showed the class a fish fossil, a shell fossil, and a fossilized fern. Then she placed Nia's rock beside the fern sample.

"Do you notice a similarity?" she asked.

Hands flew into the air.

"They both have the same kind of lines," Nia said.

"And they spread from the middle," Omar added.

Dr. Cruz smiled. "Those details help scientists compare one fossil to another. I cannot say the exact plant yet, but this does appear to be a fossil of a leaf or fern."

The room filled with excited whispers.

"So there used to be ferns in our schoolyard?" Mateo asked.

"Maybe," Dr. Cruz said. "Or this rock may have come from another place many years ago. Fossils help us ask questions about the past. Then we gather evidence to answer them."

Nia liked the sound of that. The rock was not just an object. It was a clue.

Later that week, the class made a small display in the library. They wrote labels, drew pictures, and placed the fossil on blue cloth beneath a sign that read:

**RIDGEVIEW DISCOVERY**

Students from other grades stopped to look. Some guessed it was a feather. Others thought it was a fish fin. Nia enjoyed hearing each idea, but she liked the questions even more.

At the end of the day, Omar stood beside the display and folded his arms. "I guess weeding turned out to be better than recess."

Nia grinned. "Only because we found a reason to look closely."

Mr. Bennett, who had overheard them, nodded. "That is how discovery often begins," he said. "Not with a giant shout, but with someone noticing a small detail."

Nia glanced once more at the fossil before heading home. The schoolyard looked ordinary from far away: swings, garden beds, and a patch of dry ground by the fence. But now she knew ordinary places could hold pieces of very old stories.`;

const fossilsFormPassage = `Read the passage and answer the questions.

**How Fossils Form**
*adapted from educational science sources*

Fossils are clues from long ago. They can show what living things looked like, where they lived, and how Earth has changed over time. Some fossils are parts of plants or animals, and others are marks left behind, such as footprints or leaf prints.

**A Quick Burial**

Many fossils begin to form when a plant or animal is covered quickly by mud, sand, or ash. This covering is important because it helps protect the remains from being broken apart or eaten. The covering material is called sediment.

**Layers Build Up**

Over time, more layers of sediment pile on top. The lower layers are pressed together. As the layers harden into rock, the shape of the plant or animal may stay behind. In some fossils, minerals replace the original material bit by bit. In others, only an impression remains.

**Body Fossils and Trace Fossils**

A body fossil is made from part of a living thing, such as a bone, tooth, shell, or stem. A trace fossil is evidence of an action. Footprints, burrows, and leaf prints are trace fossils because they show what an organism did or where it moved.

**Why Fossils Matter**

Scientists study fossils to learn about ancient environments. A fossil fish might suggest that water once covered an area. A fossil fern may show that a place was once warm and wet enough for those plants to grow. By comparing many fossils and the rock layers around them, scientists can make careful ideas about the past.

**Reading the Rock Layers**

Rock layers also give useful information. In many places, lower layers formed earlier than higher layers. That means a fossil found deep in the ground is often older than one found closer to the surface. Scientists use this pattern, along with other evidence, to understand when different organisms lived.

Fossils do not answer every question by themselves. Scientists must observe closely, compare details, and look for patterns. Even so, fossils remain some of the most helpful clues we have about life on Earth long before people were here to record it.`;

const museumPresentationTranscript = `Read the transcript of the presentation. Then answer the questions.

**A Day at Ridge Museum**
*presentation transcript*

Welcome, visitors, to Ridge Museum's Discovery Week. Today I want to tell you about the museum's newest fossil exhibit and how it was prepared for the public.

Before the exhibit opened, workers planned each step carefully. They cleaned the display cases, tested the lights, and measured the space around each fossil so visitors could walk safely. The museum team also printed maps to help families find the new Fossil Hall.

One part of the opening did not happen as planned. On the morning of the event, a delivery box arrived late because of heavy traffic. The museum staff had to move quickly to place the final fern fossil in its case before the first tour began.

By noon, dozens of students had entered the exhibit. They studied a fossil fish, a shell fossil, and a leaf print found in a nearby ridge. Guides explained that fossils are useful because they give clues about ancient environments. A fish fossil can show that water was once present. A leaf print can help scientists think about the kinds of plants that grew in an area long ago.

At the end of the tour, visitors stopped at a question wall. There they wrote notes about what they had learned and what they still wondered. The museum director said the goal of Discovery Week was not only to show old objects, but also to help young scientists ask new questions.`;

const fossilCluesTranscript = `Read the transcript of the presentation. Then answer the questions.

**Clues in Stone**
*presentation transcript*

Have you ever thought museum stations could help you remember fossil facts? In this presentation, I will compare three fossil clues to three museum stations so you can remember what each one tells us.

At the first station, visitors study a fossil shell. Shell fossils are often connected to places that were covered by water long ago. At the second station, visitors examine a fern print. Plant fossils can help scientists think about what the land and climate were like. At the third station, visitors inspect a set of footprints pressed into stone. Footprint fossils can suggest how an animal moved.

The stations were arranged in a careful order before the presentation began. The shell station was placed near the map table. The fern station was placed beside the climate chart. The footprint station was set near the movement display. Museum helpers also planned to hand out note cards at the start.

One small surprise happened after visitors arrived. A stack of note cards slipped to the floor when a fan blew across the table. A helper picked them up quickly, and the presentation continued.

By the end, most visitors said the stations helped them remember that fossils are more than old objects. They are clues that connect evidence with questions about the past.`;

const ridgeDiscoverySource = `**The Ridge Discovery**
*by Clara Benson*

On a windy Saturday morning, a group of children joined a family hike along Juniper Ridge. Their teacher, Ms. Hall, asked everyone to watch for interesting rocks and plants. She reminded the hikers not to remove anything from the ground without an adult's permission.

Halfway up the trail, Eli noticed a flat stone with a pattern that looked like tiny branches. He showed it to Ms. Hall, who brushed away the dust and studied the lines. She said the pattern might be a fossil plant.

The hikers marked the spot with flags and took photographs. Later, a museum scientist visited the ridge and confirmed that the rock contained a fossilized fern print. She explained that the print formed when a fern pressed into soft mud long ago. Over time, layers of sediment covered the mark, and the sediment hardened into rock.

The scientist also said the fossil mattered because it gave evidence about the ridge's ancient environment. Today Juniper Ridge is dry and rocky, but the fern print suggested the area may once have been wetter and greener.

After the discovery, the children created a poster for the town library. Their poster explained where the fossil was found, how scientists studied it, and why careful observation was important. Many visitors said the poster helped them see the ridge in a new way.`;

const fossilsHelpScientistsSource = `**Why Fossils Help Scientists**
*adapted from science reference materials*

Scientists study fossils because fossils preserve clues about life long ago. A fossil can show the shape of a shell, the pattern of a leaf, or the path an animal took across soft ground.

Scientists do not learn from a fossil by guessing. First, they observe details. Next, they compare the fossil with other fossils and with living plants or animals. They also study the rock layers around the fossil. In many places, deeper rock layers formed earlier than higher layers, so the position of a fossil can help scientists decide how old it may be.

Different fossils can answer different questions. A body fossil, such as a bone or shell, can show what part of an organism looked like. A trace fossil, such as a footprint or burrow, can show movement or behavior. Plant fossils can help scientists think about climate and land conditions from long ago.

When scientists combine fossil evidence with other observations, they can build strong explanations about ancient environments. Fossils do not tell the whole story alone, but they are some of the best clues available about Earth's past.`;

const museumVisitorsTable = {
  columns: ["Room A", "Room B", "Room C", "Room D"],
  rows: [
    { label: "Monday", values: [24, 18, 27, 21] },
    { label: "Tuesday", values: [30, 24, 21, 25] },
    { label: "Wednesday", values: [28, 26, 32, 20] },
  ],
};

const fossilHallTable = {
  columns: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
  rows: [
    { label: "Shell Display", values: [32, 28, 35, 31, 29] },
    { label: "Fern Display", values: [25, 27, 24, 30, 26] },
    { label: "Footprint Display", values: [18, 22, 20, 19, 21] },
  ],
};

const test13MathCAT: Question[] = [
  {
    id: 13001,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "OA",
    target: "A",
    dok: 2,
    standard: "3.OA.A.1",
    type: "text-input",
    questionText: "A museum guide places 6 fossils on each shelf. There are 7 shelves. How many fossils are on the shelves in all?",
    correctAnswer: "42",
    rubric: "The student enters the correct total number of fossils.",
    points: 1,
  },
  {
    id: 13002,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "OA",
    target: "A",
    dok: 2,
    standard: "3.OA.A.3",
    type: "multiple-choice",
    questionText: "Forty museum tickets are shared equally among 5 tour groups. How many tickets does each group get?",
    options: [
      { label: "A", text: "7" },
      { label: "B", text: "8" },
      { label: "C", text: "9" },
      { label: "D", text: "45" },
    ],
    correctAnswer: "B",
    rubric: "The student selects the correct quotient.",
    points: 1,
  },
  {
    id: 13003,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "OA",
    target: "B",
    dok: 1,
    standard: "3.OA.A.4",
    type: "text-input",
    questionText: "What number makes the equation true?\n\n__ × 9 = 54",
    correctAnswer: "6",
    rubric: "The student enters the correct missing factor.",
    points: 1,
  },
  {
    id: 13004,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 3,
    domain: "OA",
    target: "F",
    dok: 2,
    standard: "3.OA.B.5",
    type: "multiple-choice",
    questionText: "Which equation belongs to the same fact family as 8 × 4 = 32?",
    options: [
      { label: "A", text: "32 + 8 = 40" },
      { label: "B", text: "32 ÷ 4 = 8" },
      { label: "C", text: "8 + 4 = 12" },
      { label: "D", text: "32 - 8 = 24" },
    ],
    correctAnswer: "B",
    rubric: "The student identifies a related division equation.",
    points: 1,
  },
  {
    id: 13005,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "OA",
    target: "C",
    dok: 1,
    standard: "3.OA.C.7",
    type: "text-input",
    questionText: "What is 48 ÷ 6?",
    correctAnswer: "8",
    rubric: "The student enters the correct quotient.",
    points: 1,
  },
  {
    id: 13006,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "OA",
    target: "D",
    dok: 2,
    standard: "3.OA.D.8",
    type: "multiple-choice",
    questionText: "A class museum tour has 18 students in the morning and 16 students in the afternoon. The teacher wants 40 students to visit in all. How many more students are needed?",
    options: [
      { label: "A", text: "4" },
      { label: "B", text: "6" },
      { label: "C", text: "14" },
      { label: "D", text: "34" },
    ],
    correctAnswer: "B",
    rubric: "The student solves a two-step problem.",
    points: 1,
  },
  {
    id: 13007,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "NBT",
    target: "E",
    dok: 1,
    standard: "3.NBT.A.1",
    type: "text-input",
    questionText: "Round 267 to the nearest ten.",
    correctAnswer: "270",
    rubric: "The student rounds to the nearest ten correctly.",
    points: 1,
  },
  {
    id: 13008,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "NBT",
    target: "E",
    dok: 1,
    standard: "3.NBT.A.1",
    type: "multiple-choice",
    questionText: "Which number is 483 rounded to the nearest hundred?",
    options: [
      { label: "A", text: "400" },
      { label: "B", text: "450" },
      { label: "C", text: "480" },
      { label: "D", text: "500" },
    ],
    correctAnswer: "A",
    rubric: "The student selects the correct rounded number.",
    points: 1,
  },
  {
    id: 13009,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "NBT",
    target: "E",
    dok: 2,
    standard: "3.NBT.A.2",
    type: "text-input",
    questionText: "What is 278 + 145?",
    correctAnswer: "423",
    rubric: "The student enters the correct sum.",
    points: 1,
  },
  {
    id: 13010,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "NBT",
    target: "C",
    dok: 2,
    standard: "3.NBT.A.2",
    type: "multiple-choice",
    questionText: "The shell display has 361 visitors this month. The fern display has 287 visitors this month. How many more visitors did the shell display have?",
    options: [
      { label: "A", text: "64" },
      { label: "B", text: "74" },
      { label: "C", text: "84" },
      { label: "D", text: "648" },
    ],
    correctAnswer: "B",
    rubric: "The student finds the difference correctly.",
    points: 1,
  },
  {
    id: 13011,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "MD",
    target: "B",
    dok: 2,
    standard: "3.MD.C.5",
    type: "multiple-choice",
    questionText: "A fossil tray is 4 units long and 6 units wide. What is the area of the tray?",
    options: [
      { label: "A", text: "10 square units" },
      { label: "B", text: "20 square units" },
      { label: "C", text: "24 square units" },
      { label: "D", text: "24 units" },
    ],
    correctAnswer: "C",
    rubric: "The student finds the area of a rectangle.",
    points: 1,
  },
  {
    id: 13012,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "MD",
    target: "B",
    dok: 2,
    standard: "3.MD.C.7",
    type: "multi-select",
    questionText: "Select all the statements that are true about a rectangle that is 5 units long and 3 units wide.",
    options: [
      { label: "A", text: "Its area is 15 square units." },
      { label: "B", text: "Its perimeter is 8 units." },
      { label: "C", text: "Its perimeter is 16 units." },
      { label: "D", text: "Its area is 8 square units." },
    ],
    correctAnswer: ["A", "C"],
    rubric: "The student selects both true statements and no incorrect statements.",
    points: 1,
  },
  {
    id: 13013,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "MD",
    target: "B",
    dok: 2,
    standard: "3.MD.D.8",
    type: "text-input",
    questionText: "A museum map is shaped like a rectangle. It is 7 units long and 4 units wide. What is its perimeter?",
    correctAnswer: "22",
    rubric: "The student enters the correct perimeter.",
    points: 1,
  },
  {
    id: 13014,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "NF",
    target: "A",
    dok: 1,
    standard: "3.NF.A.1",
    type: "multiple-choice",
    questionText: "Eight fossil cards are on a table. Three of the cards show plant fossils. What fraction of the cards show plant fossils?",
    options: [
      { label: "A", text: "3/8" },
      { label: "B", text: "5/8" },
      { label: "C", text: "3/5" },
      { label: "D", text: "8/3" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies the correct fraction.",
    points: 1,
  },
  {
    id: 13015,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "NF",
    target: "A",
    dok: 2,
    standard: "3.NF.A.3",
    type: "multi-select",
    questionText: "Select all the fractions that are equal to 1/2.",
    options: [
      { label: "A", text: "2/4" },
      { label: "B", text: "3/6" },
      { label: "C", text: "2/3" },
      { label: "D", text: "4/8" },
    ],
    correctAnswer: ["A", "B", "D"],
    rubric: "The student selects all fractions equivalent to one-half.",
    points: 1,
  },
  {
    id: 13016,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "NF",
    target: "A",
    dok: 2,
    standard: "3.NF.A.2",
    type: "multiple-choice",
    questionText: "A number line from 0 to 1 is divided into 4 equal parts. Which fraction names the point at the third mark after 0?",
    options: [
      { label: "A", text: "1/4" },
      { label: "B", text: "2/4" },
      { label: "C", text: "3/4" },
      { label: "D", text: "4/3" },
    ],
    correctAnswer: "C",
    rubric: "The student identifies the correct fraction on a number line.",
    points: 1,
  },
  {
    id: 13017,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "MD",
    target: "A",
    dok: 2,
    standard: "3.MD.A.1",
    type: "text-input",
    questionText: "A museum tour starts at 10:15 a.m. and ends at 11:00 a.m. How many minutes long is the tour?",
    correctAnswer: "45",
    rubric: "The student enters the correct elapsed time in minutes.",
    points: 1,
  },
  {
    id: 13018,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "MD",
    target: "C",
    dok: 2,
    standard: "3.MD.B.3",
    type: "multiple-choice",
    dataTable: museumVisitorsTable,
    questionText: "On which day did the museum have the greatest total number of visitors in Rooms A, B, C, and D?",
    options: [
      { label: "A", text: "Monday" },
      { label: "B", text: "Tuesday" },
      { label: "C", text: "Wednesday" },
      { label: "D", text: "All three days had the same total" },
    ],
    correctAnswer: "C",
    rubric: "The student identifies the day with the greatest total visitors.",
    points: 1,
  },
  {
    id: 13019,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "MD",
    target: "C",
    dok: 2,
    standard: "3.MD.B.3",
    type: "grid-match",
    questionText: "Complete the chart to match each measurement with the best unit.",
    gridRows: ["Length of a fossil tooth", "Mass of a rock sample", "Amount of water in a cleaning cup"],
    gridColumns: ["centimeters", "grams", "liters"],
    correctAnswer: ["0:0", "1:1", "2:2"],
    rubric: "The student matches each measurement to the appropriate unit.",
    points: 1,
  },
  {
    id: 13020,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 3,
    domain: "OA",
    target: "F",
    dok: 2,
    standard: "3.OA.B.5",
    type: "multiple-choice",
    questionText: "Which equation uses the distributive property to find 6 × 7?",
    options: [
      { label: "A", text: "(6 × 5) + (6 × 2)" },
      { label: "B", text: "6 + 7" },
      { label: "C", text: "7 × 7" },
      { label: "D", text: "42 + 6" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies an expression that uses the distributive property.",
    points: 1,
  },
  {
    id: 13021,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "OA",
    target: "D",
    dok: 2,
    standard: "3.OA.D.9",
    type: "text-input",
    questionText: "Complete the pattern: 125, 135, 145, 155, __, __",
    correctAnswer: "165, 175",
    rubric: "The student enters the next two numbers in the pattern.",
    points: 1,
  },
  {
    id: 13022,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "NBT",
    target: "D",
    dok: 2,
    standard: "3.NBT.A.2",
    type: "multiple-choice",
    questionText: "A student says that 198 + 205 is about 500. Is the estimate reasonable?",
    options: [
      { label: "A", text: "Yes, because 198 + 205 = 500 exactly." },
      { label: "B", text: "Yes, because both numbers round to 250." },
      { label: "C", text: "No, because 198 is about 200 and 205 is about 200, so the sum is about 400." },
      { label: "D", text: "No, because adding always makes 500." },
    ],
    correctAnswer: "C",
    rubric: "The student judges the estimate using rounding.",
    points: 1,
  },
  {
    id: 13023,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 3,
    domain: "OA",
    target: "F",
    dok: 2,
    standard: "3.OA.B.5",
    type: "multi-select",
    questionText: "Select all the equations that are true.",
    options: [
      { label: "A", text: "7 × 5 = 35" },
      { label: "B", text: "54 ÷ 6 = 8" },
      { label: "C", text: "9 × 4 = 36" },
      { label: "D", text: "45 ÷ 9 = 6" },
    ],
    correctAnswer: ["A", "C"],
    rubric: "The student selects all true equations.",
    points: 1,
  },
  {
    id: 13024,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "MD",
    target: "D",
    dok: 2,
    standard: "3.MD.A.2",
    type: "text-input",
    questionText: "A shell fossil has a mass of 145 grams. A rock sample has a mass of 220 grams. What is their total mass in grams?",
    correctAnswer: "365",
    rubric: "The student adds the masses correctly.",
    points: 1,
  },
  {
    id: 13025,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "MD",
    target: "D",
    dok: 2,
    standard: "3.MD.A.2",
    type: "multiple-choice",
    questionText: "A cleaning bucket holds 6 liters of water. Three equal containers are filled from the bucket. How many liters go into each container?",
    options: [
      { label: "A", text: "2 liters" },
      { label: "B", text: "3 liters" },
      { label: "C", text: "9 liters" },
      { label: "D", text: "18 liters" },
    ],
    correctAnswer: "A",
    rubric: "The student divides the total liters equally.",
    points: 1,
  },
  {
    id: 13026,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 3,
    domain: "G",
    target: "A",
    dok: 1,
    standard: "3.G.A.1",
    type: "multiple-choice",
    questionText: "Which shape always has exactly 4 sides?",
    options: [
      { label: "A", text: "Triangle" },
      { label: "B", text: "Quadrilateral" },
      { label: "C", text: "Pentagon" },
      { label: "D", text: "Hexagon" },
    ],
    correctAnswer: "B",
    rubric: "The student identifies the correct shape category.",
    points: 1,
  },
  {
    id: 13027,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 3,
    domain: "G",
    target: "A",
    dok: 2,
    standard: "3.G.A.1",
    type: "multi-select",
    questionText: "Select all the statements that are true about quadrilaterals.",
    options: [
      { label: "A", text: "They have 4 sides." },
      { label: "B", text: "They can have equal sides." },
      { label: "C", text: "They always have 3 right angles." },
      { label: "D", text: "A rectangle is a quadrilateral." },
    ],
    correctAnswer: ["A", "B", "D"],
    rubric: "The student selects all true statements about quadrilaterals.",
    points: 1,
  },
  {
    id: 13028,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "MD",
    target: "B",
    dok: 2,
    standard: "3.MD.C.7",
    type: "text-input",
    questionText: "A fossil sorting mat is 8 units long and 5 units wide. What is the area of the mat in square units?",
    correctAnswer: "40",
    rubric: "The student enters the correct area.",
    points: 1,
  },
  {
    id: 13029,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 4,
    domain: "OA",
    target: "A",
    dok: 3,
    standard: "3.OA.D.8",
    type: "multiple-choice",
    questionText: "A museum guide needs 4 trays. Each tray must hold 9 rock samples. She already placed 11 samples on the trays. How many more samples does she need?",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "36" },
      { label: "C", text: "47" },
      { label: "D", text: "52" },
    ],
    correctAnswer: "A",
    rubric: "The student solves the multistep problem correctly.",
    points: 1,
  },
  {
    id: 13030,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "OA",
    target: "B",
    dok: 2,
    standard: "3.OA.A.4",
    type: "multiple-choice",
    questionText: "Which equation can be used to find the missing number in this problem?\n\nThirty-six visitors are placed into groups of 4. How many groups are there?",
    options: [
      { label: "A", text: "36 + 4 = __" },
      { label: "B", text: "36 - 4 = __" },
      { label: "C", text: "36 ÷ 4 = __" },
      { label: "D", text: "4 ÷ 36 = __" },
    ],
    correctAnswer: "C",
    rubric: "The student identifies the correct equation.",
    points: 1,
  },
  {
    id: 13031,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "MD",
    target: "C",
    dok: 2,
    standard: "3.MD.B.3",
    type: "text-input",
    dataTable: museumVisitorsTable,
    questionText: "How many visitors were in Room C on Monday, Tuesday, and Wednesday in all?",
    correctAnswer: "80",
    rubric: "The student adds the Room C visitors correctly.",
    points: 1,
  },
  {
    id: 13032,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 3,
    domain: "OA",
    target: "F",
    dok: 2,
    standard: "3.OA.B.5",
    type: "multi-select",
    questionText: "A display case has 4 rows with 6 fossils in each row. Select all the expressions that can be used to find the total number of fossils.",
    options: [
      { label: "A", text: "4 × 6" },
      { label: "B", text: "6 + 6 + 6 + 6" },
      { label: "C", text: "4 + 6" },
      { label: "D", text: "24 ÷ 4" },
    ],
    correctAnswer: ["A", "B"],
    rubric: "The student selects expressions that find the total number of fossils.",
    points: 1,
  },
  {
    id: 13033,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "NF",
    target: "A",
    dok: 2,
    standard: "3.NF.A.2",
    type: "multiple-choice",
    questionText: "A strip of paper is divided into 6 equal parts. Four parts are shaded. Which fraction names the shaded part?",
    options: [
      { label: "A", text: "4/6" },
      { label: "B", text: "4/5" },
      { label: "C", text: "6/4" },
      { label: "D", text: "1/6" },
    ],
    correctAnswer: "A",
    rubric: "The student names the shaded fraction correctly.",
    points: 1,
  },
  {
    id: 13034,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "MD",
    target: "A",
    dok: 2,
    standard: "3.MD.A.1",
    type: "text-input",
    questionText: "The first museum video starts at 1:20 p.m. and ends at 1:55 p.m. How many minutes long is the video?",
    correctAnswer: "35",
    rubric: "The student enters the correct number of minutes.",
    points: 1,
  },
  {
    id: 13035,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 4,
    domain: "NBT",
    target: "D",
    dok: 3,
    standard: "3.NBT.A.2",
    type: "multiple-choice",
    questionText: "A museum sold 126 tickets on Thursday and 138 tickets on Friday. The goal was to sell 300 tickets over both days. Which statement is true?",
    options: [
      { label: "A", text: "The museum met the goal exactly." },
      { label: "B", text: "The museum sold 36 more than the goal." },
      { label: "C", text: "The museum sold 36 fewer than the goal." },
      { label: "D", text: "The museum sold 26 fewer than the goal." },
    ],
    correctAnswer: "C",
    rubric: "The student compares the total to the goal correctly.",
    points: 1,
  },
  {
    id: 13036,
    practiceTest: 13,
    testType: "cat",
    subject: "math",
    grade: 3,
    claim: 4,
    domain: "MD",
    target: "B",
    dok: 3,
    standard: "3.MD.D.8",
    type: "short-answer",
    questionText: "A rectangular fossil rug is 9 units long and 4 units wide. Explain how to find both the area and the perimeter of the rug. Write 2 or 3 sentences.",
    correctAnswer: "Area is 36 square units because 9 × 4 = 36. Perimeter is 26 units because 9 + 4 + 9 + 4 = 26.",
    rubric: "2 points: The response correctly explains how to find both area and perimeter. 1 point: The response correctly explains only one measure or has minor errors. 0 points: All other responses.",
    points: 2,
    explanation: "Area is found by multiplying length by width, so 9 × 4 = 36 square units. Perimeter is found by adding all four sides, so 9 + 4 + 9 + 4 = 26 units.",
  },
];

const test13MathPT: Question[] = [
  {
    id: 13040,
    practiceTest: 13,
    testType: "pt",
    subject: "math",
    grade: 3,
    claim: 2,
    domain: "MD",
    target: "C",
    dok: 2,
    standard: "3.MD.B.3",
    type: "multi-select",
    studentDirections: `**Mathematics Performance Task**

Ridge Museum is planning a Fossil Hall exhibit. The museum director wants to know which display drew the most visitors during the week.

Use the table to answer the questions about the Fossil Hall exhibit.`,
    dataTable: fossilHallTable,
    questionText: "Select all the display sections that had more than 140 visitors during the week.",
    options: [
      { label: "A", text: "Shell Display" },
      { label: "B", text: "Fern Display" },
      { label: "C", text: "Footprint Display" },
      { label: "D", text: "None of the displays" },
    ],
    correctAnswer: ["A"],
    rubric: "The student selects the display section with a total greater than 140 and no incorrect options.",
    points: 1,
  },
  {
    id: 13041,
    practiceTest: 13,
    testType: "pt",
    subject: "math",
    grade: 3,
    claim: 1,
    domain: "NBT",
    target: "D",
    dok: 2,
    standard: "3.NBT.A.2",
    type: "text-input",
    studentDirections: `**Mathematics Performance Task**

Ridge Museum is planning a Fossil Hall exhibit. The museum director wants to know which display drew the most visitors during the week.

Use the table to answer the questions about the Fossil Hall exhibit.`,
    dataTable: fossilHallTable,
    questionText: "How many visitors did the Shell Display have during the week?",
    correctAnswer: "155",
    rubric: "The student enters the correct weekly total for the Shell Display.",
    points: 1,
  },
  {
    id: 13042,
    practiceTest: 13,
    testType: "pt",
    subject: "math",
    grade: 3,
    claim: 4,
    domain: "NBT",
    target: "A",
    dok: 3,
    standard: "3.NBT.A.2",
    type: "table-input",
    studentDirections: `**Mathematics Performance Task**

Ridge Museum is planning a Fossil Hall exhibit. The museum director wants to know which display drew the most visitors during the week.

Use the table to answer the questions about the Fossil Hall exhibit.`,
    dataTable: fossilHallTable,
    questionText: "The museum will add a Saturday Mini-Fossil Display. Complete the table to show one way the Saturday display could have more visitors than the Footprint Display had during the week.",
    tableColumns: ["Saturday Morning", "Saturday Afternoon", "Saturday Evening"],
    tableRowLabel: "Mini-Fossil Display",
    tableMinSumExclusive: 100,
    correctAnswer: ["40", "35", "30"],
    rubric: "1 point: The student enters any three numbers with a total greater than 100. 0 points: All other responses.",
    points: 1,
  },
  {
    id: 13043,
    practiceTest: 13,
    testType: "pt",
    subject: "math",
    grade: 3,
    claim: 4,
    domain: "MD",
    target: "A",
    dok: 3,
    standard: "3.MD.B.3",
    type: "short-answer",
    studentDirections: `**Mathematics Performance Task**

Ridge Museum is planning a Fossil Hall exhibit. The museum director wants to know which display drew the most visitors during the week.

Use the table to answer the questions about the Fossil Hall exhibit.`,
    dataTable: fossilHallTable,
    questionText: "Which display should the museum place at the entrance if it wants the most visitors to see it first? Use numbers from the table to explain your answer.",
    correctAnswer: "The museum should place the Shell Display at the entrance because it had the most visitors. Its total was 155 visitors, which is greater than the Fern Display's 132 and the Footprint Display's 100.",
    rubric: "2 points: The response names the correct display and uses numbers from the table to justify the choice. 1 point: The response names the correct display with incomplete support. 0 points: All other responses.",
    points: 2,
    explanation: "The Shell Display should go at the entrance because it has the highest weekly total. A complete answer compares 155 visitors to 132 for the Fern Display and 100 for the Footprint Display.",
  },
  {
    id: 13044,
    practiceTest: 13,
    testType: "pt",
    subject: "math",
    grade: 3,
    claim: 4,
    domain: "MD",
    target: "B",
    dok: 3,
    standard: "3.MD.D.8",
    type: "short-answer",
    studentDirections: `**Mathematics Performance Task**

Ridge Museum is planning a Fossil Hall exhibit. The museum director wants to know which display drew the most visitors during the week.

Use the table to answer the questions about the Fossil Hall exhibit.`,
    dataTable: fossilHallTable,
    questionText: "The museum wants to build a rectangular sign for the most popular display. One sign design is 8 units long and 3 units wide. Find the area of the sign and explain what the area means.",
    correctAnswer: "The area is 24 square units because 8 × 3 = 24. This means the front of the sign covers 24 square units of space.",
    rubric: "2 points: The response gives the correct area and explains what the area means. 1 point: The response gives the correct area but weak explanation, or explains with a minor error. 0 points: All other responses.",
    points: 2,
    explanation: "Multiply the length and width to find area: 8 × 3 = 24 square units. The area tells how much surface the rectangular sign covers.",
  },
];

const test13ELACAT: Question[] = [
  {
    id: 13101,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "1",
    dok: 1,
    standard: "RL.3.1",
    type: "multiple-choice",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "Why does Nia stop before tossing the rock aside?",
    options: [
      { label: "A", text: "She thinks it belongs to Omar." },
      { label: "B", text: "She sees a pattern pressed into it." },
      { label: "C", text: "She wants to finish weeding faster." },
      { label: "D", text: "She hears Mr. Bennett call her name." },
    ],
    correctAnswer: "B",
    rubric: "The student selects the detail that explains Nia's action.",
    points: 1,
  },
  {
    id: 13102,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "5",
    dok: 2,
    standard: "RL.3.4",
    type: "multiple-choice",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "What does the word **pause** mean as it is used in the passage?",
    options: [
      { label: "A", text: "to stop for a moment" },
      { label: "B", text: "to fall over quickly" },
      { label: "C", text: "to speak loudly" },
      { label: "D", text: "to hide something" },
    ],
    correctAnswer: "A",
    rubric: "The student determines the meaning of a word from context.",
    points: 1,
  },
  {
    id: 13103,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "4",
    dok: 3,
    standard: "RL.3.2",
    type: "two-part",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "Part A: What lesson does Nia learn in the story?\n\nPart B: Which detail from the story best supports the answer to Part A?",
    partAPrompt: "What lesson does Nia learn in the story?",
    partAOptions: [
      { label: "A", text: "Careful noticing can lead to discovery." },
      { label: "B", text: "Recess is always more fun than work." },
      { label: "C", text: "Scientists work alone most of the time." },
      { label: "D", text: "School gardens should be replaced with museums." },
    ],
    partBPrompt: "Which detail from the story best supports the answer to Part A?",
    partBOptions: [
      { label: "A", text: "Omar pretends his shovel is a racecar." },
      { label: "B", text: "Nia almost throws the rock away, but the pattern on it makes her look more closely." },
      { label: "C", text: "The class gets extra recess after working." },
      { label: "D", text: "Students from other grades stop by the library display." },
    ],
    correctAnswer: ["A", "B"],
    rubric: "The student selects the correct answer in both parts.",
    points: 1,
  },
  {
    id: 13104,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "1",
    dok: 2,
    standard: "RL.3.1",
    type: "multiple-choice",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "Why does Mr. Bennett call the rock 'evidence' instead of 'treasure'?",
    options: [
      { label: "A", text: "He wants the students to sell it to the museum." },
      { label: "B", text: "He thinks it could give clues about something from the past." },
      { label: "C", text: "He does not want the students to be excited." },
      { label: "D", text: "He knows it is only an ordinary stone." },
    ],
    correctAnswer: "B",
    rubric: "The student uses story details to make an inference.",
    points: 1,
  },
  {
    id: 13105,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "3",
    dok: 2,
    standard: "RL.3.3",
    type: "multiple-choice",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "Which event happens first in the story?",
    options: [
      { label: "A", text: "Dr. Cruz visits the class with sample fossils." },
      { label: "B", text: "The class creates a library display." },
      { label: "C", text: "Nia notices lines pressed into a rock." },
      { label: "D", text: "Mr. Bennett emails Dr. Cruz." },
    ],
    correctAnswer: "C",
    rubric: "The student identifies the first event in sequence.",
    points: 1,
  },
  {
    id: 13106,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "1",
    dok: 2,
    standard: "RL.3.1",
    type: "multi-select",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "Select two details that show the class studies the rock carefully.",
    options: [
      { label: "A", text: "They put the weeds in a bucket." },
      { label: "B", text: "They use a magnifying lens to look at the rock." },
      { label: "C", text: "They compare the rock with Dr. Cruz's sample fossils." },
      { label: "D", text: "They ask for extra recess." },
    ],
    correctAnswer: ["B", "C"],
    rubric: "The student selects the two details that support careful study.",
    points: 1,
  },
  {
    id: 13107,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "5",
    dok: 2,
    standard: "RL.3.4",
    type: "multiple-choice",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "What does the word **ordinary** mean in the last paragraph?",
    options: [
      { label: "A", text: "special" },
      { label: "B", text: "common" },
      { label: "C", text: "dangerous" },
      { label: "D", text: "silent" },
    ],
    correctAnswer: "B",
    rubric: "The student determines the meaning of a word from context.",
    points: 1,
  },
  {
    id: 13108,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "3",
    dok: 2,
    standard: "RL.3.3",
    type: "multiple-choice",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "How does Omar change from the beginning of the story to the end?",
    options: [
      { label: "A", text: "He becomes more interested in the discovery." },
      { label: "B", text: "He decides that science is too hard." },
      { label: "C", text: "He stays upset about missing recess." },
      { label: "D", text: "He stops talking to Nia." },
    ],
    correctAnswer: "A",
    rubric: "The student analyzes character change.",
    points: 1,
  },
  {
    id: 13109,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "6",
    dok: 2,
    standard: "RL.3.6",
    type: "multiple-choice",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "From whose point of view is the story told?",
    options: [
      { label: "A", text: "Nia's, as if she is telling the story herself" },
      { label: "B", text: "Omar's, as if he is speaking to the reader" },
      { label: "C", text: "A narrator who tells about Nia and the other characters" },
      { label: "D", text: "Dr. Cruz's, as if she is writing a report" },
    ],
    correctAnswer: "C",
    rubric: "The student identifies the story's point of view.",
    points: 1,
  },
  {
    id: 13110,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "4",
    dok: 3,
    standard: "RL.3.2",
    type: "two-part",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "Part A: Why is the library display important to the story?\n\nPart B: Which sentence best supports the answer to Part A?",
    partAPrompt: "Why is the library display important to the story?",
    partAOptions: [
      { label: "A", text: "It shows the class has turned the discovery into something they can share with others." },
      { label: "B", text: "It proves the fossil is the oldest one in the county." },
      { label: "C", text: "It makes Omar wish he had found the fossil first." },
      { label: "D", text: "It helps the class avoid doing any more work." },
    ],
    partBPrompt: "Which sentence best supports the answer to Part A?",
    partBOptions: [
      { label: "A", text: "The ground was dry from three sunny days." },
      { label: "B", text: "Students from other grades stopped to look." },
      { label: "C", text: "Mr. Bennett carried a wheelbarrow to the compost bin." },
      { label: "D", text: "Some guessed it was a feather." },
    ],
    correctAnswer: ["A", "B"],
    rubric: "The student selects the correct response in both parts.",
    points: 1,
  },
  {
    id: 13111,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "5",
    dok: 2,
    standard: "RL.3.4",
    type: "multiple-choice",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "What does the phrase **hands flew into the air** show about the students?",
    options: [
      { label: "A", text: "They are eager to answer." },
      { label: "B", text: "They are afraid of the fossils." },
      { label: "C", text: "They are getting ready to leave." },
      { label: "D", text: "They are measuring the rock." },
    ],
    correctAnswer: "A",
    rubric: "The student interprets figurative language in context.",
    points: 1,
  },
  {
    id: 13112,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "2",
    dok: 2,
    standard: "RL.3.2",
    type: "multi-select",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "Select the two sentences that should be included in a summary of the story.",
    options: [
      { label: "A", text: "Nia finds a rock with a leaf-like pattern while pulling weeds at school." },
      { label: "B", text: "The weather is sunny for three days before the discovery." },
      { label: "C", text: "A museum scientist helps the class learn that the rock is likely a fossil." },
      { label: "D", text: "Omar pretends his shovel is a racecar." },
    ],
    correctAnswer: ["A", "C"],
    rubric: "The student selects the key ideas needed for a summary.",
    points: 1,
  },
  {
    id: 13113,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "3",
    dok: 2,
    standard: "RL.3.3",
    type: "multiple-choice",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "How does Nia most likely feel at the end of the story?",
    options: [
      { label: "A", text: "Proud and curious" },
      { label: "B", text: "Angry and tired" },
      { label: "C", text: "Confused and worried" },
      { label: "D", text: "Lonely and bored" },
    ],
    correctAnswer: "A",
    rubric: "The student infers a character's feelings from the ending.",
    points: 1,
  },
  {
    id: 13114,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "3",
    dok: 2,
    standard: "RL.3.3",
    type: "multiple-choice",
    passage: fossilSchoolyardPassage,
    passageTitle: "The Fossil in the Schoolyard",
    questionText: "Which sentence best tells the main problem in the story?",
    options: [
      { label: "A", text: "Nia wants to skip the school garden work." },
      { label: "B", text: "The class needs to figure out what the strange rock might be." },
      { label: "C", text: "Omar cannot find his shovel." },
      { label: "D", text: "Dr. Cruz arrives late to school." },
    ],
    correctAnswer: "B",
    rubric: "The student identifies the story's central problem.",
    points: 1,
  },
  {
    id: 13115,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "2",
    dok: 2,
    standard: "RI.3.2",
    type: "multiple-choice",
    passage: fossilsFormPassage,
    passageTitle: "How Fossils Form",
    questionText: "What is the main idea of the passage?",
    options: [
      { label: "A", text: "Fossils form through processes in rock layers and help scientists learn about the past." },
      { label: "B", text: "Only body fossils are useful to scientists." },
      { label: "C", text: "Most fossils are found near schools and museums." },
      { label: "D", text: "Scientists always know exactly how old a fossil is." },
    ],
    correctAnswer: "A",
    rubric: "The student identifies the main idea of the passage.",
    points: 1,
  },
  {
    id: 13116,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "5",
    dok: 2,
    standard: "RI.3.4",
    type: "multiple-choice",
    passage: fossilsFormPassage,
    passageTitle: "How Fossils Form",
    questionText: "What does the word **sediment** mean in the passage?",
    options: [
      { label: "A", text: "a type of animal bone" },
      { label: "B", text: "material such as mud or sand that can cover remains" },
      { label: "C", text: "a tool scientists use to dig" },
      { label: "D", text: "a map of rock layers" },
    ],
    correctAnswer: "B",
    rubric: "The student determines the meaning of a domain-specific word from context.",
    points: 1,
  },
  {
    id: 13117,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "3",
    dok: 2,
    standard: "RI.3.3",
    type: "multiple-choice",
    passage: fossilsFormPassage,
    passageTitle: "How Fossils Form",
    questionText: "Why is quick burial important when a fossil begins to form?",
    options: [
      { label: "A", text: "It helps protect the remains." },
      { label: "B", text: "It makes the fossil turn into metal." },
      { label: "C", text: "It keeps scientists from seeing it." },
      { label: "D", text: "It makes every fossil a body fossil." },
    ],
    correctAnswer: "A",
    rubric: "The student identifies a cause-and-effect relationship in the article.",
    points: 1,
  },
  {
    id: 13118,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "4",
    dok: 3,
    standard: "RI.3.1",
    type: "multi-select",
    passage: fossilsFormPassage,
    passageTitle: "How Fossils Form",
    questionText: "Select two details that explain why fossils are helpful to scientists.",
    options: [
      { label: "A", text: "A fossil fish might suggest that water once covered an area." },
      { label: "B", text: "Fossils can give clues about ancient environments and living things." },
      { label: "C", text: "Fossils always show the exact date an organism lived." },
      { label: "D", text: "Only museums can study fossils correctly." },
    ],
    correctAnswer: ["A", "B"],
    rubric: "The student selects the two details that explain why fossils are useful to scientists.",
    points: 1,
  },
  {
    id: 13119,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "1",
    dok: 2,
    standard: "RI.3.1",
    type: "multi-select",
    passage: fossilsFormPassage,
    passageTitle: "How Fossils Form",
    questionText: "Select two statements that are supported by the passage.",
    options: [
      { label: "A", text: "A footprint can be a trace fossil." },
      { label: "B", text: "Fossils can form only in water." },
      { label: "C", text: "Lower rock layers often formed earlier than higher ones." },
      { label: "D", text: "Scientists never compare fossils with living things." },
    ],
    correctAnswer: ["A", "C"],
    rubric: "The student selects two supported statements.",
    points: 1,
  },
  {
    id: 13120,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "6",
    dok: 2,
    standard: "RI.3.5",
    type: "multiple-choice",
    passage: fossilsFormPassage,
    passageTitle: "How Fossils Form",
    questionText: "Why does the author include the heading **Body Fossils and Trace Fossils**?",
    options: [
      { label: "A", text: "to tell a story about two scientists" },
      { label: "B", text: "to compare two kinds of fossils" },
      { label: "C", text: "to explain how to draw fossils" },
      { label: "D", text: "to list the oldest fossils ever found" },
    ],
    correctAnswer: "B",
    rubric: "The student identifies the purpose of a text feature.",
    points: 1,
  },
  {
    id: 13121,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 1,
    target: "9",
    dok: 2,
    standard: "RI.3.9",
    type: "multiple-choice",
    passage: fossilSchoolyardPassage + "\n\n---\n\n" + fossilsFormPassage,
    passageTitle: "The Fossil in the Schoolyard / How Fossils Form",
    questionText: "How are the two passages mostly alike?",
    options: [
      { label: "A", text: "Both explain how to build a museum display." },
      { label: "B", text: "Both show that fossils can give clues about the past." },
      { label: "C", text: "Both are stories told by Nia." },
      { label: "D", text: "Both focus only on animal fossils." },
    ],
    correctAnswer: "B",
    rubric: "The student compares ideas across the two passages.",
    points: 1,
  },
  {
    id: 13122,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 3,
    target: "4",
    dok: 3,
    standard: "SL.3.2",
    type: "two-part",
    passage: museumPresentationTranscript,
    passageTitle: "A Day at Ridge Museum",
    studentDirections: "Read the transcript of the presentation. Then answer the questions.",
    questionText: "Part A: What is the most likely reason the speaker gave the presentation?\n\nPart B: Which sentence from the presentation best supports the answer to Part A?",
    partAPrompt: "What is the most likely reason the speaker gave the presentation?",
    partAOptions: [
      { label: "A", text: "to explain how the new fossil exhibit was prepared and why it matters" },
      { label: "B", text: "to persuade listeners to stop visiting museums" },
      { label: "C", text: "to describe how to grow ferns at home" },
      { label: "D", text: "to tell a funny story about heavy traffic" },
    ],
    partBPrompt: "Which sentence from the presentation best supports the answer to Part A?",
    partBOptions: [
      { label: "A", text: "Today I want to tell you about the museum's newest fossil exhibit and how it was prepared for the public." },
      { label: "B", text: "One part of the opening did not happen as planned." },
      { label: "C", text: "Guides explained that fossils are useful because they give clues about ancient environments." },
      { label: "D", text: "The museum director said the goal of Discovery Week was to help young scientists ask new questions." },
    ],
    correctAnswer: ["A", "A"],
    rubric: "The student selects the correct answer in both parts.",
    points: 1,
  },
  {
    id: 13123,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 3,
    target: "4",
    dok: 2,
    standard: "SL.3.2",
    type: "multi-select",
    passage: museumPresentationTranscript,
    passageTitle: "A Day at Ridge Museum",
    studentDirections: "Read the transcript of the presentation. Then answer the questions.",
    questionText: "Select two questions a listener can answer after reading the presentation.",
    options: [
      { label: "A", text: "What problem happened on the opening morning?" },
      { label: "B", text: "How was the museum's newest fossil exhibit prepared for the public?" },
      { label: "C", text: "How much did it cost to print the museum maps?" },
      { label: "D", text: "Why did the museum director decide to become a scientist?" },
    ],
    correctAnswer: ["A", "B"],
    rubric: "The student selects the two questions answered by the presentation.",
    points: 1,
  },
  {
    id: 13124,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 3,
    target: "4",
    dok: 2,
    standard: "SL.3.2",
    type: "grid-match",
    passage: museumPresentationTranscript,
    passageTitle: "A Day at Ridge Museum",
    studentDirections: "Read the transcript of the presentation. Then answer the questions.",
    questionText: "Complete the chart to show which events were planned and which event was unplanned.",
    gridRows: [
      "Workers cleaned the display cases.",
      "The final fern fossil arrived late.",
      "The museum team printed maps.",
      "Visitors wrote notes on the question wall.",
    ],
    gridColumns: ["Planned", "Unplanned"],
    correctAnswer: ["0:0", "1:1", "2:0", "3:0"],
    rubric: "The student correctly identifies which events were planned and which were unplanned.",
    points: 1,
  },
  {
    id: 13125,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 3,
    target: "4",
    dok: 2,
    standard: "SL.3.2",
    type: "multi-select",
    passage: fossilCluesTranscript,
    passageTitle: "Clues in Stone",
    studentDirections: "Read the transcript of the presentation. Then answer the questions.",
    questionText: "Select two conclusions supported by the presentation.",
    options: [
      { label: "A", text: "Museum stations can help visitors remember different fossil clues." },
      { label: "B", text: "Different fossil clues can help scientists think about different parts of the past." },
      { label: "C", text: "Every fossil tells the same kind of story." },
      { label: "D", text: "Museum helpers planned nothing before the presentation." },
    ],
    correctAnswer: ["A", "B"],
    rubric: "The student selects the two conclusions supported by the presentation.",
    points: 1,
  },
  {
    id: 13126,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 3,
    target: "4",
    dok: 2,
    standard: "SL.3.2",
    type: "grid-match",
    passage: fossilCluesTranscript,
    passageTitle: "Clues in Stone",
    studentDirections: "Read the transcript of the presentation. Then answer the questions.",
    questionText: "Complete the chart to match each fossil clue with what it can help scientists think about.",
    gridRows: ["Shell fossil", "Fern print", "Footprint fossil"],
    gridColumns: ["water in the past", "land and climate", "how an animal moved"],
    correctAnswer: ["0:0", "1:1", "2:2"],
    rubric: "The student matches each fossil clue with the correct idea from the presentation.",
    points: 1,
  },
  {
    id: 13127,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 3,
    target: "4",
    dok: 2,
    standard: "SL.3.2",
    type: "multiple-choice",
    passage: fossilCluesTranscript,
    passageTitle: "Clues in Stone",
    studentDirections: "Read the transcript of the presentation. Then answer the questions.",
    questionText: "What is the most likely reason the speaker compares fossil clues to museum stations?",
    options: [
      { label: "A", text: "to help visitors remember the information more easily" },
      { label: "B", text: "to show that museums should only teach with food" },
      { label: "C", text: "to prove that one station is the best" },
      { label: "D", text: "to explain why fans should not be used indoors" },
    ],
    correctAnswer: "A",
    rubric: "The student determines the speaker's likely reason for making the comparison.",
    points: 1,
  },
  {
    id: 13128,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 3,
    target: "4",
    dok: 2,
    standard: "SL.3.2",
    type: "multi-select",
    passage: fossilCluesTranscript,
    passageTitle: "Clues in Stone",
    studentDirections: "Read the transcript of the presentation. Then answer the questions.",
    questionText: "Select two details from the presentation that belong in a listener's notes.",
    options: [
      { label: "A", text: "Shell fossils can suggest that water was in an area long ago." },
      { label: "B", text: "The speaker's favorite snack is pretzels." },
      { label: "C", text: "Footprint fossils can give clues about how an animal moved." },
      { label: "D", text: "The museum gift shop sells toy shovels." },
    ],
    correctAnswer: ["A", "C"],
    rubric: "The student selects the two details supported by the presentation.",
    points: 1,
  },
  {
    id: 13129,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 3,
    target: "4",
    dok: 2,
    standard: "SL.3.2",
    type: "multi-select",
    passage: museumPresentationTranscript,
    passageTitle: "A Day at Ridge Museum",
    studentDirections: "Read the transcript of the presentation. Then answer the questions.",
    questionText: "Select two ideas the speaker emphasizes in the presentation.",
    options: [
      { label: "A", text: "The museum's newest fossil exhibit was prepared carefully for the public." },
      { label: "B", text: "Discovery Week was meant to help young scientists ask new questions." },
      { label: "C", text: "The oldest fossil in the building was found by the speaker." },
      { label: "D", text: "Visitors were told never to speak during the exhibit opening." },
    ],
    correctAnswer: ["A", "B"],
    rubric: "The student selects the two ideas emphasized in the presentation.",
    points: 1,
  },
  {
    id: 13130,
    practiceTest: 13,
    testType: "cat",
    subject: "ela",
    grade: 3,
    claim: 3,
    target: "4",
    dok: 2,
    standard: "SL.3.2",
    type: "multiple-choice",
    passage: museumPresentationTranscript,
    passageTitle: "A Day at Ridge Museum",
    studentDirections: "Read the transcript of the presentation. Then answer the questions.",
    questionText: "Which detail from the presentation best supports the idea that the exhibit encouraged curiosity?",
    options: [
      { label: "A", text: "The opening started in the morning." },
      { label: "B", text: "The museum director said Discovery Week was meant to help young scientists ask new questions." },
      { label: "C", text: "Workers cleaned the display cases before visitors arrived." },
      { label: "D", text: "One fossil arrived later than expected." },
    ],
    correctAnswer: "B",
    rubric: "The student selects the detail that best supports the stated idea.",
    points: 1,
  },
];

const test13ELAPT: Question[] = [
  {
    id: 13150,
    practiceTest: 13,
    testType: "pt",
    subject: "ela",
    grade: 3,
    claim: 4,
    target: "2",
    dok: 3,
    standard: "RI.3.9",
    type: "grid-match",
    passage: ridgeDiscoverySource + "\n\n---\n\n" + fossilsHelpScientistsSource,
    passageTitle: "The Ridge Discovery / Why Fossils Help Scientists",
    questionText: "Complete the chart to show whether each detail comes from Source 1, Source 2, or both sources.",
    gridRows: [
      "Scientists study rock layers around fossils.",
      "Children help create a poster for the town library.",
      "Fossils can give clues about ancient environments.",
    ],
    gridColumns: ["Source 1", "Source 2", "Both Sources"],
    correctAnswer: ["0:1", "1:0", "2:2"],
    rubric: "The student correctly identifies where each detail appears across the two sources.",
    points: 1,
  },
  {
    id: 13151,
    practiceTest: 13,
    testType: "pt",
    subject: "ela",
    grade: 3,
    claim: 4,
    target: "3",
    dok: 3,
    standard: "W.3.9",
    type: "short-answer",
    passage: ridgeDiscoverySource + "\n\n---\n\n" + fossilsHelpScientistsSource,
    passageTitle: "The Ridge Discovery / Why Fossils Help Scientists",
    questionText: "Explain how the fossil found on Juniper Ridge helped people learn about the past. Use information from both sources. Write 2 or 3 sentences.",
    correctAnswer: "The fern print from Juniper Ridge helped people learn that the area may once have been wetter and greener. Source 2 explains that plant fossils help scientists think about climate and land conditions from long ago, so the discovery gave evidence about the ridge's ancient environment.",
    rubric: "2 points: The response uses accurate information from both sources to explain what the fossil revealed. 1 point: The response uses one source well or gives only partial support. 0 points: All other responses.",
    points: 2,
    explanation: "A strong answer explains that the fern fossil gave evidence about what Juniper Ridge was like long ago. The discovery source describes the fern print, and the second source explains that plant fossils help scientists infer past climate and land conditions.",
  },
  {
    id: 13152,
    practiceTest: 13,
    testType: "pt",
    subject: "ela",
    grade: 3,
    claim: 2,
    target: "4",
    dok: 4,
    standard: "W.3.2",
    type: "extended-writing",
    passage: ridgeDiscoverySource + "\n\n---\n\n" + fossilsHelpScientistsSource,
    passageTitle: "The Ridge Discovery / Why Fossils Help Scientists",
    studentDirections: "You have read 'The Ridge Discovery' and 'Why Fossils Help Scientists.' Now write an informational response explaining how fossil discoveries help scientists and communities learn about the past.\n\nIn your response:\n- Introduce the topic clearly\n- Use at least one detail from 'The Ridge Discovery'\n- Use at least one detail from 'Why Fossils Help Scientists'\n- Explain how the details support your ideas\n- Use complete sentences and correct punctuation",
    questionText: "Write an informational response explaining how fossil discoveries help scientists and communities learn about the past. Use details from both sources.",
    correctAnswer: "Responses will vary. See rubric.",
    rubric: "4 points: The response clearly explains the topic, uses relevant details from both sources, and is well organized. 3 points: The response uses both sources with some development. 2 points: The response uses limited source support or uneven development. 1 point: Minimal response. 0 points: Off-topic or blank.",
    points: 4,
    explanation: "A strong response explains that fossil discoveries help scientists and communities learn about past plants, animals, and environments, using details from both the Juniper Ridge discovery and the informational source about fossils.",
  },
];

export const practiceTest13Questions: Question[] = [
  ...test13MathCAT,
  ...test13MathPT,
  ...test13ELACAT,
  ...test13ELAPT,
];
