import { type Question } from "./questions";

// ══════════════════════════════════════════════════════════════
// MEDIUM PRACTICE TEST 6 — GRADE 3 CAASPP
// Similar difficulty to Practice Tests 2 and 3
// ══════════════════════════════════════════════════════════════

const lanternBridgePassage = `Read the passage and answer the questions.

**The Lantern Bridge**
*by Naomi Reed*

Every autumn, the town of Pine Creek held a lantern walk. Families gathered at sunset beside the old wooden bridge, carrying paper lanterns painted with stars, leaves, and moons. Then they crossed the bridge together and hung the lanterns in the town square.

This year, however, the bridge was closed.

On the morning of the lantern walk, Maya and her older brother Eli rode their bikes to the creek and saw a bright orange sign. It said:

**BRIDGE CLOSED FOR REPAIRS**

"But the lantern walk is tonight!" Maya said.

Mr. Vega, who was standing nearby with a toolbox, nodded. "Last night's storm loosened several boards. It isn't safe for people to cross yet."

Maya stared at the dark water moving below the bridge. "Then the lantern walk is ruined."

"Not ruined," Eli said. "Just changed."

Maya wasn't so sure. The bridge was the heart of the tradition. Their grandmother had crossed it when she was a child. Last year, Maya had carried a lantern painted with a fox. This year, she had painted one with silver fish and tiny blue waves.

At lunch, Maya, Eli, and their grandmother sat at the kitchen table. Grandma listened carefully, then folded her hands.

"Traditions matter," she said, "but the reason behind a tradition matters even more."

"What does that mean?" Maya asked.

"The lantern walk was never only about the bridge," Grandma replied. "It was about bringing people together."

Eli looked up. "Then we need another way to bring everyone together."

That afternoon, the three of them made calls. Eli spoke with the librarian. Grandma called the bakery. Maya went door to door on their street with a marker and a stack of bright yellow paper.

By evening, new signs were taped all over town:

**LANTERN WALK MOVED TO MAPLE PARK**
**MEET BY THE BIG OAK TREE AT 6:30**

When Maya arrived at the park, she gasped. Strings of white lights hung between the trees. The bakery had sent trays of warm rolls. The librarian had brought a wagon full of books about fall festivals from around the world. Families stood in groups, laughing as they lit their lanterns.

"You did all this so quickly," Maya told Grandma.

Grandma smiled. "Many hands make light work."

At 6:30, Mr. Vega rang a little brass bell. "Welcome, everyone!" he called. "The bridge may be closed, but Pine Creek is still open for celebration."

People cheered. Then the lantern walk began. Instead of crossing the creek, everyone followed a path around the park. The lanterns glowed red, gold, and blue in the deepening twilight. Reflections of the lights shimmered in the pond.

Maya walked beside Eli and Grandma, holding her lantern carefully. Around her, she heard babies babbling, dogs barking, and neighbors greeting one another. The night felt different from past years, but not smaller. In some ways, it felt bigger.

At the end of the path, families hung their lanterns on ropes stretched between two trees. Soon the park was shining.

Maya stepped back and looked at the glowing row of lanterns. "I think this might be my favorite lantern walk yet," she said.

Grandma squeezed her shoulder. "Traditions can bend without breaking," she said.

Across the park, Mr. Vega lifted a repaired board from the bridge onto his truck. He waved, and Maya waved back. She realized the town had not lost its tradition at all. It had carried it somewhere new.`;

const riverPassage = `Read the passage and answer the questions.

**How Rivers Shape the Land**
*adapted from educational science sources*

Rivers do much more than carry water from one place to another. Over time, rivers can change the shape of land, move rocks and soil, and create habitats for plants and animals. Even a small stream can slowly carve a path through earth and stone.

**Where Rivers Begin**

Many rivers begin in mountains or hills where rainwater collects or snow melts. Gravity pulls the water downhill. As tiny streams join together, they form larger creeks and rivers. A river's beginning is called its source.

**Erosion and Weathering**

Flowing water wears away land in a process called erosion. A river can carry bits of sand, soil, and rock. As these materials bump and scrape along the bottom of the river, they help wear the land away even more. Weathering also helps. Weathering happens when wind, water, ice, and temperature changes break rocks into smaller pieces.

**Curves, Valleys, and Canyons**

Rivers do not always flow in straight lines. Over time, they often curve and bend. These bends are called meanders. A river may also cut down into the ground and form a valley. In some places, rivers have carved deep canyons with steep walls. The Grand Canyon in Arizona was shaped over a very long time by the Colorado River and other natural forces.

**Dropping Sediment**

As rivers slow down, they may drop some of the sand, soil, and rock they were carrying. These dropped materials are called sediment. Sediment can build up along riverbanks or near the mouth of a river, where it flows into a lake or ocean. Over time, this can create new landforms.

**Why Rivers Matter**

Rivers provide water for people, farms, and wildlife. Many animals depend on river habitats for food and shelter. Fish lay eggs in riverbeds. Birds nest in trees along the banks. People also use rivers for transportation, fishing, and recreation.

Because rivers are so important, many communities work to protect them. Planting trees near riverbanks, reducing pollution, and keeping trash out of streams all help keep rivers healthy. A healthy river can continue shaping the land and supporting life for many years.`;

// ══════════════════════════════════════════════════════════════
// PRACTICE TEST 6 — MATH CAT (36 questions, IDs 5001–5036)
// ══════════════════════════════════════════════════════════════

const test6MathCAT: Question[] = [
  {
    id: 5001, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "OA", target: "A", dok: 2, standard: "3.OA.A.1",
    type: "text-input",
    questionText: "A school buys 7 boxes of markers. Each box has 8 markers. How many markers did the school buy?",
    correctAnswer: "56",
    rubric: "The student enters the correct product.",
    points: 1,
    explanation: "Multiply the number of boxes by the markers in each box: 7 × 8 = 56 markers.",
  },
  {
    id: 5002, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "OA", target: "A", dok: 2, standard: "3.OA.A.3",
    type: "multiple-choice",
    questionText: "There are 45 students going on a trip. They ride in vans that hold 5 students each. How many vans are needed?",
    options: [
      { label: "A", text: "8" },
      { label: "B", text: "9" },
      { label: "C", text: "10" },
      { label: "D", text: "40" },
    ],
    correctAnswer: "B",
    rubric: "The student selects the correct quotient.",
    points: 1,
    explanation: "Divide 45 by 5. Since 45 ÷ 5 = 9, they need 9 vans.",
  },
  {
    id: 5003, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "OA", target: "B", dok: 1, standard: "3.OA.A.4",
    type: "text-input",
    questionText: "What number makes this equation true?\n\n? × 8 = 64",
    correctAnswer: "8",
    rubric: "The student enters the correct missing factor.",
    points: 1,
    explanation: "The missing factor is 8 because 8 × 8 = 64.",
  },
  {
    id: 5004, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "OA", target: "B", dok: 1, standard: "3.OA.B.6",
    type: "multiple-choice",
    questionText: "Which equation is in the same fact family as 9 × 6 = 54?",
    options: [
      { label: "A", text: "54 ÷ 9 = 6" },
      { label: "B", text: "54 − 9 = 45" },
      { label: "C", text: "9 + 6 = 15" },
      { label: "D", text: "54 + 6 = 60" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies a related division fact.",
    points: 1,
    explanation: "Fact families connect multiplication and division. Since 9 × 6 = 54, then 54 ÷ 9 = 6.",
  },
  {
    id: 5005, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "OA", target: "C", dok: 1, standard: "3.OA.C.7",
    type: "text-input",
    questionText: "What is 7 × 9?",
    correctAnswer: "63",
    rubric: "The student enters the correct product.",
    points: 1,
    explanation: "7 × 9 = 63.",
  },
  {
    id: 5006, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "OA", target: "C", dok: 1, standard: "3.OA.C.7",
    type: "text-input",
    questionText: "What is 56 ÷ 7?",
    correctAnswer: "8",
    rubric: "The student enters the correct quotient.",
    points: 1,
    explanation: "56 ÷ 7 = 8 because 8 × 7 = 56.",
  },
  {
    id: 5007, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "OA", target: "D", dok: 2, standard: "3.OA.D.8",
    type: "multiple-choice",
    questionText: "Jamal reads 18 pages on Monday and 27 pages on Tuesday. He wants to read 60 pages total. How many pages does he still need to read?",
    options: [
      { label: "A", text: "15" },
      { label: "B", text: "18" },
      { label: "C", text: "33" },
      { label: "D", text: "45" },
    ],
    correctAnswer: "A",
    rubric: "The student solves a two-step problem.",
    points: 1,
    explanation: "First add 18 + 27 = 45. Then subtract 60 − 45 = 15 pages still needed.",
  },
  {
    id: 5008, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 3, domain: "OA", target: "F", dok: 2, standard: "3.OA.B.5",
    type: "multiple-choice",
    questionText: "Which equation shows the distributive property?",
    options: [
      { label: "A", text: "6 × 7 = (6 × 5) + (6 × 2)" },
      { label: "B", text: "6 × 7 = 6 + 7" },
      { label: "C", text: "6 × 7 = 7 × 7" },
      { label: "D", text: "6 × 7 = 42 + 7" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies an equation using the distributive property.",
    points: 1,
    explanation: "You can break 7 into 5 + 2, so 6 × 7 = (6 × 5) + (6 × 2).",
  },
  {
    id: 5009, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 3, domain: "OA", target: "F", dok: 2, standard: "3.OA.B.5",
    type: "multiple-choice",
    questionText: "Which statement is true?",
    options: [
      { label: "A", text: "4 × 8 is greater than 8 × 4" },
      { label: "B", text: "4 × 8 is less than 8 × 4" },
      { label: "C", text: "4 × 8 is equal to 8 × 4" },
      { label: "D", text: "4 × 8 is equal to 4 + 8" },
    ],
    correctAnswer: "C",
    rubric: "The student understands the commutative property.",
    points: 1,
    explanation: "The order of the factors does not change the product. 4 × 8 = 8 × 4 = 32.",
  },
  {
    id: 5010, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "OA", target: "D", dok: 2, standard: "3.OA.D.9",
    type: "text-input",
    questionText: "Complete the pattern: 6, 12, 18, 24, __, __",
    correctAnswer: "30, 36",
    rubric: "The student enters the next two numbers in the pattern.",
    points: 1,
    explanation: "The pattern adds 6 each time, so the next numbers are 30 and 36.",
  },
  {
    id: 5011, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "NBT", target: "E", dok: 1, standard: "3.NBT.A.1",
    type: "multiple-choice",
    questionText: "What is 286 rounded to the nearest ten?",
    options: [
      { label: "A", text: "280" },
      { label: "B", text: "290" },
      { label: "C", text: "300" },
      { label: "D", text: "286" },
    ],
    correctAnswer: "B",
    rubric: "The student rounds to the nearest ten.",
    points: 1,
    explanation: "The ones digit is 6, so 286 rounds up to 290.",
  },
  {
    id: 5012, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "NBT", target: "E", dok: 1, standard: "3.NBT.A.1",
    type: "text-input",
    questionText: "Round 648 to the nearest hundred.",
    correctAnswer: "600",
    rubric: "The student rounds to the nearest hundred.",
    points: 1,
    explanation: "The tens digit is 4, so 648 rounds down to 600.",
  },
  {
    id: 5013, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "NBT", target: "E", dok: 2, standard: "3.NBT.A.2",
    type: "text-input",
    questionText: "What is 378 + 246?",
    correctAnswer: "624",
    rubric: "The student enters the correct sum.",
    points: 1,
    explanation: "378 + 246 = 624.",
  },
  {
    id: 5014, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "NBT", target: "E", dok: 2, standard: "3.NBT.A.2",
    type: "text-input",
    questionText: "What is 905 − 187?",
    correctAnswer: "718",
    rubric: "The student enters the correct difference.",
    points: 1,
    explanation: "Subtract carefully: 905 − 187 = 718.",
  },
  {
    id: 5015, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "NBT", target: "E", dok: 2, standard: "3.NBT.A.3",
    type: "multiple-choice",
    questionText: "What is 4 × 300?",
    options: [
      { label: "A", text: "120" },
      { label: "B", text: "700" },
      { label: "C", text: "1,200" },
      { label: "D", text: "12,000" },
    ],
    correctAnswer: "C",
    rubric: "The student selects the correct product.",
    points: 1,
    explanation: "4 × 300 = 1,200.",
  },
  {
    id: 5016, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "NBT", target: "E", dok: 2, standard: "3.NBT.A.3",
    type: "text-input",
    questionText: "What is 6 × 40?",
    correctAnswer: "240",
    rubric: "The student enters the correct product.",
    points: 1,
    explanation: "6 × 40 = 240.",
  },
  {
    id: 5017, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "NF", target: "F", dok: 2, standard: "3.NF.A.1",
    type: "multiple-choice",
    questionText: "A ribbon is cut into 8 equal pieces. Three pieces are used. What fraction of the ribbon is used?",
    options: [
      { label: "A", text: "3/8" },
      { label: "B", text: "5/8" },
      { label: "C", text: "8/3" },
      { label: "D", text: "1/8" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies the correct fraction.",
    points: 1,
    explanation: "Three out of eight equal parts were used, so the fraction is 3/8.",
  },
  {
    id: 5018, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "NF", target: "F", dok: 2, standard: "3.NF.A.2",
    type: "text-input",
    questionText: "A number line from 0 to 1 is divided into 6 equal parts. What fraction is at the second mark after 0?",
    correctAnswer: "2/6",
    rubric: "The student enters the correct fraction.",
    points: 1,
    explanation: "The second mark after 0 is 2 out of 6 equal parts, so it is 2/6.",
  },
  {
    id: 5019, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "NF", target: "F", dok: 2, standard: "3.NF.A.3",
    type: "multiple-choice",
    questionText: "Which fraction is greater than 1/3?",
    options: [
      { label: "A", text: "1/4" },
      { label: "B", text: "1/5" },
      { label: "C", text: "1/2" },
      { label: "D", text: "1/6" },
    ],
    correctAnswer: "C",
    rubric: "The student compares fractions with the same numerator.",
    points: 1,
    explanation: "For unit fractions, the smaller denominator gives the larger fraction. 1/2 is greater than 1/3.",
  },
  {
    id: 5020, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "NF", target: "F", dok: 2, standard: "3.NF.A.3",
    type: "multiple-choice",
    questionText: "Which pair of fractions is equivalent?",
    options: [
      { label: "A", text: "1/2 and 3/4" },
      { label: "B", text: "2/3 and 4/6" },
      { label: "C", text: "1/3 and 1/6" },
      { label: "D", text: "2/5 and 3/5" },
    ],
    correctAnswer: "B",
    rubric: "The student identifies equivalent fractions.",
    points: 1,
    explanation: "2/3 and 4/6 are equivalent because 4/6 simplifies to 2/3.",
  },
  {
    id: 5021, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "MD", target: "G", dok: 2, standard: "3.MD.A.1",
    type: "multiple-choice",
    questionText: "A concert starts at 6:20 p.m. and ends at 7:55 p.m. How long is the concert?",
    options: [
      { label: "A", text: "1 hour 15 minutes" },
      { label: "B", text: "1 hour 25 minutes" },
      { label: "C", text: "1 hour 35 minutes" },
      { label: "D", text: "2 hours 5 minutes" },
    ],
    correctAnswer: "C",
    rubric: "The student calculates elapsed time.",
    points: 1,
    explanation: "From 6:20 to 7:20 is 1 hour. From 7:20 to 7:55 is 35 minutes. Total: 1 hour 35 minutes.",
  },
  {
    id: 5022, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "MD", target: "G", dok: 2, standard: "3.MD.A.2",
    type: "multiple-choice",
    questionText: "A watering can holds 3 liters of water. How many milliliters is that?",
    options: [
      { label: "A", text: "30 mL" },
      { label: "B", text: "300 mL" },
      { label: "C", text: "3,000 mL" },
      { label: "D", text: "30,000 mL" },
    ],
    correctAnswer: "C",
    rubric: "The student converts liters to milliliters.",
    points: 1,
    explanation: "1 liter = 1,000 milliliters, so 3 liters = 3,000 milliliters.",
  },
  {
    id: 5023, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "MD", target: "H", dok: 2, standard: "3.MD.B.3",
    type: "multiple-choice",
    questionText: "A graph shows books read by four classes: Class A = 18, Class B = 24, Class C = 21, Class D = 16. Which class read the most books?",
    options: [
      { label: "A", text: "Class A" },
      { label: "B", text: "Class B" },
      { label: "C", text: "Class C" },
      { label: "D", text: "Class D" },
    ],
    correctAnswer: "B",
    rubric: "The student reads the data correctly.",
    points: 1,
    explanation: "24 is the greatest value, so Class B read the most books.",
  },
  {
    id: 5024, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "MD", target: "H", dok: 2, standard: "3.MD.B.4",
    type: "multiple-choice",
    questionText: "The lengths of ribbons are 4 in., 6 in., 4 in., 8 in., 4 in., and 6 in. What is the most common length?",
    options: [
      { label: "A", text: "4 inches" },
      { label: "B", text: "6 inches" },
      { label: "C", text: "8 inches" },
      { label: "D", text: "10 inches" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies the mode.",
    points: 1,
    explanation: "4 inches appears three times, more than any other length.",
  },
  {
    id: 5025, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "MD", target: "I", dok: 2, standard: "3.MD.C.7",
    type: "text-input",
    questionText: "A rectangle is 9 feet long and 4 feet wide. What is its area in square feet?",
    correctAnswer: "36",
    rubric: "The student enters the correct area.",
    points: 1,
    explanation: "Area = length × width = 9 × 4 = 36 square feet.",
  },
  {
    id: 5026, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "MD", target: "J", dok: 2, standard: "3.MD.D.8",
    type: "text-input",
    questionText: "A rectangle is 9 feet long and 4 feet wide. What is its perimeter in feet?",
    correctAnswer: "26",
    rubric: "The student enters the correct perimeter.",
    points: 1,
    explanation: "Perimeter = 2 × 9 + 2 × 4 = 18 + 8 = 26 feet.",
  },
  {
    id: 5027, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 4, domain: "MD", target: "I", dok: 2, standard: "3.MD.C.7",
    type: "multiple-choice",
    questionText: "A shape is made of two rectangles. Rectangle A has area 12 square units. Rectangle B has area 15 square units. What is the total area?",
    options: [
      { label: "A", text: "3 square units" },
      { label: "B", text: "17 square units" },
      { label: "C", text: "27 square units" },
      { label: "D", text: "180 square units" },
    ],
    correctAnswer: "C",
    rubric: "The student adds the areas of two rectangles.",
    points: 1,
    explanation: "12 + 15 = 27 square units.",
  },
  {
    id: 5028, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "G", target: "K", dok: 1, standard: "3.G.A.1",
    type: "multiple-choice",
    questionText: "How many angles does a pentagon have?",
    options: [
      { label: "A", text: "4" },
      { label: "B", text: "5" },
      { label: "C", text: "6" },
      { label: "D", text: "8" },
    ],
    correctAnswer: "B",
    rubric: "The student identifies a property of a pentagon.",
    points: 1,
    explanation: "A pentagon has 5 sides and 5 angles.",
  },
  {
    id: 5029, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "G", target: "K", dok: 2, standard: "3.G.A.2",
    type: "multiple-choice",
    questionText: "A shape is divided into 10 equal parts. Four parts are shaded. What fraction is NOT shaded?",
    options: [
      { label: "A", text: "4/10" },
      { label: "B", text: "5/10" },
      { label: "C", text: "6/10" },
      { label: "D", text: "10/4" },
    ],
    correctAnswer: "C",
    rubric: "The student finds the unshaded fraction.",
    points: 1,
    explanation: "10 total parts − 4 shaded parts = 6 unshaded parts, so the fraction is 6/10.",
  },
  {
    id: 5030, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 2, domain: "OA", target: "A", dok: 2, standard: "3.OA.A.3",
    type: "text-input",
    questionText: "A theater has 8 rows of seats with 7 seats in each row. How many seats are there in all?",
    correctAnswer: "56",
    rubric: "The student enters the correct total.",
    points: 1,
    explanation: "8 rows × 7 seats = 56 seats.",
  },
  {
    id: 5031, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 2, domain: "OA", target: "D", dok: 2, standard: "3.OA.D.8",
    type: "multiple-choice",
    questionText: "Nina saves $6 each week for 5 weeks. Then she spends $9 on a notebook. How much money does she have left?",
    options: [
      { label: "A", text: "$21" },
      { label: "B", text: "$24" },
      { label: "C", text: "$30" },
      { label: "D", text: "$39" },
    ],
    correctAnswer: "A",
    rubric: "The student solves a two-step problem.",
    points: 1,
    explanation: "First find the total savings: 6 × 5 = 30. Then subtract the amount spent: 30 − 9 = 21.",
  },
  {
    id: 5032, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "NF", target: "F", dok: 2, standard: "3.NF.A.2",
    type: "multiple-choice",
    questionText: "A number line from 0 to 1 is divided into 4 equal parts. Which fraction names the third mark after 0?",
    options: [
      { label: "A", text: "1/4" },
      { label: "B", text: "2/4" },
      { label: "C", text: "3/4" },
      { label: "D", text: "4/3" },
    ],
    correctAnswer: "C",
    rubric: "The student identifies the fraction on a number line.",
    points: 1,
    explanation: "The third mark after 0 on fourths is 3/4.",
  },
  {
    id: 5033, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 1, domain: "MD", target: "G", dok: 2, standard: "3.MD.A.1",
    type: "text-input",
    questionText: "Practice starts at 3:35 p.m. and lasts 50 minutes. What time does practice end?",
    correctAnswer: "4:25",
    rubric: "The student enters the correct end time.",
    points: 1,
    explanation: "Add 25 minutes to get to 4:00, then add 25 more minutes to get 4:25.",
  },
  {
    id: 5034, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 3, domain: "OA", target: "E", dok: 2, standard: "3.OA.A.3",
    type: "multiple-choice",
    questionText: "Which expression matches this situation: 3 shelves with 8 books on each shelf and 2 shelves with 8 books on each shelf?",
    options: [
      { label: "A", text: "(3 + 2) × 8" },
      { label: "B", text: "3 + 2 + 8" },
      { label: "C", text: "3 × 2 × 8" },
      { label: "D", text: "(8 + 8) × 3" },
    ],
    correctAnswer: "A",
    rubric: "The student matches an expression to a situation.",
    points: 1,
    explanation: "There are 5 shelves total, with 8 books on each shelf. That is (3 + 2) × 8.",
  },
  {
    id: 5035, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 4, domain: "MD", target: "H", dok: 2, standard: "3.MD.B.3",
    type: "multiple-choice",
    questionText: "A chart shows the number of apples sold: Monday 14, Tuesday 18, Wednesday 16. How many apples were sold in all?",
    options: [
      { label: "A", text: "34" },
      { label: "B", text: "38" },
      { label: "C", text: "48" },
      { label: "D", text: "58" },
    ],
    correctAnswer: "C",
    rubric: "The student totals the data from the chart.",
    points: 1,
    explanation: "Add 14 + 18 + 16 = 48 apples.",
  },
  {
    id: 5036, practiceTest: 6, testType: "cat", subject: "math", grade: 3,
    claim: 4, domain: "MD", target: "I", dok: 2, standard: "3.MD.C.7",
    type: "multiple-choice",
    questionText: "Rectangle A has side lengths 5 and 4. Rectangle B has side lengths 3 and 6. What is the combined area of the two rectangles?",
    options: [
      { label: "A", text: "18 square units" },
      { label: "B", text: "20 square units" },
      { label: "C", text: "32 square units" },
      { label: "D", text: "38 square units" },
    ],
    correctAnswer: "D",
    rubric: "The student adds the areas of two rectangles.",
    points: 1,
    explanation: "Area A = 5 × 4 = 20. Area B = 3 × 6 = 18. Combined area = 38 square units.",
  },
];

// ══════════════════════════════════════════════════════════════
// PRACTICE TEST 6 — MATH PT (7 questions, IDs 5040–5046)
// Theme: Town Market Day
// ══════════════════════════════════════════════════════════════

const test6MathPT: Question[] = [
  {
    id: 5040, practiceTest: 6, testType: "pt", subject: "math", grade: 3,
    claim: 2, domain: "MD", target: "I", dok: 2, standard: "3.MD.C.7",
    type: "multiple-choice",
    questionText: "A booth at Market Day is 7 feet long and 4 feet wide. What is the area of the booth space?",
    options: [
      { label: "A", text: "11 square feet" },
      { label: "B", text: "22 square feet" },
      { label: "C", text: "28 square feet" },
      { label: "D", text: "30 square feet" },
    ],
    correctAnswer: "C",
    rubric: "The student selects the correct area.",
    points: 1,
    explanation: "Area = length × width = 7 × 4 = 28 square feet.",
  },
  {
    id: 5041, practiceTest: 6, testType: "pt", subject: "math", grade: 3,
    claim: 2, domain: "MD", target: "J", dok: 2, standard: "3.MD.D.8",
    type: "text-input",
    questionText: "The same booth space is 7 feet long and 4 feet wide. How many feet of border are needed to go all the way around it?",
    correctAnswer: "22",
    rubric: "The student enters the correct perimeter.",
    points: 1,
    explanation: "Perimeter = 2 × 7 + 2 × 4 = 14 + 8 = 22 feet.",
  },
  {
    id: 5042, practiceTest: 6, testType: "pt", subject: "math", grade: 3,
    claim: 4, domain: "OA", target: "D", dok: 2, standard: "3.OA.D.8",
    type: "text-input",
    questionText: "A class makes 6 trays of muffins with 8 muffins on each tray. They give away 11 muffins to volunteers. How many muffins are left to sell?",
    correctAnswer: "37",
    rubric: "The student solves the two-step problem correctly.",
    points: 1,
    explanation: "First find the total muffins: 6 × 8 = 48. Then subtract 11: 48 − 11 = 37 muffins left.",
  },
  {
    id: 5043, practiceTest: 6, testType: "pt", subject: "math", grade: 3,
    claim: 3, domain: "OA", target: "E", dok: 2, standard: "3.OA.A.3",
    type: "multiple-choice",
    questionText: "Students pack fruit cups in 4 rows of 6 and snack bags in 3 rows of 6. Which expression shows the total number of items packed?",
    options: [
      { label: "A", text: "(4 + 3) × 6" },
      { label: "B", text: "4 × 3 × 6" },
      { label: "C", text: "(6 + 6) × 3" },
      { label: "D", text: "4 + 3 + 6" },
    ],
    correctAnswer: "A",
    rubric: "The student chooses the correct expression.",
    points: 1,
    explanation: "There are 7 rows total and each row has 6 items, so the expression is (4 + 3) × 6.",
  },
  {
    id: 5044, practiceTest: 6, testType: "pt", subject: "math", grade: 3,
    claim: 2, domain: "NF", target: "F", dok: 2, standard: "3.NF.A.1",
    type: "multiple-choice",
    questionText: "A tray is divided into 10 equal spaces. Seven spaces are filled with cookies. What fraction of the tray is filled?",
    options: [
      { label: "A", text: "7/10" },
      { label: "B", text: "3/10" },
      { label: "C", text: "10/7" },
      { label: "D", text: "1/7" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies the correct fraction.",
    points: 1,
    explanation: "Seven out of ten equal spaces are filled, so the fraction is 7/10.",
  },
  {
    id: 5045, practiceTest: 6, testType: "pt", subject: "math", grade: 3,
    claim: 4, domain: "OA", target: "D", dok: 3, standard: "3.OA.D.8",
    type: "short-answer",
    questionText: "The class earned $84 from sales. They spent $39 on supplies and $18 on decorations. Do they have enough money left to buy a new sign that costs $30? Show your work and explain.",
    correctAnswer: "They spent $39 + $18 = $57. Then $84 - $57 = $27. Since $27 is less than $30, they do not have enough money left to buy the sign.",
    rubric: "Full credit (2 points): Correct conclusion with clear work. 1 point: Correct method with a minor error or incomplete explanation.",
    points: 2,
    explanation: "Add the expenses first: 39 + 18 = 57. Then subtract from 84 to get 27. Because 27 is less than 30, the sign cannot be bought.",
  },
  {
    id: 5046, practiceTest: 6, testType: "pt", subject: "math", grade: 3,
    claim: 2, domain: "MD", target: "G", dok: 2, standard: "3.MD.A.1",
    type: "multiple-choice",
    questionText: "Market Day opens at 10:15 a.m. and closes at 12:45 p.m. How long is Market Day open?",
    options: [
      { label: "A", text: "2 hours" },
      { label: "B", text: "2 hours 15 minutes" },
      { label: "C", text: "2 hours 30 minutes" },
      { label: "D", text: "2 hours 45 minutes" },
    ],
    correctAnswer: "C",
    rubric: "The student finds the elapsed time.",
    points: 1,
    explanation: "From 10:15 to 12:15 is 2 hours, and from 12:15 to 12:45 is 30 minutes. Total: 2 hours 30 minutes.",
  },
];

// ══════════════════════════════════════════════════════════════
// PRACTICE TEST 6 — ELA CAT (37 questions, IDs 5101–5137)
// ══════════════════════════════════════════════════════════════

const test6ELACAT: Question[] = [
  {
    id: 5101, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "1", dok: 2, standard: "RL.1",
    type: "multiple-choice",
    passage: lanternBridgePassage, passageTitle: "The Lantern Bridge",
    questionText: "Why was the bridge closed on the day of the lantern walk?",
    options: [
      { label: "A", text: "It was being painted" },
      { label: "B", text: "Several boards were loosened by a storm" },
      { label: "C", text: "The town wanted people to use the park instead" },
      { label: "D", text: "Mr. Vega forgot to unlock it" },
    ],
    correctAnswer: "B",
    rubric: "The student identifies a key detail from the story.",
    points: 1,
    explanation: "Mr. Vega explains that last night's storm loosened several boards, so the bridge was not safe.",
  },
  {
    id: 5102, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "2", dok: 2, standard: "RL.2",
    type: "multiple-choice",
    passage: lanternBridgePassage, passageTitle: "The Lantern Bridge",
    questionText: "What is one theme of the story?",
    options: [
      { label: "A", text: "A tradition can continue even when it changes" },
      { label: "B", text: "Storms always ruin outdoor events" },
      { label: "C", text: "Older people dislike change" },
      { label: "D", text: "Bridges are more important than people" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies the story's theme.",
    points: 1,
    explanation: "The story shows that the tradition survived in a new form. The event changed locations, but people still came together.",
  },
  {
    id: 5103, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "3", dok: 2, standard: "RL.3",
    type: "multiple-choice",
    passage: lanternBridgePassage, passageTitle: "The Lantern Bridge",
    questionText: "How do Maya's feelings change during the story?",
    options: [
      { label: "A", text: "She is excited at first and angry at the end" },
      { label: "B", text: "She is worried at first and proud by the end" },
      { label: "C", text: "She is bored at first and confused later" },
      { label: "D", text: "She is calm at first and frightened later" },
    ],
    correctAnswer: "B",
    rubric: "The student analyzes character change.",
    points: 1,
    explanation: "At first Maya thinks the lantern walk is ruined. By the end, she says it might be her favorite lantern walk yet.",
  },
  {
    id: 5104, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "4", dok: 2, standard: "RL.4",
    type: "multiple-choice",
    passage: lanternBridgePassage, passageTitle: "The Lantern Bridge",
    questionText: 'What does Grandma most likely mean when she says, "Traditions can bend without breaking"?',
    options: [
      { label: "A", text: "Traditions should never change" },
      { label: "B", text: "A tradition can be adjusted and still keep its meaning" },
      { label: "C", text: "Bridges are easy to repair" },
      { label: "D", text: "People should stop following traditions" },
    ],
    correctAnswer: "B",
    rubric: "The student interprets figurative language.",
    points: 1,
    explanation: "Grandma means the town could change the event and still keep the important idea of coming together.",
  },
  {
    id: 5105, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "5", dok: 2, standard: "RL.5",
    type: "multiple-choice",
    passage: lanternBridgePassage, passageTitle: "The Lantern Bridge",
    questionText: "Which event happens first?",
    options: [
      { label: "A", text: "Families hang lanterns between two trees" },
      { label: "B", text: "Maya sees the bridge closed sign" },
      { label: "C", text: "Mr. Vega rings a brass bell" },
      { label: "D", text: "The bakery sends trays of warm rolls" },
    ],
    correctAnswer: "B",
    rubric: "The student identifies the sequence of events.",
    points: 1,
    explanation: "The story begins with Maya and Eli seeing the sign that says the bridge is closed.",
  },
  {
    id: 5106, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "6", dok: 2, standard: "RL.6",
    type: "multiple-choice",
    passage: lanternBridgePassage, passageTitle: "The Lantern Bridge",
    questionText: "Which statement best describes Grandma's point of view?",
    options: [
      { label: "A", text: "She believes the tradition should be canceled" },
      { label: "B", text: "She believes the bridge matters more than the people" },
      { label: "C", text: "She believes the purpose of the tradition is more important than the location" },
      { label: "D", text: "She thinks children should not help plan events" },
    ],
    correctAnswer: "C",
    rubric: "The student identifies a character's point of view.",
    points: 1,
    explanation: "Grandma says the lantern walk was never only about the bridge. She values the meaning behind the tradition.",
  },
  {
    id: 5107, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "1", dok: 2, standard: "RL.1",
    type: "multiple-choice",
    passage: lanternBridgePassage, passageTitle: "The Lantern Bridge",
    questionText: "What did Maya paint on her lantern this year?",
    options: [
      { label: "A", text: "A fox and red leaves" },
      { label: "B", text: "Silver fish and tiny blue waves" },
      { label: "C", text: "A moon and yellow stars" },
      { label: "D", text: "A bridge and a bell" },
    ],
    correctAnswer: "B",
    rubric: "The student recalls a detail from the text.",
    points: 1,
    explanation: "The passage says Maya painted her lantern with silver fish and tiny blue waves.",
  },
  {
    id: 5108, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "3", dok: 2, standard: "RL.3",
    type: "multiple-choice",
    passage: lanternBridgePassage, passageTitle: "The Lantern Bridge",
    questionText: "Why does Eli say, 'Not ruined. Just changed'?",
    options: [
      { label: "A", text: "He thinks someone else will repair the bridge in time" },
      { label: "B", text: "He believes the event can still happen in a different way" },
      { label: "C", text: "He wants to stay home instead" },
      { label: "D", text: "He does not care about the lantern walk" },
    ],
    correctAnswer: "B",
    rubric: "The student interprets a character's words.",
    points: 1,
    explanation: "Eli is saying the tradition can continue even if it does not happen on the bridge.",
  },
  {
    id: 5109, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "2", dok: 2, standard: "RL.2",
    type: "multiple-choice",
    passage: lanternBridgePassage, passageTitle: "The Lantern Bridge",
    questionText: "Which detail best supports the idea that the whole town helped save the event?",
    options: [
      { label: "A", text: "Maya rode her bike to the creek" },
      { label: "B", text: "Strings of white lights hung between the trees, and families stood together in the park" },
      { label: "C", text: "The water moved below the bridge" },
      { label: "D", text: "Maya remembered last year's lantern" },
    ],
    correctAnswer: "B",
    rubric: "The student selects supporting evidence for a theme or idea.",
    points: 1,
    explanation: "Those details show many people worked together to create the new celebration.",
  },
  {
    id: 5110, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "4", dok: 2, standard: "RL.4",
    type: "multiple-choice",
    passage: lanternBridgePassage, passageTitle: "The Lantern Bridge",
    questionText: 'What does the word "shimmered" help the reader picture?',
    options: [
      { label: "A", text: "The lights moved and sparkled on the water" },
      { label: "B", text: "The pond turned dark black" },
      { label: "C", text: "The lanterns sank into the pond" },
      { label: "D", text: "The park became noisy" },
    ],
    correctAnswer: "A",
    rubric: "The student determines meaning from context.",
    points: 1,
    explanation: "Shimmered suggests the reflections were shining with a soft, moving sparkle.",
  },
  {
    id: 5111, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "7", dok: 2, standard: "RI.1",
    type: "multiple-choice",
    passage: riverPassage, passageTitle: "How Rivers Shape the Land",
    questionText: "What is a river's beginning called?",
    options: [
      { label: "A", text: "Its valley" },
      { label: "B", text: "Its source" },
      { label: "C", text: "Its sediment" },
      { label: "D", text: "Its mouth wall" },
    ],
    correctAnswer: "B",
    rubric: "The student identifies a key detail from the informational text.",
    points: 1,
    explanation: "The passage states that a river's beginning is called its source.",
  },
  {
    id: 5112, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "8", dok: 2, standard: "RI.2",
    type: "multiple-choice",
    passage: riverPassage, passageTitle: "How Rivers Shape the Land",
    questionText: "What is the main idea of the passage?",
    options: [
      { label: "A", text: "Rivers only help fish survive" },
      { label: "B", text: "Rivers can change land and are important to life" },
      { label: "C", text: "Rivers always flow in straight lines" },
      { label: "D", text: "Only large rivers matter" },
    ],
    correctAnswer: "B",
    rubric: "The student identifies the main idea.",
    points: 1,
    explanation: "The passage explains both how rivers shape land and why they matter to people, animals, and the environment.",
  },
  {
    id: 5113, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "9", dok: 2, standard: "RI.3",
    type: "multiple-choice",
    passage: riverPassage, passageTitle: "How Rivers Shape the Land",
    questionText: "How does flowing water help erosion happen?",
    options: [
      { label: "A", text: "It paints the riverbanks" },
      { label: "B", text: "It carries sand, soil, and rocks that scrape the land" },
      { label: "C", text: "It makes the river warmer" },
      { label: "D", text: "It stops weathering from happening" },
    ],
    correctAnswer: "B",
    rubric: "The student explains a cause-and-effect relationship.",
    points: 1,
    explanation: "The passage says the materials carried by water bump and scrape along the bottom, helping wear the land away.",
  },
  {
    id: 5114, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "10", dok: 2, standard: "RI.4",
    type: "multiple-choice",
    passage: riverPassage, passageTitle: "How Rivers Shape the Land",
    questionText: 'What does the word "meanders" mean in the passage?',
    options: [
      { label: "A", text: "Fast waterfalls" },
      { label: "B", text: "Curves or bends in a river" },
      { label: "C", text: "Large river mouths" },
      { label: "D", text: "Pieces of broken rock" },
    ],
    correctAnswer: "B",
    rubric: "The student determines word meaning from context.",
    points: 1,
    explanation: "The sentence explains that rivers often curve and bend, and then names those bends meanders.",
  },
  {
    id: 5115, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "11", dok: 2, standard: "RI.5",
    type: "multiple-choice",
    passage: riverPassage, passageTitle: "How Rivers Shape the Land",
    questionText: "Why does the author use bold section headings?",
    options: [
      { label: "A", text: "To separate the passage into topics" },
      { label: "B", text: "To show which words rhyme" },
      { label: "C", text: "To tell a story in order" },
      { label: "D", text: "To make the text shorter" },
    ],
    correctAnswer: "A",
    rubric: "The student understands a text feature.",
    points: 1,
    explanation: "The headings organize the information into clear sections so readers can follow different ideas.",
  },
  {
    id: 5116, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "12", dok: 2, standard: "RI.6",
    type: "multiple-choice",
    passage: riverPassage, passageTitle: "How Rivers Shape the Land",
    questionText: "What is the author's main purpose in writing this passage?",
    options: [
      { label: "A", text: "To entertain readers with a river story" },
      { label: "B", text: "To persuade readers to build a dam" },
      { label: "C", text: "To inform readers about how rivers change land and why they matter" },
      { label: "D", text: "To compare rivers and oceans" },
    ],
    correctAnswer: "C",
    rubric: "The student identifies the author's purpose.",
    points: 1,
    explanation: "The passage gives facts and explanations about rivers, so its purpose is to inform.",
  },
  {
    id: 5117, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "7", dok: 2, standard: "RI.1",
    type: "multiple-choice",
    passage: riverPassage, passageTitle: "How Rivers Shape the Land",
    questionText: "According to the passage, where can sediment build up?",
    options: [
      { label: "A", text: "Only at the source of a river" },
      { label: "B", text: "Along riverbanks or near the river's mouth" },
      { label: "C", text: "Only in deep canyons" },
      { label: "D", text: "Only under bridges" },
    ],
    correctAnswer: "B",
    rubric: "The student recalls a supporting detail.",
    points: 1,
    explanation: "The passage says sediment can build up along riverbanks or near the mouth of a river.",
  },
  {
    id: 5118, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "8", dok: 2, standard: "RI.2",
    type: "multiple-choice",
    passage: riverPassage, passageTitle: "How Rivers Shape the Land",
    questionText: "What is the main idea of the section called 'Why Rivers Matter'?",
    options: [
      { label: "A", text: "Rivers are important because they support people, animals, and ecosystems" },
      { label: "B", text: "Rivers are too dangerous to use" },
      { label: "C", text: "Only birds need rivers" },
      { label: "D", text: "Rivers do not need protection" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies the main idea of a section.",
    points: 1,
    explanation: "That section explains how rivers provide water, habitats, transportation, and recreation.",
  },
  {
    id: 5119, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "9", dok: 2, standard: "RI.3",
    type: "multiple-choice",
    passage: riverPassage, passageTitle: "How Rivers Shape the Land",
    questionText: "What happens as tiny streams join together?",
    options: [
      { label: "A", text: "They form larger creeks and rivers" },
      { label: "B", text: "They disappear into the ground" },
      { label: "C", text: "They freeze permanently" },
      { label: "D", text: "They stop moving downhill" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies how ideas are connected in the text.",
    points: 1,
    explanation: "The passage states that as tiny streams join together, they form larger creeks and rivers.",
  },
  {
    id: 5120, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "10", dok: 2, standard: "RI.4",
    type: "multiple-choice",
    passage: riverPassage, passageTitle: "How Rivers Shape the Land",
    questionText: 'What does the word "sediment" mean in the passage?',
    options: [
      { label: "A", text: "Dropped sand, soil, and rock" },
      { label: "B", text: "A river's source" },
      { label: "C", text: "A type of fish habitat" },
      { label: "D", text: "A deep canyon wall" },
    ],
    correctAnswer: "A",
    rubric: "The student determines the meaning of a science term.",
    points: 1,
    explanation: "The passage directly explains that sediment is the material rivers drop when they slow down.",
  },
  {
    id: 5121, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "11", dok: 2, standard: "RI.5",
    type: "multiple-choice",
    passage: riverPassage, passageTitle: "How Rivers Shape the Land",
    questionText: "Which section mostly explains how rivers wear away land?",
    options: [
      { label: "A", text: "Where Rivers Begin" },
      { label: "B", text: "Erosion and Weathering" },
      { label: "C", text: "Why Rivers Matter" },
      { label: "D", text: "Dropping Sediment" },
    ],
    correctAnswer: "B",
    rubric: "The student uses text structure to locate information.",
    points: 1,
    explanation: "The section titled 'Erosion and Weathering' explains how rivers wear away land.",
  },
  {
    id: 5122, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "12", dok: 2, standard: "RI.6",
    type: "multiple-choice",
    passage: riverPassage, passageTitle: "How Rivers Shape the Land",
    questionText: "Which sentence best shows the author thinks rivers should be protected?",
    options: [
      { label: "A", text: "Many rivers begin in mountains or hills" },
      { label: "B", text: "Because rivers are so important, many communities work to protect them" },
      { label: "C", text: "Rivers do not always flow in straight lines" },
      { label: "D", text: "Fish lay eggs in riverbeds" },
    ],
    correctAnswer: "B",
    rubric: "The student identifies the author's viewpoint from the text.",
    points: 1,
    explanation: "That sentence directly states that communities work to protect rivers because they are important.",
  },
  {
    id: 5123, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 2, target: "13", dok: 2, standard: "L.3.1",
    type: "multiple-choice",
    passage: lanternBridgePassage,
    passageTitle: "The Lantern Bridge",
    questionText: "Which sentence uses commas correctly?",
    options: [
      { label: "A", text: "Maya Eli and Grandma made calls all afternoon." },
      { label: "B", text: "Maya, Eli, and Grandma made calls all afternoon." },
      { label: "C", text: "Maya Eli, and Grandma made calls all afternoon." },
      { label: "D", text: "Maya, Eli and, Grandma made calls all afternoon." },
    ],
    correctAnswer: "B",
    rubric: "The student identifies correct comma use in a series.",
    points: 1,
    explanation: "Items in a series should be separated with commas: Maya, Eli, and Grandma.",
  },
  {
    id: 5124, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 2, target: "14", dok: 2, standard: "L.3.2",
    type: "multiple-choice",
    passage: riverPassage,
    passageTitle: "How Rivers Shape the Land",
    questionText: "Which sentence is punctuated correctly?",
    options: [
      { label: "A", text: "Rivers are important because they provide water food and habitats." },
      { label: "B", text: "Rivers are important, because they provide water, food, and habitats." },
      { label: "C", text: "Rivers are important because they provide water, food, and habitats." },
      { label: "D", text: "Rivers are important because, they provide water food and habitats." },
    ],
    correctAnswer: "C",
    rubric: "The student identifies correct punctuation.",
    points: 1,
    explanation: "The list water, food, and habitats is correctly punctuated in choice C.",
  },
  {
    id: 5125, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 2, target: "15", dok: 2, standard: "L.3.4",
    type: "multiple-choice",
    passage: lanternBridgePassage,
    passageTitle: "The Lantern Bridge",
    questionText: 'What does the word "tradition" most nearly mean in the story?',
    options: [
      { label: "A", text: "A machine used for repairs" },
      { label: "B", text: "An event or custom that people repeat over time" },
      { label: "C", text: "A kind of lantern" },
      { label: "D", text: "A bridge warning sign" },
    ],
    correctAnswer: "B",
    rubric: "The student determines the meaning of a word from context.",
    points: 1,
    explanation: "The lantern walk happens every autumn, so tradition means a repeated custom or event.",
  },
  {
    id: 5126, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 2, target: "16", dok: 2, standard: "L.3.5",
    type: "multiple-choice",
    passage: riverPassage,
    passageTitle: "How Rivers Shape the Land",
    questionText: "Which word is an antonym for 'healthy'?",
    options: [
      { label: "A", text: "Strong" },
      { label: "B", text: "Sick" },
      { label: "C", text: "Fresh" },
      { label: "D", text: "Natural" },
    ],
    correctAnswer: "B",
    rubric: "The student identifies an antonym.",
    points: 1,
    explanation: "An antonym is a word with the opposite meaning. The opposite of healthy is sick.",
  },
  {
    id: 5127, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 2, target: "17", dok: 2, standard: "L.3.6",
    type: "multiple-choice",
    passage: lanternBridgePassage,
    passageTitle: "The Lantern Bridge",
    questionText: "Which word means nearly the same as 'glowed'?",
    options: [
      { label: "A", text: "Shined" },
      { label: "B", text: "Dropped" },
      { label: "C", text: "Whispered" },
      { label: "D", text: "Hidden" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies a synonym.",
    points: 1,
    explanation: "Glowed means shined with light.",
  },
  {
    id: 5128, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 3, target: "18", dok: 2, standard: "SL.3.1",
    type: "multiple-choice",
    passage: lanternBridgePassage,
    passageTitle: "The Lantern Bridge",
    questionText: "Which question would best help a class discuss how the town solved the problem?",
    options: [
      { label: "A", text: "What color were the lanterns?" },
      { label: "B", text: "How did different people work together to create the new event?" },
      { label: "C", text: "Why do bridges have boards?" },
      { label: "D", text: "What foods do you like at festivals?" },
    ],
    correctAnswer: "B",
    rubric: "The student identifies a discussion question that focuses on the text's ideas.",
    points: 1,
    explanation: "That question asks students to talk about the problem and the town's teamwork, which is central to the story.",
  },
  {
    id: 5129, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 3, target: "19", dok: 2, standard: "SL.3.2",
    type: "multiple-choice",
    passage: riverPassage,
    passageTitle: "How Rivers Shape the Land",
    questionText: "If a student gave a presentation about rivers, which detail from the passage would be most important to include?",
    options: [
      { label: "A", text: "Rivers can shape land through erosion and also support life" },
      { label: "B", text: "Some bridges are made of wood" },
      { label: "C", text: "Families enjoy festivals in parks" },
      { label: "D", text: "Lanterns can be painted with leaves and moons" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies relevant supporting information.",
    points: 1,
    explanation: "That detail captures the passage's major ideas about how rivers change land and why they matter.",
  },
  {
    id: 5130, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 4, target: "20", dok: 2, standard: "RI.3.9",
    type: "multiple-choice",
    passage: riverPassage,
    passageTitle: "How Rivers Shape the Land",
    questionText: "Which detail best supports the idea that rivers affect both land and living things?",
    options: [
      { label: "A", text: "Rivers carry water from one place to another" },
      { label: "B", text: "Rivers can create habitats for plants and animals and can also carve paths through earth and stone" },
      { label: "C", text: "Some rivers begin in mountains or hills" },
      { label: "D", text: "People use rivers for recreation" },
    ],
    correctAnswer: "B",
    rubric: "The student selects evidence that supports a combined idea.",
    points: 1,
    explanation: "Choice B includes one detail about shaping land and one about supporting living things.",
  },
  {
    id: 5131, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 4, target: "21", dok: 3, standard: "RL.3.9",
    type: "multiple-choice",
    passage: lanternBridgePassage + "\n\n---\n\n" + riverPassage,
    passageTitle: "The Lantern Bridge / How Rivers Shape the Land",
    questionText: "How are the two passages alike?",
    options: [
      { label: "A", text: "Both explain how storms create canyons" },
      { label: "B", text: "Both include a river or creek as an important part of the setting or topic" },
      { label: "C", text: "Both are fictional stories about one family" },
      { label: "D", text: "Both are instructions for community events" },
    ],
    correctAnswer: "B",
    rubric: "The student compares information across two texts.",
    points: 1,
    explanation: "The story takes place near Pine Creek, and the article explains rivers and streams. Water is important in both passages.",
  },
  {
    id: 5132, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 4, target: "22", dok: 3, standard: "RL.3.9",
    type: "multiple-choice",
    passage: lanternBridgePassage + "\n\n---\n\n" + riverPassage,
    passageTitle: "The Lantern Bridge / How Rivers Shape the Land",
    questionText: "Which statement best describes a difference between the two passages?",
    options: [
      { label: "A", text: "The first passage tells a story, while the second passage explains facts" },
      { label: "B", text: "The first passage explains facts, while the second tells a story" },
      { label: "C", text: "Both passages are poems" },
      { label: "D", text: "Both passages are written as directions" },
    ],
    correctAnswer: "A",
    rubric: "The student distinguishes text types across two passages.",
    points: 1,
    explanation: "The Lantern Bridge is fiction, while How Rivers Shape the Land is informational text.",
  },
  {
    id: 5133, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "1", dok: 2, standard: "RL.1",
    type: "short-answer",
    passage: lanternBridgePassage,
    passageTitle: "The Lantern Bridge",
    questionText: "Why does Maya decide the new lantern walk is still special? Use 2 details from the story.",
    correctAnswer: "Maya sees that people still came together, and the park was filled with lights, lanterns, and neighbors celebrating. She realizes the tradition was about the community, not only the bridge.",
    rubric: "The student explains Maya's thinking using at least two details. 2 points: clear explanation with two details; 1 point: partial explanation or only one detail.",
    points: 2,
    explanation: "A strong answer mentions the community working together and the glowing lantern display in the park.",
  },
  {
    id: 5134, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 1, target: "7", dok: 2, standard: "RI.1",
    type: "short-answer",
    passage: riverPassage,
    passageTitle: "How Rivers Shape the Land",
    questionText: "Explain how erosion and sediment are connected. Write 2-3 sentences.",
    correctAnswer: "Erosion happens when flowing water wears away land and carries pieces of sand, soil, and rock. When the river slows down, it can drop those materials, and the dropped materials are called sediment.",
    rubric: "The student explains the relationship between the two ideas. 2 points: clear connection; 1 point: partial explanation.",
    points: 2,
    explanation: "Erosion moves material, and sediment is the material that gets dropped when the river slows down.",
  },
  {
    id: 5135, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 2, target: "15", dok: 2, standard: "L.3.4",
    type: "text-input",
    passage: riverPassage,
    passageTitle: "How Rivers Shape the Land",
    questionText: "What is one natural force besides rivers that the passage says helped shape the Grand Canyon?",
    correctAnswer: "Weathering",
    rubric: "Accept weathering, wind, water, ice, or temperature changes.",
    points: 1,
    explanation: "The passage says the Grand Canyon was shaped by the Colorado River and other natural forces, including weathering processes.",
  },
  {
    id: 5136, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 2, target: "16", dok: 2, standard: "L.3.5",
    type: "multiple-choice",
    passage: lanternBridgePassage,
    passageTitle: "The Lantern Bridge",
    questionText: "Which phrase from the story helps create a feeling of warmth and celebration?",
    options: [
      { label: "A", text: "bright orange sign" },
      { label: "B", text: "storm loosened several boards" },
      { label: "C", text: "strings of white lights hung between the trees" },
      { label: "D", text: "dark water moving below the bridge" },
    ],
    correctAnswer: "C",
    rubric: "The student identifies language that creates mood.",
    points: 1,
    explanation: "That image makes the park feel welcoming, bright, and festive.",
  },
  {
    id: 5137, practiceTest: 6, testType: "cat", subject: "ela", grade: 3,
    claim: 4, target: "23", dok: 3, standard: "RI.3.9",
    type: "multiple-choice",
    passage: lanternBridgePassage + "\n\n---\n\n" + riverPassage,
    passageTitle: "The Lantern Bridge / How Rivers Shape the Land",
    questionText: "Which idea is supported by BOTH passages?",
    options: [
      { label: "A", text: "Natural places can affect how people live and what communities do" },
      { label: "B", text: "Bridges should always be built over rivers" },
      { label: "C", text: "Families should never change their traditions" },
      { label: "D", text: "Only scientists can help protect waterways" },
    ],
    correctAnswer: "A",
    rubric: "The student identifies a shared idea across both texts.",
    points: 1,
    explanation: "The creek affects the lantern walk in the story, and rivers affect land, wildlife, and human communities in the article.",
  },
];

// ══════════════════════════════════════════════════════════════
// PRACTICE TEST 6 — ELA PT (4 questions, IDs 5150–5153)
// ══════════════════════════════════════════════════════════════

const test6ELAPT: Question[] = [
  {
    id: 5150, practiceTest: 6, testType: "pt", subject: "ela", grade: 3,
    claim: 1, target: "1", dok: 2, standard: "RL.3.1",
    type: "multiple-choice",
    passage: lanternBridgePassage + "\n\n---\n\n" + riverPassage,
    passageTitle: "The Lantern Bridge / How Rivers Shape the Land",
    questionText: "Which detail from BOTH passages shows that water can influence a community?",
    options: [
      { label: "A", text: "Pine Creek changed the lantern walk, and rivers provide water and habitats that communities depend on" },
      { label: "B", text: "Maya painted fish, and rivers always flow straight" },
      { label: "C", text: "The bakery sent rolls, and fish lay eggs" },
      { label: "D", text: "The bridge was wooden, and sediment can build up" },
    ],
    correctAnswer: "A",
    rubric: "The student connects evidence across both sources.",
    points: 1,
    explanation: "In the story, the creek and bridge affect the town's tradition. In the article, rivers affect communities by supplying water and habitats.",
  },
  {
    id: 5151, practiceTest: 6, testType: "pt", subject: "ela", grade: 3,
    claim: 4, target: "2", dok: 3, standard: "RI.3.9",
    type: "multiple-choice",
    passage: lanternBridgePassage + "\n\n---\n\n" + riverPassage,
    passageTitle: "The Lantern Bridge / How Rivers Shape the Land",
    questionText: "How are the two passages mostly different?",
    options: [
      { label: "A", text: "One is about a community event, and the other explains science ideas about rivers" },
      { label: "B", text: "Both are only about animals" },
      { label: "C", text: "One gives directions, and the other is a poem" },
      { label: "D", text: "Both are personal letters" },
    ],
    correctAnswer: "A",
    rubric: "The student compares the focus of two texts.",
    points: 1,
    explanation: "The first text is a narrative about a town tradition, while the second text is an informational article about rivers.",
  },
  {
    id: 5152, practiceTest: 6, testType: "pt", subject: "ela", grade: 3,
    claim: 2, target: "3", dok: 3, standard: "W.3.9",
    type: "short-answer",
    passage: lanternBridgePassage + "\n\n---\n\n" + riverPassage,
    passageTitle: "The Lantern Bridge / How Rivers Shape the Land",
    questionText: "Both passages show that people are connected to waterways. Explain one way the town in 'The Lantern Bridge' is connected to Pine Creek and one way people are connected to rivers in the article. Write 2-3 sentences.",
    correctAnswer: "The town in The Lantern Bridge is connected to Pine Creek because the bridge and creek are part of the lantern walk tradition. In the article, people are connected to rivers because rivers provide water, transportation, and places for recreation.",
    rubric: "2 points: response includes one clear example from each text. 1 point: response includes only one text or is partly correct.",
    points: 2,
    explanation: "A strong answer gives one example from the story and one from the article to show how people depend on waterways.",
  },
  {
    id: 5153, practiceTest: 6, testType: "pt", subject: "ela", grade: 3,
    claim: 2, target: "4", dok: 4, standard: "W.3.2",
    type: "extended-writing",
    passage: lanternBridgePassage + "\n\n---\n\n" + riverPassage,
    passageTitle: "The Lantern Bridge / How Rivers Shape the Land",
    studentDirections: "You have read 'The Lantern Bridge' and 'How Rivers Shape the Land.' Now write an informational paragraph or short essay explaining why waterways matter to communities.\n\nIn your response:\n- State your main idea clearly\n- Use at least one detail from 'The Lantern Bridge'\n- Use at least one detail from 'How Rivers Shape the Land'\n- Explain how the details support your main idea\n- Use complete sentences and correct punctuation",
    questionText: "Write an informational response explaining why waterways matter to communities. Use details from BOTH passages.",
    correctAnswer: "Responses will vary. See rubric.",
    rubric: "4 points: clear main idea, accurate details from both sources, organized explanation, and mostly correct conventions. 3 points: uses both sources with some detail but less development or some errors. 2 points: uses only one source well or both sources weakly. 1 point: minimal response. 0 points: off-topic or blank.",
    points: 4,
    explanation: "A strong response explains that waterways matter because they shape land, provide habitats and water, and can also affect traditions and community life, as shown in both passages.",
  },
];

export const mediumPracticeTestQuestions: Question[] = [
  ...test6MathCAT,
  ...test6MathPT,
  ...test6ELACAT,
  ...test6ELAPT,
];
